// Generated by CIRCT firtool-1.135.0
module Conversion_12(
  input  [4:0]  io_q_j_1,
  input  [63:0] io_pre_q_A,
  input  [63:0] io_pre_q_B,
  output [63:0] io_nxt_q_A,
  output [63:0] io_nxt_q_B
);

  wire [63:0] new_q_A_1 = {io_pre_q_A[61:0], 2'h1};
  wire [63:0] new_q_A_2 = {io_pre_q_A[61:0], 2'h0};
  wire [63:0] new_q_A_3 = {io_pre_q_B[61:0], 2'h3};
  wire [63:0] new_q_A_4 = {io_pre_q_B[61:0], 2'h2};
  assign io_nxt_q_A =
    (io_q_j_1[0] ? {io_pre_q_A[61:0], 2'h2} : 64'h0) | (io_q_j_1[1] ? new_q_A_1 : 64'h0)
    | (io_q_j_1[2] ? new_q_A_2 : 64'h0) | (io_q_j_1[3] ? new_q_A_3 : 64'h0)
    | (io_q_j_1[4] ? new_q_A_4 : 64'h0);
  assign io_nxt_q_B =
    (io_q_j_1[0] ? new_q_A_1 : 64'h0) | (io_q_j_1[1] ? new_q_A_2 : 64'h0)
    | (io_q_j_1[2] ? new_q_A_3 : 64'h0) | (io_q_j_1[3] ? new_q_A_4 : 64'h0)
    | (io_q_j_1[4] ? {io_pre_q_B[61:0], 2'h1} : 64'h0);
endmodule

