// Generated by CIRCT firtool-1.135.0
module Pipeline_24(
  input         clock,
  input         reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [9:0]  io_in_bits_set,
  input  [3:0]  io_in_bits_way,
  input  [29:0] io_in_bits_tag,
  input         io_out_ready,
  output        io_out_valid,
  output [9:0]  io_out_bits_set,
  output [3:0]  io_out_bits_way,
  output [29:0] io_out_bits_tag
);

  Queue1_ClientTagWrite stages_0 (
    .clock           (clock),
    .reset           (reset),
    .io_enq_ready    (io_in_ready),
    .io_enq_valid    (io_in_valid),
    .io_enq_bits_set (io_in_bits_set),
    .io_enq_bits_way (io_in_bits_way),
    .io_enq_bits_tag (io_in_bits_tag),
    .io_deq_ready    (io_out_ready),
    .io_deq_valid    (io_out_valid),
    .io_deq_bits_set (io_out_bits_set),
    .io_deq_bits_way (io_out_bits_way),
    .io_deq_bits_tag (io_out_bits_tag)
  );
endmodule

