// Generated by CIRCT firtool-1.135.0
module Pmaaddr2Module(
  output [63:0] rdata,
  output [63:0] regOut_ALL,
  input  [63:0] addrRData_2,
  input  [63:0] addrRegOut_2
);

  assign rdata = addrRData_2;
  assign regOut_ALL = addrRegOut_2;
endmodule

