// Generated by CIRCT firtool-1.135.0
module r4_qds_spec(
  input  [8:0] rem_i,
  input  [8:0] sqrt_csa_val_neg_2_msbs_i,
  input  [8:0] sqrt_csa_val_neg_1_msbs_i,
  input  [8:0] sqrt_csa_val_pos_1_msbs_i,
  input  [8:0] sqrt_csa_val_pos_2_msbs_i,
  input  [6:0] m_neg_1_neg_2_i,
  input  [6:0] m_neg_0_neg_2_i,
  input  [6:0] m_pos_1_neg_2_i,
  input  [6:0] m_pos_2_neg_2_i,
  input  [6:0] m_neg_1_neg_1_i,
  input  [6:0] m_neg_0_neg_1_i,
  input  [6:0] m_pos_1_neg_1_i,
  input  [6:0] m_pos_2_neg_1_i,
  input  [6:0] m_neg_1_neg_0_i,
  input  [6:0] m_neg_0_neg_0_i,
  input  [6:0] m_pos_1_neg_0_i,
  input  [6:0] m_pos_2_neg_0_i,
  input  [6:0] m_neg_1_pos_1_i,
  input  [6:0] m_neg_0_pos_1_i,
  input  [6:0] m_pos_1_pos_1_i,
  input  [6:0] m_pos_2_pos_1_i,
  input  [6:0] m_neg_1_pos_2_i,
  input  [6:0] m_neg_0_pos_2_i,
  input  [6:0] m_pos_1_pos_2_i,
  input  [6:0] m_pos_2_pos_2_i,
  input  [4:0] prev_rt_dig_i,
  output [4:0] rt_dig_o
);

  wire [8:0] _qds_sign_spec_4_T_18 = 9'(rem_i + sqrt_csa_val_neg_2_msbs_i);
  wire [8:0] _qds_sign_spec_4_T_3 = 9'(_qds_sign_spec_4_T_18 + {m_pos_2_neg_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_4_T_9 = 9'(_qds_sign_spec_4_T_18 + {m_pos_1_neg_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_4_T_15 = 9'(_qds_sign_spec_4_T_18 + {m_neg_0_neg_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_4_T_21 = 9'(_qds_sign_spec_4_T_18 + {m_neg_1_neg_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_3_T_18 = 9'(rem_i + sqrt_csa_val_neg_1_msbs_i);
  wire [8:0] _qds_sign_spec_3_T_3 = 9'(_qds_sign_spec_3_T_18 + {m_pos_2_neg_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_3_T_9 = 9'(_qds_sign_spec_3_T_18 + {m_pos_1_neg_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_3_T_15 = 9'(_qds_sign_spec_3_T_18 + {m_neg_0_neg_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_3_T_21 = 9'(_qds_sign_spec_3_T_18 + {m_neg_1_neg_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_2_T_1 = 9'(rem_i + {m_pos_2_neg_0_i, 2'h0});
  wire [8:0] _qds_sign_spec_2_T_5 = 9'(rem_i + {m_pos_1_neg_0_i, 2'h0});
  wire [8:0] _qds_sign_spec_2_T_9 = 9'(rem_i + {m_neg_0_neg_0_i, 2'h0});
  wire [8:0] _qds_sign_spec_2_T_13 = 9'(rem_i + {m_neg_1_neg_0_i, 2'h0});
  wire [8:0] _qds_sign_spec_1_T_18 = 9'(rem_i + sqrt_csa_val_pos_1_msbs_i);
  wire [8:0] _qds_sign_spec_1_T_3 = 9'(_qds_sign_spec_1_T_18 + {m_pos_2_pos_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_1_T_9 = 9'(_qds_sign_spec_1_T_18 + {m_pos_1_pos_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_1_T_15 = 9'(_qds_sign_spec_1_T_18 + {m_neg_0_pos_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_1_T_21 = 9'(_qds_sign_spec_1_T_18 + {m_neg_1_pos_1_i, 2'h0});
  wire [8:0] _qds_sign_spec_0_T_18 = 9'(rem_i + sqrt_csa_val_pos_2_msbs_i);
  wire [8:0] _qds_sign_spec_0_T_3 = 9'(_qds_sign_spec_0_T_18 + {m_pos_2_pos_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_0_T_9 = 9'(_qds_sign_spec_0_T_18 + {m_pos_1_pos_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_0_T_15 = 9'(_qds_sign_spec_0_T_18 + {m_neg_0_pos_2_i, 2'h0});
  wire [8:0] _qds_sign_spec_0_T_21 = 9'(_qds_sign_spec_0_T_18 + {m_neg_1_pos_2_i, 2'h0});
  wire [3:0] qds_sign =
    (prev_rt_dig_i[4]
       ? {_qds_sign_spec_4_T_3[8],
          _qds_sign_spec_4_T_9[8],
          _qds_sign_spec_4_T_15[8],
          _qds_sign_spec_4_T_21[8]}
       : 4'h0)
    | (prev_rt_dig_i[3]
         ? {_qds_sign_spec_3_T_3[8],
            _qds_sign_spec_3_T_9[8],
            _qds_sign_spec_3_T_15[8],
            _qds_sign_spec_3_T_21[8]}
         : 4'h0)
    | (prev_rt_dig_i[2]
         ? {_qds_sign_spec_2_T_1[8],
            _qds_sign_spec_2_T_5[8],
            _qds_sign_spec_2_T_9[8],
            _qds_sign_spec_2_T_13[8]}
         : 4'h0)
    | (prev_rt_dig_i[1]
         ? {_qds_sign_spec_1_T_3[8],
            _qds_sign_spec_1_T_9[8],
            _qds_sign_spec_1_T_15[8],
            _qds_sign_spec_1_T_21[8]}
         : 4'h0)
    | (prev_rt_dig_i[0]
         ? {_qds_sign_spec_0_T_3[8],
            _qds_sign_spec_0_T_9[8],
            _qds_sign_spec_0_T_15[8],
            _qds_sign_spec_0_T_21[8]}
         : 4'h0);
  assign rt_dig_o =
    {&(qds_sign[1:0]),
     qds_sign[1:0] == 2'h2,
     qds_sign[2:1] == 2'h2,
     qds_sign[3:2] == 2'h2,
     qds_sign[3:2] == 2'h0};
endmodule

