// Generated by CIRCT firtool-1.135.0
module Adder_xb_8(
  input  [15:0] io_in1,
  input  [15:0] io_in2,
  output        io_cout
);

  wire [17:0] _bits_T_2 = 18'({1'h0, io_in1, 1'h1} + {1'h0, io_in2, 1'h1});
  assign io_cout = _bits_T_2[17];
endmodule

