// Generated by CIRCT firtool-1.135.0
module ClkDiv2SRAMTemplate_43(
  input         clock,
  input         io_r_req_valid,
  input  [11:0] io_r_req_bits_setIdx,
  output        io_r_resp_data_0_dirty,
  output [1:0]  io_r_resp_data_0_state,
  output [1:0]  io_r_resp_data_0_clientStates_0,
  output        io_r_resp_data_0_prefetch,
  output        io_r_resp_data_1_dirty,
  output [1:0]  io_r_resp_data_1_state,
  output [1:0]  io_r_resp_data_1_clientStates_0,
  output        io_r_resp_data_1_prefetch,
  output        io_r_resp_data_2_dirty,
  output [1:0]  io_r_resp_data_2_state,
  output [1:0]  io_r_resp_data_2_clientStates_0,
  output        io_r_resp_data_2_prefetch,
  output        io_r_resp_data_3_dirty,
  output [1:0]  io_r_resp_data_3_state,
  output [1:0]  io_r_resp_data_3_clientStates_0,
  output        io_r_resp_data_3_prefetch,
  output        io_r_resp_data_4_dirty,
  output [1:0]  io_r_resp_data_4_state,
  output [1:0]  io_r_resp_data_4_clientStates_0,
  output        io_r_resp_data_4_prefetch,
  output        io_r_resp_data_5_dirty,
  output [1:0]  io_r_resp_data_5_state,
  output [1:0]  io_r_resp_data_5_clientStates_0,
  output        io_r_resp_data_5_prefetch,
  output        io_r_resp_data_6_dirty,
  output [1:0]  io_r_resp_data_6_state,
  output [1:0]  io_r_resp_data_6_clientStates_0,
  output        io_r_resp_data_6_prefetch,
  output        io_r_resp_data_7_dirty,
  output [1:0]  io_r_resp_data_7_state,
  output [1:0]  io_r_resp_data_7_clientStates_0,
  output        io_r_resp_data_7_prefetch,
  output        io_r_resp_data_8_dirty,
  output [1:0]  io_r_resp_data_8_state,
  output [1:0]  io_r_resp_data_8_clientStates_0,
  output        io_r_resp_data_8_prefetch,
  output        io_r_resp_data_9_dirty,
  output [1:0]  io_r_resp_data_9_state,
  output [1:0]  io_r_resp_data_9_clientStates_0,
  output        io_r_resp_data_9_prefetch,
  output        io_r_resp_data_10_dirty,
  output [1:0]  io_r_resp_data_10_state,
  output [1:0]  io_r_resp_data_10_clientStates_0,
  output        io_r_resp_data_10_prefetch,
  output        io_r_resp_data_11_dirty,
  output [1:0]  io_r_resp_data_11_state,
  output [1:0]  io_r_resp_data_11_clientStates_0,
  output        io_r_resp_data_11_prefetch,
  output        io_r_resp_data_12_dirty,
  output [1:0]  io_r_resp_data_12_state,
  output [1:0]  io_r_resp_data_12_clientStates_0,
  output        io_r_resp_data_12_prefetch,
  output        io_r_resp_data_13_dirty,
  output [1:0]  io_r_resp_data_13_state,
  output [1:0]  io_r_resp_data_13_clientStates_0,
  output        io_r_resp_data_13_prefetch,
  output        io_r_resp_data_14_dirty,
  output [1:0]  io_r_resp_data_14_state,
  output [1:0]  io_r_resp_data_14_clientStates_0,
  output        io_r_resp_data_14_prefetch,
  output        io_r_resp_data_15_dirty,
  output [1:0]  io_r_resp_data_15_state,
  output [1:0]  io_r_resp_data_15_clientStates_0,
  output        io_r_resp_data_15_prefetch,
  input         io_w_req_valid,
  input  [11:0] io_w_req_bits_setIdx,
  input         io_w_req_bits_data_0_dirty,
  input  [1:0]  io_w_req_bits_data_0_state,
  input  [1:0]  io_w_req_bits_data_0_clientStates_0,
  input         io_w_req_bits_data_0_prefetch,
  input         io_w_req_bits_data_1_dirty,
  input  [1:0]  io_w_req_bits_data_1_state,
  input  [1:0]  io_w_req_bits_data_1_clientStates_0,
  input         io_w_req_bits_data_1_prefetch,
  input         io_w_req_bits_data_2_dirty,
  input  [1:0]  io_w_req_bits_data_2_state,
  input  [1:0]  io_w_req_bits_data_2_clientStates_0,
  input         io_w_req_bits_data_2_prefetch,
  input         io_w_req_bits_data_3_dirty,
  input  [1:0]  io_w_req_bits_data_3_state,
  input  [1:0]  io_w_req_bits_data_3_clientStates_0,
  input         io_w_req_bits_data_3_prefetch,
  input         io_w_req_bits_data_4_dirty,
  input  [1:0]  io_w_req_bits_data_4_state,
  input  [1:0]  io_w_req_bits_data_4_clientStates_0,
  input         io_w_req_bits_data_4_prefetch,
  input         io_w_req_bits_data_5_dirty,
  input  [1:0]  io_w_req_bits_data_5_state,
  input  [1:0]  io_w_req_bits_data_5_clientStates_0,
  input         io_w_req_bits_data_5_prefetch,
  input         io_w_req_bits_data_6_dirty,
  input  [1:0]  io_w_req_bits_data_6_state,
  input  [1:0]  io_w_req_bits_data_6_clientStates_0,
  input         io_w_req_bits_data_6_prefetch,
  input         io_w_req_bits_data_7_dirty,
  input  [1:0]  io_w_req_bits_data_7_state,
  input  [1:0]  io_w_req_bits_data_7_clientStates_0,
  input         io_w_req_bits_data_7_prefetch,
  input         io_w_req_bits_data_8_dirty,
  input  [1:0]  io_w_req_bits_data_8_state,
  input  [1:0]  io_w_req_bits_data_8_clientStates_0,
  input         io_w_req_bits_data_8_prefetch,
  input         io_w_req_bits_data_9_dirty,
  input  [1:0]  io_w_req_bits_data_9_state,
  input  [1:0]  io_w_req_bits_data_9_clientStates_0,
  input         io_w_req_bits_data_9_prefetch,
  input         io_w_req_bits_data_10_dirty,
  input  [1:0]  io_w_req_bits_data_10_state,
  input  [1:0]  io_w_req_bits_data_10_clientStates_0,
  input         io_w_req_bits_data_10_prefetch,
  input         io_w_req_bits_data_11_dirty,
  input  [1:0]  io_w_req_bits_data_11_state,
  input  [1:0]  io_w_req_bits_data_11_clientStates_0,
  input         io_w_req_bits_data_11_prefetch,
  input         io_w_req_bits_data_12_dirty,
  input  [1:0]  io_w_req_bits_data_12_state,
  input  [1:0]  io_w_req_bits_data_12_clientStates_0,
  input         io_w_req_bits_data_12_prefetch,
  input         io_w_req_bits_data_13_dirty,
  input  [1:0]  io_w_req_bits_data_13_state,
  input  [1:0]  io_w_req_bits_data_13_clientStates_0,
  input         io_w_req_bits_data_13_prefetch,
  input         io_w_req_bits_data_14_dirty,
  input  [1:0]  io_w_req_bits_data_14_state,
  input  [1:0]  io_w_req_bits_data_14_clientStates_0,
  input         io_w_req_bits_data_14_prefetch,
  input         io_w_req_bits_data_15_dirty,
  input  [1:0]  io_w_req_bits_data_15_state,
  input  [1:0]  io_w_req_bits_data_15_clientStates_0,
  input         io_w_req_bits_data_15_prefetch,
  input  [15:0] io_w_req_bits_waymask
);

  wire        realRen;
  wire [95:0] _array_ext_RW0_rdata;
  assign realRen = io_r_req_valid & ~io_w_req_valid;
  array_4096x96 array_ext (
    .RW0_addr  (io_w_req_valid ? io_w_req_bits_setIdx : io_r_req_bits_setIdx),
    .RW0_en    (realRen | io_w_req_valid),
    .RW0_clk   (clock),
    .RW0_wmode (io_w_req_valid),
    .RW0_wdata
      ({io_w_req_bits_data_15_dirty,
        io_w_req_bits_data_15_state,
        io_w_req_bits_data_15_clientStates_0,
        io_w_req_bits_data_15_prefetch,
        io_w_req_bits_data_14_dirty,
        io_w_req_bits_data_14_state,
        io_w_req_bits_data_14_clientStates_0,
        io_w_req_bits_data_14_prefetch,
        io_w_req_bits_data_13_dirty,
        io_w_req_bits_data_13_state,
        io_w_req_bits_data_13_clientStates_0,
        io_w_req_bits_data_13_prefetch,
        io_w_req_bits_data_12_dirty,
        io_w_req_bits_data_12_state,
        io_w_req_bits_data_12_clientStates_0,
        io_w_req_bits_data_12_prefetch,
        io_w_req_bits_data_11_dirty,
        io_w_req_bits_data_11_state,
        io_w_req_bits_data_11_clientStates_0,
        io_w_req_bits_data_11_prefetch,
        io_w_req_bits_data_10_dirty,
        io_w_req_bits_data_10_state,
        io_w_req_bits_data_10_clientStates_0,
        io_w_req_bits_data_10_prefetch,
        io_w_req_bits_data_9_dirty,
        io_w_req_bits_data_9_state,
        io_w_req_bits_data_9_clientStates_0,
        io_w_req_bits_data_9_prefetch,
        io_w_req_bits_data_8_dirty,
        io_w_req_bits_data_8_state,
        io_w_req_bits_data_8_clientStates_0,
        io_w_req_bits_data_8_prefetch,
        io_w_req_bits_data_7_dirty,
        io_w_req_bits_data_7_state,
        io_w_req_bits_data_7_clientStates_0,
        io_w_req_bits_data_7_prefetch,
        io_w_req_bits_data_6_dirty,
        io_w_req_bits_data_6_state,
        io_w_req_bits_data_6_clientStates_0,
        io_w_req_bits_data_6_prefetch,
        io_w_req_bits_data_5_dirty,
        io_w_req_bits_data_5_state,
        io_w_req_bits_data_5_clientStates_0,
        io_w_req_bits_data_5_prefetch,
        io_w_req_bits_data_4_dirty,
        io_w_req_bits_data_4_state,
        io_w_req_bits_data_4_clientStates_0,
        io_w_req_bits_data_4_prefetch,
        io_w_req_bits_data_3_dirty,
        io_w_req_bits_data_3_state,
        io_w_req_bits_data_3_clientStates_0,
        io_w_req_bits_data_3_prefetch,
        io_w_req_bits_data_2_dirty,
        io_w_req_bits_data_2_state,
        io_w_req_bits_data_2_clientStates_0,
        io_w_req_bits_data_2_prefetch,
        io_w_req_bits_data_1_dirty,
        io_w_req_bits_data_1_state,
        io_w_req_bits_data_1_clientStates_0,
        io_w_req_bits_data_1_prefetch,
        io_w_req_bits_data_0_dirty,
        io_w_req_bits_data_0_state,
        io_w_req_bits_data_0_clientStates_0,
        io_w_req_bits_data_0_prefetch}),
    .RW0_rdata (_array_ext_RW0_rdata),
    .RW0_wmask (io_w_req_bits_waymask)
  );
  assign io_r_resp_data_0_dirty = _array_ext_RW0_rdata[5];
  assign io_r_resp_data_0_state = _array_ext_RW0_rdata[4:3];
  assign io_r_resp_data_0_clientStates_0 = _array_ext_RW0_rdata[2:1];
  assign io_r_resp_data_0_prefetch = _array_ext_RW0_rdata[0];
  assign io_r_resp_data_1_dirty = _array_ext_RW0_rdata[11];
  assign io_r_resp_data_1_state = _array_ext_RW0_rdata[10:9];
  assign io_r_resp_data_1_clientStates_0 = _array_ext_RW0_rdata[8:7];
  assign io_r_resp_data_1_prefetch = _array_ext_RW0_rdata[6];
  assign io_r_resp_data_2_dirty = _array_ext_RW0_rdata[17];
  assign io_r_resp_data_2_state = _array_ext_RW0_rdata[16:15];
  assign io_r_resp_data_2_clientStates_0 = _array_ext_RW0_rdata[14:13];
  assign io_r_resp_data_2_prefetch = _array_ext_RW0_rdata[12];
  assign io_r_resp_data_3_dirty = _array_ext_RW0_rdata[23];
  assign io_r_resp_data_3_state = _array_ext_RW0_rdata[22:21];
  assign io_r_resp_data_3_clientStates_0 = _array_ext_RW0_rdata[20:19];
  assign io_r_resp_data_3_prefetch = _array_ext_RW0_rdata[18];
  assign io_r_resp_data_4_dirty = _array_ext_RW0_rdata[29];
  assign io_r_resp_data_4_state = _array_ext_RW0_rdata[28:27];
  assign io_r_resp_data_4_clientStates_0 = _array_ext_RW0_rdata[26:25];
  assign io_r_resp_data_4_prefetch = _array_ext_RW0_rdata[24];
  assign io_r_resp_data_5_dirty = _array_ext_RW0_rdata[35];
  assign io_r_resp_data_5_state = _array_ext_RW0_rdata[34:33];
  assign io_r_resp_data_5_clientStates_0 = _array_ext_RW0_rdata[32:31];
  assign io_r_resp_data_5_prefetch = _array_ext_RW0_rdata[30];
  assign io_r_resp_data_6_dirty = _array_ext_RW0_rdata[41];
  assign io_r_resp_data_6_state = _array_ext_RW0_rdata[40:39];
  assign io_r_resp_data_6_clientStates_0 = _array_ext_RW0_rdata[38:37];
  assign io_r_resp_data_6_prefetch = _array_ext_RW0_rdata[36];
  assign io_r_resp_data_7_dirty = _array_ext_RW0_rdata[47];
  assign io_r_resp_data_7_state = _array_ext_RW0_rdata[46:45];
  assign io_r_resp_data_7_clientStates_0 = _array_ext_RW0_rdata[44:43];
  assign io_r_resp_data_7_prefetch = _array_ext_RW0_rdata[42];
  assign io_r_resp_data_8_dirty = _array_ext_RW0_rdata[53];
  assign io_r_resp_data_8_state = _array_ext_RW0_rdata[52:51];
  assign io_r_resp_data_8_clientStates_0 = _array_ext_RW0_rdata[50:49];
  assign io_r_resp_data_8_prefetch = _array_ext_RW0_rdata[48];
  assign io_r_resp_data_9_dirty = _array_ext_RW0_rdata[59];
  assign io_r_resp_data_9_state = _array_ext_RW0_rdata[58:57];
  assign io_r_resp_data_9_clientStates_0 = _array_ext_RW0_rdata[56:55];
  assign io_r_resp_data_9_prefetch = _array_ext_RW0_rdata[54];
  assign io_r_resp_data_10_dirty = _array_ext_RW0_rdata[65];
  assign io_r_resp_data_10_state = _array_ext_RW0_rdata[64:63];
  assign io_r_resp_data_10_clientStates_0 = _array_ext_RW0_rdata[62:61];
  assign io_r_resp_data_10_prefetch = _array_ext_RW0_rdata[60];
  assign io_r_resp_data_11_dirty = _array_ext_RW0_rdata[71];
  assign io_r_resp_data_11_state = _array_ext_RW0_rdata[70:69];
  assign io_r_resp_data_11_clientStates_0 = _array_ext_RW0_rdata[68:67];
  assign io_r_resp_data_11_prefetch = _array_ext_RW0_rdata[66];
  assign io_r_resp_data_12_dirty = _array_ext_RW0_rdata[77];
  assign io_r_resp_data_12_state = _array_ext_RW0_rdata[76:75];
  assign io_r_resp_data_12_clientStates_0 = _array_ext_RW0_rdata[74:73];
  assign io_r_resp_data_12_prefetch = _array_ext_RW0_rdata[72];
  assign io_r_resp_data_13_dirty = _array_ext_RW0_rdata[83];
  assign io_r_resp_data_13_state = _array_ext_RW0_rdata[82:81];
  assign io_r_resp_data_13_clientStates_0 = _array_ext_RW0_rdata[80:79];
  assign io_r_resp_data_13_prefetch = _array_ext_RW0_rdata[78];
  assign io_r_resp_data_14_dirty = _array_ext_RW0_rdata[89];
  assign io_r_resp_data_14_state = _array_ext_RW0_rdata[88:87];
  assign io_r_resp_data_14_clientStates_0 = _array_ext_RW0_rdata[86:85];
  assign io_r_resp_data_14_prefetch = _array_ext_RW0_rdata[84];
  assign io_r_resp_data_15_dirty = _array_ext_RW0_rdata[95];
  assign io_r_resp_data_15_state = _array_ext_RW0_rdata[94:93];
  assign io_r_resp_data_15_clientStates_0 = _array_ext_RW0_rdata[92:91];
  assign io_r_resp_data_15_prefetch = _array_ext_RW0_rdata[90];
endmodule

