// Generated by CIRCT firtool-1.135.0
module Pmaaddr14Module(
  output [63:0] rdata,
  output [63:0] regOut_ALL,
  input  [63:0] addrRData_14,
  input  [63:0] addrRegOut_14
);

  assign rdata = addrRData_14;
  assign regOut_ALL = addrRegOut_14;
endmodule

