// Generated by CIRCT firtool-1.135.0
module CSA9to2(
  input  [65:0] io_in_ppIn_0,
  input  [65:0] io_in_ppIn_1,
  input  [65:0] io_in_ppIn_2,
  input  [65:0] io_in_ppIn_3,
  input  [65:0] io_in_ppIn_4,
  input  [65:0] io_in_ppIn_5,
  input  [65:0] io_in_ppIn_6,
  input  [65:0] io_in_ppIn_7,
  input  [63:0] io_in_pp8In,
  input  [7:0]  io_in_ppCin,
  input         io_in_isMul64,
  output [79:0] io_out_ppOut_0,
  output [79:0] io_out_ppOut_1,
  output        io_out_cout80
);

  wire [37:0] _l0pp2IsMul32_T = {38{~io_in_isMul64}};
  wire [43:0] _l0pp5IsMul32_T = {44{~io_in_isMul64}};
  wire [46:0] _l0pp7IsMul32_T = {47{~io_in_isMul64}};
  wire [37:0] _l0pp2IsMul64_T = {38{io_in_isMul64}};
  wire [43:0] _l0pp5IsMul64_T = {44{io_in_isMul64}};
  wire [46:0] _l0pp7IsMul64_T = {47{io_in_isMul64}};
  wire [70:0] l0pp0 =
    {_l0pp2IsMul32_T & {35'h0, ~(io_in_ppIn_0[33]), {2{io_in_ppIn_0[33]}}}
       | _l0pp2IsMul64_T
       & {3'h0, ~(io_in_ppIn_0[65]), {2{io_in_ppIn_0[65]}}, io_in_ppIn_0[64:33]},
     io_in_ppIn_0[32:0]};
  wire [70:0] l0pp1 =
    {_l0pp2IsMul32_T & {35'h1, ~(io_in_ppIn_1[33]), io_in_ppIn_1[32:31]} | _l0pp2IsMul64_T
       & {3'h1, ~(io_in_ppIn_1[65]), io_in_ppIn_1[64:31]},
     io_in_ppIn_1[30:0],
     1'h0,
     io_in_ppCin[0]};
  wire [70:0] l0pp2 =
    {_l0pp2IsMul32_T & {33'h1, ~(io_in_ppIn_2[33]), io_in_ppIn_2[32:29]} | _l0pp2IsMul64_T
       & {1'h1, ~(io_in_ppIn_2[65]), io_in_ppIn_2[64:29]},
     io_in_ppIn_2[28:0],
     1'h0,
     io_in_ppCin[1],
     2'h0};
  wire [72:0] l0pp3 =
    {_l0pp5IsMul32_T & {37'h1, ~(io_in_ppIn_3[33]), io_in_ppIn_3[32:27]} | _l0pp5IsMul64_T
       & {5'h1, ~(io_in_ppIn_3[65]), io_in_ppIn_3[64:27]},
     io_in_ppIn_3[26:0],
     1'h0,
     io_in_ppCin[2]};
  wire [72:0] l0pp4 =
    {_l0pp5IsMul32_T & {35'h1, ~(io_in_ppIn_4[33]), io_in_ppIn_4[32:25]} | _l0pp5IsMul64_T
       & {3'h1, ~(io_in_ppIn_4[65]), io_in_ppIn_4[64:25]},
     io_in_ppIn_4[24:0],
     1'h0,
     io_in_ppCin[3],
     2'h0};
  wire [72:0] l0pp5 =
    {_l0pp5IsMul32_T & {33'h1, ~(io_in_ppIn_5[33]), io_in_ppIn_5[32:23]} | _l0pp5IsMul64_T
       & {1'h1, ~(io_in_ppIn_5[65]), io_in_ppIn_5[64:23]},
     io_in_ppIn_5[22:0],
     1'h0,
     io_in_ppCin[4],
     4'h0};
  wire [69:0] l0pp6 =
    {_l0pp7IsMul32_T & {34'h1, ~(io_in_ppIn_6[33]), io_in_ppIn_6[32:21]} | _l0pp7IsMul64_T
       & {2'h1, ~(io_in_ppIn_6[65]), io_in_ppIn_6[64:21]},
     io_in_ppIn_6[20:0],
     1'h0,
     io_in_ppCin[5]};
  wire [69:0] l0pp7 =
    {_l0pp7IsMul32_T & {32'h0, ~(io_in_ppIn_7[33]), io_in_ppIn_7[32:19]} | _l0pp7IsMul64_T
       & {~(io_in_ppIn_7[65]), io_in_ppIn_7[64:19]},
     io_in_ppIn_7[18:0],
     1'h0,
     io_in_ppCin[6],
     2'h0};
  wire [69:0] l0pp8 = {io_in_pp8In, 1'h0, io_in_ppCin[7], 4'h0};
  wire [70:0] l1ppS0 = l0pp0 ^ l0pp1 ^ l0pp2;
  wire [70:0] l1ppC0 = l0pp0 & l0pp1 | l0pp0 & l0pp2 | l0pp1 & l0pp2;
  wire [72:0] l1ppS1 = l0pp3 ^ l0pp4 ^ l0pp5;
  wire [72:0] l1ppC1 = l0pp3 & l0pp4 | l0pp3 & l0pp5 | l0pp4 & l0pp5;
  wire [69:0] l1ppS2 = l0pp6 ^ l0pp7 ^ l0pp8;
  wire [69:0] l1ppC2 = l0pp6 & l0pp7 | l0pp6 & l0pp8 | l0pp7 & l0pp8;
  wire [75:0] l2ppS0 = {9'h0, l1ppS0[70:4]} ^ {3'h0, l1ppS1} ^ {l1ppS2, 6'h0};
  wire [73:0] _GEN = {7'h0, l1ppS0[70:4]};
  wire [73:0] _GEN_0 = {1'h0, l1ppS1};
  wire [73:0] _GEN_1 = {l1ppS2[67:0], 6'h0};
  wire [73:0] l2ppC0 = _GEN & _GEN_0 | _GEN & _GEN_1 | _GEN_0 & _GEN_1;
  wire [75:0] l2ppS1 = {8'h0, l1ppC0[70:3]} ^ {2'h0, l1ppC1, 1'h0} ^ {l1ppC2[68:0], 7'h0};
  wire [73:0] _GEN_2 = {6'h0, l1ppC0[70:3]};
  wire [73:0] _GEN_3 = {l1ppC1, 1'h0};
  wire [73:0] _GEN_4 = {l1ppC2[66:0], 7'h0};
  wire [73:0] l2ppC1 = _GEN_2 & _GEN_3 | _GEN_2 & _GEN_4 | _GEN_3 & _GEN_4;
  wire [74:0] l3ppS = {1'h0, l2ppC0} ^ l2ppS1[75:1] ^ {1'h0, l2ppC1};
  wire [73:0] l3ppC = l2ppC0 & l2ppS1[74:1] | l2ppC0 & l2ppC1 | l2ppS1[74:1] & l2ppC1;
  wire [73:0] l4ppC =
    l2ppS0[75:2] & l3ppS[74:1] | l2ppS0[75:2] & l3ppC | l3ppS[74:1] & l3ppC;
  assign io_out_ppOut_0 = {l2ppS0[75:2] ^ l3ppS[74:1] ^ l3ppC, l2ppS0[1:0], l1ppS0[3:0]};
  assign io_out_ppOut_1 = {l4ppC[72:0], 1'h0, l3ppS[0], l2ppS1[0], l1ppC0[2:0], 1'h0};
  assign io_out_cout80 = l1ppC2[69] | l4ppC[73];
endmodule

