// Generated by CIRCT firtool-1.135.0
module IndirectOtherPermitModule(
  input  [11:0] io_in_csrAccess_addr,
  input  [1:0]  io_in_privState_PRVM,
  input         io_in_privState_V,
  input  [63:0] io_in_aia_miselect,
  input  [63:0] io_in_aia_siselect,
  input  [63:0] io_in_aia_vsiselect,
  output        io_out_indirectCSR_EX_II
);

  wire        isModeM_v_PrvmIsM = &io_in_privState_PRVM;
  wire        isModeM = isModeM_v_PrvmIsM;
  wire        PrvmIsS = io_in_privState_PRVM == 2'h1;
  wire        isModeHS = ~io_in_privState_V & PrvmIsS;
  wire        isModeVS = io_in_privState_V & PrvmIsS;
  wire        PrvmIsU = io_in_privState_PRVM == 2'h0;
  wire        isModeVU = io_in_privState_V & PrvmIsU;
  wire [63:0] effectiveSiregSelect =
    io_in_privState_V ? io_in_aia_vsiselect : io_in_aia_siselect;
  assign io_out_indirectCSR_EX_II =
    ~(io_in_aia_miselect > 64'h2F & io_in_aia_miselect < 64'h40
      | io_in_aia_miselect > 64'h6F & io_in_aia_miselect < 64'h100
      | (|(io_in_aia_miselect[63:6])) & io_in_aia_miselect < 64'h60)
    & io_in_csrAccess_addr > 12'h350 & io_in_csrAccess_addr < 12'h358
    & io_in_csrAccess_addr != 12'h354
    | ~(effectiveSiregSelect > 64'h2F & effectiveSiregSelect < 64'h40
        | effectiveSiregSelect > 64'h6F & effectiveSiregSelect < 64'h100
        | (|(effectiveSiregSelect[63:6])) & effectiveSiregSelect < 64'h60)
    & io_in_csrAccess_addr > 12'h150 & io_in_csrAccess_addr < 12'h158
    & io_in_csrAccess_addr != 12'h154
    | ~(io_in_aia_vsiselect > 64'h2F & io_in_aia_vsiselect < 64'h40
        | io_in_aia_vsiselect > 64'h6F & io_in_aia_vsiselect < 64'h100
        | (|(io_in_aia_vsiselect[63:6])) & io_in_aia_vsiselect < 64'h60)
    & io_in_csrAccess_addr > 12'h250 & io_in_csrAccess_addr < 12'h258
    & io_in_csrAccess_addr != 12'h254;
endmodule

