// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LsqEnqCtrl(
  input         clock,
  input         reset,
  input         io_redirect_valid,
  output        io_enq_canAccept,
  input  [1:0]  io_enq_needAlloc_0,
  input  [1:0]  io_enq_needAlloc_1,
  input  [1:0]  io_enq_needAlloc_2,
  input  [1:0]  io_enq_needAlloc_3,
  input  [1:0]  io_enq_needAlloc_4,
  input  [1:0]  io_enq_needAlloc_5,
  input  [1:0]  io_enq_needAlloc_6,
  input  [1:0]  io_enq_needAlloc_7,
  input         io_enq_req_0_valid,
  input  [35:0] io_enq_req_0_bits_fuType,
  input  [6:0]  io_enq_req_0_bits_uopIdx,
  input         io_enq_req_0_bits_robIdx_flag,
  input  [8:0]  io_enq_req_0_bits_robIdx_value,
  input  [4:0]  io_enq_req_0_bits_numLsElem,
  input         io_enq_req_1_valid,
  input  [35:0] io_enq_req_1_bits_fuType,
  input  [6:0]  io_enq_req_1_bits_uopIdx,
  input         io_enq_req_1_bits_robIdx_flag,
  input  [8:0]  io_enq_req_1_bits_robIdx_value,
  input  [4:0]  io_enq_req_1_bits_numLsElem,
  input         io_enq_req_2_valid,
  input  [35:0] io_enq_req_2_bits_fuType,
  input  [6:0]  io_enq_req_2_bits_uopIdx,
  input         io_enq_req_2_bits_robIdx_flag,
  input  [8:0]  io_enq_req_2_bits_robIdx_value,
  input  [4:0]  io_enq_req_2_bits_numLsElem,
  input         io_enq_req_3_valid,
  input  [35:0] io_enq_req_3_bits_fuType,
  input  [6:0]  io_enq_req_3_bits_uopIdx,
  input         io_enq_req_3_bits_robIdx_flag,
  input  [8:0]  io_enq_req_3_bits_robIdx_value,
  input  [4:0]  io_enq_req_3_bits_numLsElem,
  input         io_enq_req_4_valid,
  input  [35:0] io_enq_req_4_bits_fuType,
  input  [6:0]  io_enq_req_4_bits_uopIdx,
  input         io_enq_req_4_bits_robIdx_flag,
  input  [8:0]  io_enq_req_4_bits_robIdx_value,
  input  [4:0]  io_enq_req_4_bits_numLsElem,
  input         io_enq_req_5_valid,
  input  [35:0] io_enq_req_5_bits_fuType,
  input  [6:0]  io_enq_req_5_bits_uopIdx,
  input         io_enq_req_5_bits_robIdx_flag,
  input  [8:0]  io_enq_req_5_bits_robIdx_value,
  input  [4:0]  io_enq_req_5_bits_numLsElem,
  input         io_enq_req_6_valid,
  input  [35:0] io_enq_req_6_bits_fuType,
  input  [6:0]  io_enq_req_6_bits_uopIdx,
  input         io_enq_req_6_bits_robIdx_flag,
  input  [8:0]  io_enq_req_6_bits_robIdx_value,
  input  [4:0]  io_enq_req_6_bits_numLsElem,
  input         io_enq_req_7_valid,
  input  [35:0] io_enq_req_7_bits_fuType,
  input  [6:0]  io_enq_req_7_bits_uopIdx,
  input         io_enq_req_7_bits_robIdx_flag,
  input  [8:0]  io_enq_req_7_bits_robIdx_value,
  input  [4:0]  io_enq_req_7_bits_numLsElem,
  input         io_enq_iqAccept_0,
  input         io_enq_iqAccept_1,
  input         io_enq_iqAccept_2,
  input         io_enq_iqAccept_3,
  input         io_enq_iqAccept_4,
  input         io_enq_iqAccept_5,
  input         io_enq_iqAccept_6,
  input         io_enq_iqAccept_7,
  output        io_enq_resp_0_lqIdx_flag,
  output [6:0]  io_enq_resp_0_lqIdx_value,
  output        io_enq_resp_0_sqIdx_flag,
  output [5:0]  io_enq_resp_0_sqIdx_value,
  output        io_enq_resp_1_lqIdx_flag,
  output [6:0]  io_enq_resp_1_lqIdx_value,
  output        io_enq_resp_1_sqIdx_flag,
  output [5:0]  io_enq_resp_1_sqIdx_value,
  output        io_enq_resp_2_lqIdx_flag,
  output [6:0]  io_enq_resp_2_lqIdx_value,
  output        io_enq_resp_2_sqIdx_flag,
  output [5:0]  io_enq_resp_2_sqIdx_value,
  output        io_enq_resp_3_lqIdx_flag,
  output [6:0]  io_enq_resp_3_lqIdx_value,
  output        io_enq_resp_3_sqIdx_flag,
  output [5:0]  io_enq_resp_3_sqIdx_value,
  output        io_enq_resp_4_lqIdx_flag,
  output [6:0]  io_enq_resp_4_lqIdx_value,
  output        io_enq_resp_4_sqIdx_flag,
  output [5:0]  io_enq_resp_4_sqIdx_value,
  output        io_enq_resp_5_lqIdx_flag,
  output [6:0]  io_enq_resp_5_lqIdx_value,
  output        io_enq_resp_5_sqIdx_flag,
  output [5:0]  io_enq_resp_5_sqIdx_value,
  output        io_enq_resp_6_lqIdx_flag,
  output [6:0]  io_enq_resp_6_lqIdx_value,
  output        io_enq_resp_6_sqIdx_flag,
  output [5:0]  io_enq_resp_6_sqIdx_value,
  output        io_enq_resp_7_lqIdx_flag,
  output [6:0]  io_enq_resp_7_lqIdx_value,
  output        io_enq_resp_7_sqIdx_flag,
  output [5:0]  io_enq_resp_7_sqIdx_value,
  input  [3:0]  io_lcommit,
  input  [1:0]  io_scommit,
  input  [6:0]  io_lqCancelCnt,
  input  [5:0]  io_sqCancelCnt,
  output [6:0]  io_lqFreeCount,
  output [5:0]  io_sqFreeCount,
  output [1:0]  io_enqLsq_needAlloc_0,
  output [1:0]  io_enqLsq_needAlloc_1,
  output [1:0]  io_enqLsq_needAlloc_2,
  output [1:0]  io_enqLsq_needAlloc_3,
  output [1:0]  io_enqLsq_needAlloc_4,
  output [1:0]  io_enqLsq_needAlloc_5,
  output [1:0]  io_enqLsq_needAlloc_6,
  output [1:0]  io_enqLsq_needAlloc_7,
  output        io_enqLsq_req_0_valid,
  output [35:0] io_enqLsq_req_0_bits_fuType,
  output [6:0]  io_enqLsq_req_0_bits_uopIdx,
  output        io_enqLsq_req_0_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_0_bits_robIdx_value,
  output        io_enqLsq_req_0_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_0_bits_lqIdx_value,
  output        io_enqLsq_req_0_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_0_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_0_bits_numLsElem,
  output        io_enqLsq_req_1_valid,
  output [35:0] io_enqLsq_req_1_bits_fuType,
  output [6:0]  io_enqLsq_req_1_bits_uopIdx,
  output        io_enqLsq_req_1_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_1_bits_robIdx_value,
  output        io_enqLsq_req_1_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_1_bits_lqIdx_value,
  output        io_enqLsq_req_1_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_1_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_1_bits_numLsElem,
  output        io_enqLsq_req_2_valid,
  output [35:0] io_enqLsq_req_2_bits_fuType,
  output [6:0]  io_enqLsq_req_2_bits_uopIdx,
  output        io_enqLsq_req_2_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_2_bits_robIdx_value,
  output        io_enqLsq_req_2_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_2_bits_lqIdx_value,
  output        io_enqLsq_req_2_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_2_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_2_bits_numLsElem,
  output        io_enqLsq_req_3_valid,
  output [35:0] io_enqLsq_req_3_bits_fuType,
  output [6:0]  io_enqLsq_req_3_bits_uopIdx,
  output        io_enqLsq_req_3_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_3_bits_robIdx_value,
  output        io_enqLsq_req_3_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_3_bits_lqIdx_value,
  output        io_enqLsq_req_3_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_3_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_3_bits_numLsElem,
  output        io_enqLsq_req_4_valid,
  output [35:0] io_enqLsq_req_4_bits_fuType,
  output [6:0]  io_enqLsq_req_4_bits_uopIdx,
  output        io_enqLsq_req_4_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_4_bits_robIdx_value,
  output        io_enqLsq_req_4_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_4_bits_lqIdx_value,
  output        io_enqLsq_req_4_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_4_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_4_bits_numLsElem,
  output        io_enqLsq_req_5_valid,
  output [35:0] io_enqLsq_req_5_bits_fuType,
  output [6:0]  io_enqLsq_req_5_bits_uopIdx,
  output        io_enqLsq_req_5_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_5_bits_robIdx_value,
  output        io_enqLsq_req_5_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_5_bits_lqIdx_value,
  output        io_enqLsq_req_5_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_5_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_5_bits_numLsElem,
  output        io_enqLsq_req_6_valid,
  output [35:0] io_enqLsq_req_6_bits_fuType,
  output [6:0]  io_enqLsq_req_6_bits_uopIdx,
  output        io_enqLsq_req_6_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_6_bits_robIdx_value,
  output        io_enqLsq_req_6_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_6_bits_lqIdx_value,
  output        io_enqLsq_req_6_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_6_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_6_bits_numLsElem,
  output        io_enqLsq_req_7_valid,
  output [35:0] io_enqLsq_req_7_bits_fuType,
  output [6:0]  io_enqLsq_req_7_bits_uopIdx,
  output        io_enqLsq_req_7_bits_robIdx_flag,
  output [8:0]  io_enqLsq_req_7_bits_robIdx_value,
  output        io_enqLsq_req_7_bits_lqIdx_flag,
  output [6:0]  io_enqLsq_req_7_bits_lqIdx_value,
  output        io_enqLsq_req_7_bits_sqIdx_flag,
  output [5:0]  io_enqLsq_req_7_bits_sqIdx_value,
  output [4:0]  io_enqLsq_req_7_bits_numLsElem
);

  reg         lqPtr_flag;
  reg  [6:0]  lqPtr_value;
  reg         sqPtr_flag;
  reg  [5:0]  sqPtr_value;
  reg  [6:0]  lqCounter;
  reg  [5:0]  sqCounter;
  wire [4:0]  loadQueueElem_0 =
    io_enq_req_0_valid & (io_enq_req_0_bits_fuType[16] | io_enq_req_0_bits_fuType[32])
      ? io_enq_req_0_bits_numLsElem
      : 5'h0;
  wire [4:0]  storeQueueElem_0 =
    io_enq_req_0_valid & (io_enq_req_0_bits_fuType[17] | io_enq_req_0_bits_fuType[33])
      ? io_enq_req_0_bits_numLsElem
      : 5'h0;
  wire [7:0]  _GEN = {3'h0, loadQueueElem_0};
  wire [5:0]  _loadFlowPopCount_T_20 =
    6'({1'h0, loadQueueElem_0}
       + {1'h0,
          io_enq_req_1_valid
          & (io_enq_req_1_bits_fuType[16] | io_enq_req_1_bits_fuType[32])
            ? io_enq_req_1_bits_numLsElem
            : 5'h0});
  wire [7:0]  _GEN_0 = {2'h0, _loadFlowPopCount_T_20};
  wire [6:0]  _GEN_1 = {1'h0, _loadFlowPopCount_T_20};
  wire [6:0]  _GEN_2 =
    {2'h0,
     io_enq_req_2_valid & (io_enq_req_2_bits_fuType[16] | io_enq_req_2_bits_fuType[32])
       ? io_enq_req_2_bits_numLsElem
       : 5'h0};
  wire [7:0]  _GEN_3 = {1'h0, 7'(_GEN_1 + _GEN_2)};
  wire [7:0]  _GEN_4 =
    {3'h0,
     io_enq_req_3_valid & (io_enq_req_3_bits_fuType[16] | io_enq_req_3_bits_fuType[32])
       ? io_enq_req_3_bits_numLsElem
       : 5'h0};
  wire [7:0]  loadFlowPopCount_4 = 8'({1'h0, 7'(_GEN_1 + _GEN_2)} + _GEN_4);
  wire [7:0]  _GEN_5 =
    {3'h0,
     io_enq_req_4_valid & (io_enq_req_4_bits_fuType[16] | io_enq_req_4_bits_fuType[32])
       ? io_enq_req_4_bits_numLsElem
       : 5'h0};
  wire [7:0]  _loadFlowPopCount_T_8 =
    8'({1'h0, 7'(_GEN_1 + _GEN_2)} + 8'(_GEN_4 + _GEN_5));
  wire [7:0]  _GEN_6 =
    {3'h0,
     io_enq_req_5_valid & (io_enq_req_5_bits_fuType[16] | io_enq_req_5_bits_fuType[32])
       ? io_enq_req_5_bits_numLsElem
       : 5'h0};
  wire [7:0]  _loadFlowPopCount_T_13 =
    8'(8'({1'h0, 7'(_GEN_1 + _GEN_2)} + _GEN_4) + 8'(_GEN_5 + _GEN_6));
  wire [7:0]  _GEN_7 =
    {3'h0,
     io_enq_req_6_valid & (io_enq_req_6_bits_fuType[16] | io_enq_req_6_bits_fuType[32])
       ? io_enq_req_6_bits_numLsElem
       : 5'h0};
  wire [7:0]  _loadFlowPopCount_T_19 =
    8'(8'({1'h0, 7'(_GEN_1 + _GEN_2)} + _GEN_4) + 8'(_GEN_5 + 8'(_GEN_6 + _GEN_7)));
  wire [5:0]  sqOffset_2 =
    6'({1'h0, storeQueueElem_0}
       + {1'h0,
          io_enq_req_1_valid
          & (io_enq_req_1_bits_fuType[17] | io_enq_req_1_bits_fuType[33])
            ? io_enq_req_1_bits_numLsElem
            : 5'h0});
  wire [6:0]  _GEN_8 = {1'h0, sqOffset_2};
  wire [6:0]  _GEN_9 =
    {2'h0,
     io_enq_req_2_valid & (io_enq_req_2_bits_fuType[17] | io_enq_req_2_bits_fuType[33])
       ? io_enq_req_2_bits_numLsElem
       : 5'h0};
  wire [6:0]  _storeFlowPopCount_T_2 = 7'(_GEN_8 + _GEN_9);
  wire [7:0]  _GEN_10 =
    {3'h0,
     io_enq_req_3_valid & (io_enq_req_3_bits_fuType[17] | io_enq_req_3_bits_fuType[33])
       ? io_enq_req_3_bits_numLsElem
       : 5'h0};
  wire [7:0]  storeFlowPopCount_4 = 8'({1'h0, 7'(_GEN_8 + _GEN_9)} + _GEN_10);
  wire [7:0]  _GEN_11 =
    {3'h0,
     io_enq_req_4_valid & (io_enq_req_4_bits_fuType[17] | io_enq_req_4_bits_fuType[33])
       ? io_enq_req_4_bits_numLsElem
       : 5'h0};
  wire [7:0]  _storeFlowPopCount_T_8 =
    8'({1'h0, 7'(_GEN_8 + _GEN_9)} + 8'(_GEN_10 + _GEN_11));
  wire [7:0]  _GEN_12 =
    {3'h0,
     io_enq_req_5_valid & (io_enq_req_5_bits_fuType[17] | io_enq_req_5_bits_fuType[33])
       ? io_enq_req_5_bits_numLsElem
       : 5'h0};
  wire [7:0]  _storeFlowPopCount_T_13 =
    8'(8'({1'h0, 7'(_GEN_8 + _GEN_9)} + _GEN_10) + 8'(_GEN_11 + _GEN_12));
  wire [7:0]  _GEN_13 =
    {3'h0,
     io_enq_req_6_valid & (io_enq_req_6_bits_fuType[17] | io_enq_req_6_bits_fuType[33])
       ? io_enq_req_6_bits_numLsElem
       : 5'h0};
  wire [7:0]  _storeFlowPopCount_T_19 =
    8'(8'({1'h0, 7'(_GEN_8 + _GEN_9)} + _GEN_10) + 8'(_GEN_11 + 8'(_GEN_12 + _GEN_13)));
  wire [7:0]  lqAllocNumber =
    io_enq_iqAccept_0
      ? (io_enq_iqAccept_1
           ? (io_enq_iqAccept_2
                ? (io_enq_iqAccept_3
                     ? (io_enq_iqAccept_4
                          ? (io_enq_iqAccept_5
                               ? (io_enq_iqAccept_6
                                    ? (io_enq_iqAccept_7
                                         ? 8'(8'({1'h0, 7'(_GEN_1 + _GEN_2)}
                                                 + 8'(_GEN_4 + _GEN_5))
                                              + 8'(_GEN_6
                                                   + 8'(_GEN_7
                                                        + {3'h0,
                                                           io_enq_req_7_valid
                                                           & (io_enq_req_7_bits_fuType[16]
                                                              | io_enq_req_7_bits_fuType[32])
                                                             ? io_enq_req_7_bits_numLsElem
                                                             : 5'h0})))
                                         : _loadFlowPopCount_T_19)
                                    : _loadFlowPopCount_T_13)
                               : _loadFlowPopCount_T_8)
                          : loadFlowPopCount_4)
                     : _GEN_3)
                : _GEN_0)
           : _GEN)
      : 8'h0;
  wire [7:0]  sqAllocNumber =
    io_enq_iqAccept_0
      ? (io_enq_iqAccept_1
           ? (io_enq_iqAccept_2
                ? (io_enq_iqAccept_3
                     ? (io_enq_iqAccept_4
                          ? (io_enq_iqAccept_5
                               ? (io_enq_iqAccept_6
                                    ? (io_enq_iqAccept_7
                                         ? 8'(8'({1'h0, 7'(_GEN_8 + _GEN_9)}
                                                 + 8'(_GEN_10 + _GEN_11))
                                              + 8'(_GEN_12
                                                   + 8'(_GEN_13
                                                        + {3'h0,
                                                           io_enq_req_7_valid
                                                           & (io_enq_req_7_bits_fuType[17]
                                                              | io_enq_req_7_bits_fuType[33])
                                                             ? io_enq_req_7_bits_numLsElem
                                                             : 5'h0})))
                                         : _storeFlowPopCount_T_19)
                                    : _storeFlowPopCount_T_13)
                               : _storeFlowPopCount_T_8)
                          : storeFlowPopCount_4)
                     : {1'h0, _storeFlowPopCount_T_2})
                : {2'h0, sqOffset_2})
           : {3'h0, storeQueueElem_0})
      : 8'h0;
  reg         t1_redirect;
  reg         t2_redirect;
  reg         t3_update;
  reg  [6:0]  t3_lqCancelCnt_next_r;
  reg  [5:0]  t3_sqCancelCnt_next_r;
  wire [7:0]  _GEN_14 = {1'h0, lqPtr_value};
  wire [6:0]  _GEN_15 = {1'h0, sqPtr_value};
  wire [8:0]  _GEN_16 = {2'h0, lqPtr_value};
  wire [8:0]  _GEN_17 = {1'h0, lqAllocNumber};
  wire [8:0]  _GEN_18 = {1'h0, sqAllocNumber};
  reg         io_enq_canAccept_REG;
  wire [8:0]  _io_enq_resp_0_lqIdx_diff_T_4 = 9'(_GEN_16 - 9'h48);
  wire        io_enq_resp_0_lqIdx_reverse_flag =
    $signed(_io_enq_resp_0_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_0_lqIdx_flag_0 = io_enq_resp_0_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_0_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_0_lqIdx_reverse_flag ? _io_enq_resp_0_lqIdx_diff_T_4[6:0] : lqPtr_value;
  wire [7:0]  _io_enq_resp_0_sqIdx_diff_T_4 = 8'({2'h0, sqPtr_value} - 8'h38);
  wire        io_enq_resp_0_sqIdx_reverse_flag =
    $signed(_io_enq_resp_0_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_0_sqIdx_flag_0 = io_enq_resp_0_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_0_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_0_sqIdx_reverse_flag ? _io_enq_resp_0_sqIdx_diff_T_4[5:0] : sqPtr_value;
  wire [7:0]  io_enq_resp_1_lqIdx_new_value = 8'(_GEN_14 + _GEN);
  wire [8:0]  _io_enq_resp_1_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_1_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_1_lqIdx_reverse_flag =
    $signed(_io_enq_resp_1_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_1_lqIdx_flag_0 = io_enq_resp_1_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_1_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_1_lqIdx_reverse_flag
      ? _io_enq_resp_1_lqIdx_diff_T_4[6:0]
      : io_enq_resp_1_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_1_sqIdx_new_value = 7'(_GEN_15 + {2'h0, storeQueueElem_0});
  wire [7:0]  _io_enq_resp_1_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_1_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_1_sqIdx_reverse_flag =
    $signed(_io_enq_resp_1_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_1_sqIdx_flag_0 = io_enq_resp_1_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_1_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_1_sqIdx_reverse_flag
      ? _io_enq_resp_1_sqIdx_diff_T_4[5:0]
      : io_enq_resp_1_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_2_lqIdx_new_value = 8'(_GEN_14 + _GEN_0);
  wire [8:0]  _io_enq_resp_2_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_2_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_2_lqIdx_reverse_flag =
    $signed(_io_enq_resp_2_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_2_lqIdx_flag_0 = io_enq_resp_2_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_2_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_2_lqIdx_reverse_flag
      ? _io_enq_resp_2_lqIdx_diff_T_4[6:0]
      : io_enq_resp_2_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_2_sqIdx_new_value = 7'(_GEN_15 + _GEN_8);
  wire [7:0]  _io_enq_resp_2_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_2_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_2_sqIdx_reverse_flag =
    $signed(_io_enq_resp_2_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_2_sqIdx_flag_0 = io_enq_resp_2_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_2_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_2_sqIdx_reverse_flag
      ? _io_enq_resp_2_sqIdx_diff_T_4[5:0]
      : io_enq_resp_2_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_3_lqIdx_new_value = 8'(_GEN_14 + _GEN_3);
  wire [8:0]  _io_enq_resp_3_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_3_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_3_lqIdx_reverse_flag =
    $signed(_io_enq_resp_3_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_3_lqIdx_flag_0 = io_enq_resp_3_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_3_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_3_lqIdx_reverse_flag
      ? _io_enq_resp_3_lqIdx_diff_T_4[6:0]
      : io_enq_resp_3_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_3_sqIdx_new_value =
    7'(_GEN_15 + {1'h0, _storeFlowPopCount_T_2[5:0]});
  wire [7:0]  _io_enq_resp_3_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_3_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_3_sqIdx_reverse_flag =
    $signed(_io_enq_resp_3_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_3_sqIdx_flag_0 = io_enq_resp_3_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_3_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_3_sqIdx_reverse_flag
      ? _io_enq_resp_3_sqIdx_diff_T_4[5:0]
      : io_enq_resp_3_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_4_lqIdx_new_value =
    8'(_GEN_14 + {1'h0, loadFlowPopCount_4[6:0]});
  wire [8:0]  _io_enq_resp_4_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_4_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_4_lqIdx_reverse_flag =
    $signed(_io_enq_resp_4_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_4_lqIdx_flag_0 = io_enq_resp_4_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_4_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_4_lqIdx_reverse_flag
      ? _io_enq_resp_4_lqIdx_diff_T_4[6:0]
      : io_enq_resp_4_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_4_sqIdx_new_value =
    7'(_GEN_15 + {1'h0, storeFlowPopCount_4[5:0]});
  wire [7:0]  _io_enq_resp_4_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_4_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_4_sqIdx_reverse_flag =
    $signed(_io_enq_resp_4_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_4_sqIdx_flag_0 = io_enq_resp_4_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_4_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_4_sqIdx_reverse_flag
      ? _io_enq_resp_4_sqIdx_diff_T_4[5:0]
      : io_enq_resp_4_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_5_lqIdx_new_value =
    8'(_GEN_14 + {1'h0, _loadFlowPopCount_T_8[6:0]});
  wire [8:0]  _io_enq_resp_5_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_5_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_5_lqIdx_reverse_flag =
    $signed(_io_enq_resp_5_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_5_lqIdx_flag_0 = io_enq_resp_5_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_5_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_5_lqIdx_reverse_flag
      ? _io_enq_resp_5_lqIdx_diff_T_4[6:0]
      : io_enq_resp_5_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_5_sqIdx_new_value =
    7'(_GEN_15 + {1'h0, _storeFlowPopCount_T_8[5:0]});
  wire [7:0]  _io_enq_resp_5_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_5_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_5_sqIdx_reverse_flag =
    $signed(_io_enq_resp_5_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_5_sqIdx_flag_0 = io_enq_resp_5_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_5_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_5_sqIdx_reverse_flag
      ? _io_enq_resp_5_sqIdx_diff_T_4[5:0]
      : io_enq_resp_5_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_6_lqIdx_new_value =
    8'(_GEN_14 + {1'h0, _loadFlowPopCount_T_13[6:0]});
  wire [8:0]  _io_enq_resp_6_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_6_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_6_lqIdx_reverse_flag =
    $signed(_io_enq_resp_6_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_6_lqIdx_flag_0 = io_enq_resp_6_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_6_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_6_lqIdx_reverse_flag
      ? _io_enq_resp_6_lqIdx_diff_T_4[6:0]
      : io_enq_resp_6_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_6_sqIdx_new_value =
    7'(_GEN_15 + {1'h0, _storeFlowPopCount_T_13[5:0]});
  wire [7:0]  _io_enq_resp_6_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_6_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_6_sqIdx_reverse_flag =
    $signed(_io_enq_resp_6_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_6_sqIdx_flag_0 = io_enq_resp_6_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_6_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_6_sqIdx_reverse_flag
      ? _io_enq_resp_6_sqIdx_diff_T_4[5:0]
      : io_enq_resp_6_sqIdx_new_value[5:0];
  wire [7:0]  io_enq_resp_7_lqIdx_new_value =
    8'(_GEN_14 + {1'h0, _loadFlowPopCount_T_19[6:0]});
  wire [8:0]  _io_enq_resp_7_lqIdx_diff_T_4 =
    9'({1'h0, io_enq_resp_7_lqIdx_new_value} - 9'h48);
  wire        io_enq_resp_7_lqIdx_reverse_flag =
    $signed(_io_enq_resp_7_lqIdx_diff_T_4) > -9'sh1;
  wire        io_enq_resp_7_lqIdx_flag_0 = io_enq_resp_7_lqIdx_reverse_flag ^ lqPtr_flag;
  wire [6:0]  _io_enq_resp_7_lqIdx_new_ptr_value_T_1 =
    io_enq_resp_7_lqIdx_reverse_flag
      ? _io_enq_resp_7_lqIdx_diff_T_4[6:0]
      : io_enq_resp_7_lqIdx_new_value[6:0];
  wire [6:0]  io_enq_resp_7_sqIdx_new_value =
    7'(_GEN_15 + {1'h0, _storeFlowPopCount_T_19[5:0]});
  wire [7:0]  _io_enq_resp_7_sqIdx_diff_T_4 =
    8'({1'h0, io_enq_resp_7_sqIdx_new_value} - 8'h38);
  wire        io_enq_resp_7_sqIdx_reverse_flag =
    $signed(_io_enq_resp_7_sqIdx_diff_T_4) > -8'sh1;
  wire        io_enq_resp_7_sqIdx_flag_0 = io_enq_resp_7_sqIdx_reverse_flag ^ sqPtr_flag;
  wire [5:0]  _io_enq_resp_7_sqIdx_new_ptr_value_T_1 =
    io_enq_resp_7_sqIdx_reverse_flag
      ? _io_enq_resp_7_sqIdx_diff_T_4[5:0]
      : io_enq_resp_7_sqIdx_new_value[5:0];
  reg  [1:0]  REG_0;
  reg  [1:0]  REG_1;
  reg  [1:0]  REG_2;
  reg  [1:0]  REG_3;
  reg  [1:0]  REG_4;
  reg  [1:0]  REG_5;
  reg  [1:0]  REG_6;
  reg  [1:0]  REG_7;
  reg         io_enqLsq_req_0_valid_REG;
  reg  [35:0] io_enqLsq_req_0_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_0_bits_r_uopIdx;
  reg         io_enqLsq_req_0_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_0_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_0_bits_r_numLsElem;
  reg         io_enqLsq_req_0_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_0_bits_lqIdx_r_value;
  reg         io_enqLsq_req_0_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_0_bits_sqIdx_r_value;
  reg         io_enqLsq_req_1_valid_REG;
  reg  [35:0] io_enqLsq_req_1_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_1_bits_r_uopIdx;
  reg         io_enqLsq_req_1_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_1_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_1_bits_r_numLsElem;
  reg         io_enqLsq_req_1_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_1_bits_lqIdx_r_value;
  reg         io_enqLsq_req_1_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_1_bits_sqIdx_r_value;
  reg         io_enqLsq_req_2_valid_REG;
  reg  [35:0] io_enqLsq_req_2_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_2_bits_r_uopIdx;
  reg         io_enqLsq_req_2_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_2_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_2_bits_r_numLsElem;
  reg         io_enqLsq_req_2_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_2_bits_lqIdx_r_value;
  reg         io_enqLsq_req_2_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_2_bits_sqIdx_r_value;
  reg         io_enqLsq_req_3_valid_REG;
  reg  [35:0] io_enqLsq_req_3_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_3_bits_r_uopIdx;
  reg         io_enqLsq_req_3_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_3_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_3_bits_r_numLsElem;
  reg         io_enqLsq_req_3_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_3_bits_lqIdx_r_value;
  reg         io_enqLsq_req_3_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_3_bits_sqIdx_r_value;
  reg         io_enqLsq_req_4_valid_REG;
  reg  [35:0] io_enqLsq_req_4_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_4_bits_r_uopIdx;
  reg         io_enqLsq_req_4_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_4_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_4_bits_r_numLsElem;
  reg         io_enqLsq_req_4_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_4_bits_lqIdx_r_value;
  reg         io_enqLsq_req_4_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_4_bits_sqIdx_r_value;
  reg         io_enqLsq_req_5_valid_REG;
  reg  [35:0] io_enqLsq_req_5_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_5_bits_r_uopIdx;
  reg         io_enqLsq_req_5_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_5_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_5_bits_r_numLsElem;
  reg         io_enqLsq_req_5_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_5_bits_lqIdx_r_value;
  reg         io_enqLsq_req_5_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_5_bits_sqIdx_r_value;
  reg         io_enqLsq_req_6_valid_REG;
  reg  [35:0] io_enqLsq_req_6_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_6_bits_r_uopIdx;
  reg         io_enqLsq_req_6_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_6_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_6_bits_r_numLsElem;
  reg         io_enqLsq_req_6_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_6_bits_lqIdx_r_value;
  reg         io_enqLsq_req_6_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_6_bits_sqIdx_r_value;
  reg         io_enqLsq_req_7_valid_REG;
  reg  [35:0] io_enqLsq_req_7_bits_r_fuType;
  reg  [6:0]  io_enqLsq_req_7_bits_r_uopIdx;
  reg         io_enqLsq_req_7_bits_r_robIdx_flag;
  reg  [8:0]  io_enqLsq_req_7_bits_r_robIdx_value;
  reg  [4:0]  io_enqLsq_req_7_bits_r_numLsElem;
  reg         io_enqLsq_req_7_bits_lqIdx_r_flag;
  reg  [6:0]  io_enqLsq_req_7_bits_lqIdx_r_value;
  reg         io_enqLsq_req_7_bits_sqIdx_r_flag;
  reg  [5:0]  io_enqLsq_req_7_bits_sqIdx_r_value;
  wire [7:0]  lqPtr_flipped_new_ptr_new_value =
    8'(_GEN_14 + {1'h0, 7'(7'h48 - t3_lqCancelCnt_next_r)});
  wire [8:0]  _lqPtr_flipped_new_ptr_diff_T_4 =
    9'({1'h0, lqPtr_flipped_new_ptr_new_value} - 9'h48);
  wire        lqPtr_flipped_new_ptr_reverse_flag =
    $signed(_lqPtr_flipped_new_ptr_diff_T_4) > -9'sh1;
  wire [6:0]  _GEN_19 = {3'h0, io_lcommit};
  wire [6:0]  sqPtr_flipped_new_ptr_new_value =
    7'(_GEN_15 + {1'h0, 6'(6'h38 - t3_sqCancelCnt_next_r)});
  wire [7:0]  _sqPtr_flipped_new_ptr_diff_T_4 =
    8'({1'h0, sqPtr_flipped_new_ptr_new_value} - 8'h38);
  wire        sqPtr_flipped_new_ptr_reverse_flag =
    $signed(_sqPtr_flipped_new_ptr_diff_T_4) > -8'sh1;
  wire [5:0]  _GEN_20 = {4'h0, io_scommit};
  wire        _GEN_21 = ~io_redirect_valid & io_enq_canAccept_REG;
  wire [8:0]  lqPtr_new_value = 9'(_GEN_16 + _GEN_17);
  wire [9:0]  _lqPtr_diff_T_4 = 10'({1'h0, lqPtr_new_value} - 10'h48);
  wire        lqPtr_reverse_flag = $signed(_lqPtr_diff_T_4) > -10'sh1;
  wire [8:0]  sqPtr_new_value = 9'({3'h0, sqPtr_value} + _GEN_18);
  wire [9:0]  _sqPtr_diff_T_4 = 10'({1'h0, sqPtr_new_value} - 10'h38);
  wire        sqPtr_reverse_flag = $signed(_sqPtr_diff_T_4) > -10'sh1;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      lqPtr_flag <= 1'h0;
      lqPtr_value <= 7'h0;
      sqPtr_flag <= 1'h0;
      sqPtr_value <= 6'h0;
      lqCounter <= 7'h48;
      sqCounter <= 6'h38;
      t3_lqCancelCnt_next_r <= 7'h0;
      t3_sqCancelCnt_next_r <= 6'h0;
    end
    else begin
      lqPtr_flag <=
        t3_update
          ? lqPtr_flipped_new_ptr_reverse_flag ^ ~lqPtr_flag
          : _GEN_21 & lqPtr_reverse_flag ^ lqPtr_flag;
      if (t3_update) begin
        lqPtr_value <=
          lqPtr_flipped_new_ptr_reverse_flag
            ? _lqPtr_flipped_new_ptr_diff_T_4[6:0]
            : lqPtr_flipped_new_ptr_new_value[6:0];
        sqPtr_value <=
          sqPtr_flipped_new_ptr_reverse_flag
            ? _sqPtr_flipped_new_ptr_diff_T_4[5:0]
            : sqPtr_flipped_new_ptr_new_value[5:0];
      end
      else if (_GEN_21) begin
        lqPtr_value <= lqPtr_reverse_flag ? _lqPtr_diff_T_4[6:0] : lqPtr_new_value[6:0];
        sqPtr_value <= sqPtr_reverse_flag ? _sqPtr_diff_T_4[5:0] : sqPtr_new_value[5:0];
      end
      sqPtr_flag <=
        t3_update
          ? sqPtr_flipped_new_ptr_reverse_flag ^ ~sqPtr_flag
          : _GEN_21 & sqPtr_reverse_flag ^ sqPtr_flag;
      lqCounter <=
        t3_update
          ? 7'(lqCounter + 7'(_GEN_19 + t3_lqCancelCnt_next_r))
          : _GEN_21
              ? 7'(7'(lqCounter + _GEN_19) - lqAllocNumber[6:0])
              : 7'(lqCounter + _GEN_19);
      sqCounter <=
        t3_update
          ? 6'(sqCounter + 6'(_GEN_20 + t3_sqCancelCnt_next_r))
          : _GEN_21
              ? 6'(6'(sqCounter + _GEN_20) - sqAllocNumber[5:0])
              : 6'(sqCounter + _GEN_20);
      if (io_lqCancelCnt != t3_lqCancelCnt_next_r)
        t3_lqCancelCnt_next_r <= io_lqCancelCnt;
      if (io_sqCancelCnt != t3_sqCancelCnt_next_r)
        t3_sqCancelCnt_next_r <= io_sqCancelCnt;
    end
  end // always @(posedge, posedge)
  wire        t2_update =
    t2_redirect
    & {|io_enq_needAlloc_7,
       |io_enq_needAlloc_6,
       |io_enq_needAlloc_5,
       |io_enq_needAlloc_4,
       |io_enq_needAlloc_3,
       |io_enq_needAlloc_2,
       |io_enq_needAlloc_1,
       |io_enq_needAlloc_0} == 8'h0;
  wire        do_enq = io_enq_req_0_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_1 = io_enq_req_1_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_2 = io_enq_req_2_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_3 = io_enq_req_3_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_4 = io_enq_req_4_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_5 = io_enq_req_5_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_6 = io_enq_req_6_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  wire        do_enq_7 = io_enq_req_7_valid & ~io_redirect_valid & io_enq_canAccept_REG;
  always @(posedge clock) begin
    t1_redirect <= io_redirect_valid;
    t2_redirect <= t1_redirect;
    t3_update <= t2_update;
    io_enq_canAccept_REG <=
      {2'h0, lqCounter} >= 9'(_GEN_17 + 9'h6) & {3'h0, sqCounter} >= 9'(_GEN_18 + 9'h4)
      & ~t2_update;
    REG_0 <= io_enq_needAlloc_0;
    REG_1 <= io_enq_needAlloc_1;
    REG_2 <= io_enq_needAlloc_2;
    REG_3 <= io_enq_needAlloc_3;
    REG_4 <= io_enq_needAlloc_4;
    REG_5 <= io_enq_needAlloc_5;
    REG_6 <= io_enq_needAlloc_6;
    REG_7 <= io_enq_needAlloc_7;
    io_enqLsq_req_0_valid_REG <= do_enq;
    if (do_enq) begin
      io_enqLsq_req_0_bits_r_fuType <= io_enq_req_0_bits_fuType;
      io_enqLsq_req_0_bits_r_uopIdx <= io_enq_req_0_bits_uopIdx;
      io_enqLsq_req_0_bits_r_robIdx_flag <= io_enq_req_0_bits_robIdx_flag;
      io_enqLsq_req_0_bits_r_robIdx_value <= io_enq_req_0_bits_robIdx_value;
      io_enqLsq_req_0_bits_r_numLsElem <= io_enq_req_0_bits_numLsElem;
      io_enqLsq_req_0_bits_lqIdx_r_flag <= io_enq_resp_0_lqIdx_flag_0;
      io_enqLsq_req_0_bits_lqIdx_r_value <= _io_enq_resp_0_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_0_bits_sqIdx_r_flag <= io_enq_resp_0_sqIdx_flag_0;
      io_enqLsq_req_0_bits_sqIdx_r_value <= _io_enq_resp_0_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_1_valid_REG <= do_enq_1;
    if (do_enq_1) begin
      io_enqLsq_req_1_bits_r_fuType <= io_enq_req_1_bits_fuType;
      io_enqLsq_req_1_bits_r_uopIdx <= io_enq_req_1_bits_uopIdx;
      io_enqLsq_req_1_bits_r_robIdx_flag <= io_enq_req_1_bits_robIdx_flag;
      io_enqLsq_req_1_bits_r_robIdx_value <= io_enq_req_1_bits_robIdx_value;
      io_enqLsq_req_1_bits_r_numLsElem <= io_enq_req_1_bits_numLsElem;
      io_enqLsq_req_1_bits_lqIdx_r_flag <= io_enq_resp_1_lqIdx_flag_0;
      io_enqLsq_req_1_bits_lqIdx_r_value <= _io_enq_resp_1_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_1_bits_sqIdx_r_flag <= io_enq_resp_1_sqIdx_flag_0;
      io_enqLsq_req_1_bits_sqIdx_r_value <= _io_enq_resp_1_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_2_valid_REG <= do_enq_2;
    if (do_enq_2) begin
      io_enqLsq_req_2_bits_r_fuType <= io_enq_req_2_bits_fuType;
      io_enqLsq_req_2_bits_r_uopIdx <= io_enq_req_2_bits_uopIdx;
      io_enqLsq_req_2_bits_r_robIdx_flag <= io_enq_req_2_bits_robIdx_flag;
      io_enqLsq_req_2_bits_r_robIdx_value <= io_enq_req_2_bits_robIdx_value;
      io_enqLsq_req_2_bits_r_numLsElem <= io_enq_req_2_bits_numLsElem;
      io_enqLsq_req_2_bits_lqIdx_r_flag <= io_enq_resp_2_lqIdx_flag_0;
      io_enqLsq_req_2_bits_lqIdx_r_value <= _io_enq_resp_2_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_2_bits_sqIdx_r_flag <= io_enq_resp_2_sqIdx_flag_0;
      io_enqLsq_req_2_bits_sqIdx_r_value <= _io_enq_resp_2_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_3_valid_REG <= do_enq_3;
    if (do_enq_3) begin
      io_enqLsq_req_3_bits_r_fuType <= io_enq_req_3_bits_fuType;
      io_enqLsq_req_3_bits_r_uopIdx <= io_enq_req_3_bits_uopIdx;
      io_enqLsq_req_3_bits_r_robIdx_flag <= io_enq_req_3_bits_robIdx_flag;
      io_enqLsq_req_3_bits_r_robIdx_value <= io_enq_req_3_bits_robIdx_value;
      io_enqLsq_req_3_bits_r_numLsElem <= io_enq_req_3_bits_numLsElem;
      io_enqLsq_req_3_bits_lqIdx_r_flag <= io_enq_resp_3_lqIdx_flag_0;
      io_enqLsq_req_3_bits_lqIdx_r_value <= _io_enq_resp_3_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_3_bits_sqIdx_r_flag <= io_enq_resp_3_sqIdx_flag_0;
      io_enqLsq_req_3_bits_sqIdx_r_value <= _io_enq_resp_3_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_4_valid_REG <= do_enq_4;
    if (do_enq_4) begin
      io_enqLsq_req_4_bits_r_fuType <= io_enq_req_4_bits_fuType;
      io_enqLsq_req_4_bits_r_uopIdx <= io_enq_req_4_bits_uopIdx;
      io_enqLsq_req_4_bits_r_robIdx_flag <= io_enq_req_4_bits_robIdx_flag;
      io_enqLsq_req_4_bits_r_robIdx_value <= io_enq_req_4_bits_robIdx_value;
      io_enqLsq_req_4_bits_r_numLsElem <= io_enq_req_4_bits_numLsElem;
      io_enqLsq_req_4_bits_lqIdx_r_flag <= io_enq_resp_4_lqIdx_flag_0;
      io_enqLsq_req_4_bits_lqIdx_r_value <= _io_enq_resp_4_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_4_bits_sqIdx_r_flag <= io_enq_resp_4_sqIdx_flag_0;
      io_enqLsq_req_4_bits_sqIdx_r_value <= _io_enq_resp_4_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_5_valid_REG <= do_enq_5;
    if (do_enq_5) begin
      io_enqLsq_req_5_bits_r_fuType <= io_enq_req_5_bits_fuType;
      io_enqLsq_req_5_bits_r_uopIdx <= io_enq_req_5_bits_uopIdx;
      io_enqLsq_req_5_bits_r_robIdx_flag <= io_enq_req_5_bits_robIdx_flag;
      io_enqLsq_req_5_bits_r_robIdx_value <= io_enq_req_5_bits_robIdx_value;
      io_enqLsq_req_5_bits_r_numLsElem <= io_enq_req_5_bits_numLsElem;
      io_enqLsq_req_5_bits_lqIdx_r_flag <= io_enq_resp_5_lqIdx_flag_0;
      io_enqLsq_req_5_bits_lqIdx_r_value <= _io_enq_resp_5_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_5_bits_sqIdx_r_flag <= io_enq_resp_5_sqIdx_flag_0;
      io_enqLsq_req_5_bits_sqIdx_r_value <= _io_enq_resp_5_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_6_valid_REG <= do_enq_6;
    if (do_enq_6) begin
      io_enqLsq_req_6_bits_r_fuType <= io_enq_req_6_bits_fuType;
      io_enqLsq_req_6_bits_r_uopIdx <= io_enq_req_6_bits_uopIdx;
      io_enqLsq_req_6_bits_r_robIdx_flag <= io_enq_req_6_bits_robIdx_flag;
      io_enqLsq_req_6_bits_r_robIdx_value <= io_enq_req_6_bits_robIdx_value;
      io_enqLsq_req_6_bits_r_numLsElem <= io_enq_req_6_bits_numLsElem;
      io_enqLsq_req_6_bits_lqIdx_r_flag <= io_enq_resp_6_lqIdx_flag_0;
      io_enqLsq_req_6_bits_lqIdx_r_value <= _io_enq_resp_6_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_6_bits_sqIdx_r_flag <= io_enq_resp_6_sqIdx_flag_0;
      io_enqLsq_req_6_bits_sqIdx_r_value <= _io_enq_resp_6_sqIdx_new_ptr_value_T_1;
    end
    io_enqLsq_req_7_valid_REG <= do_enq_7;
    if (do_enq_7) begin
      io_enqLsq_req_7_bits_r_fuType <= io_enq_req_7_bits_fuType;
      io_enqLsq_req_7_bits_r_uopIdx <= io_enq_req_7_bits_uopIdx;
      io_enqLsq_req_7_bits_r_robIdx_flag <= io_enq_req_7_bits_robIdx_flag;
      io_enqLsq_req_7_bits_r_robIdx_value <= io_enq_req_7_bits_robIdx_value;
      io_enqLsq_req_7_bits_r_numLsElem <= io_enq_req_7_bits_numLsElem;
      io_enqLsq_req_7_bits_lqIdx_r_flag <= io_enq_resp_7_lqIdx_flag_0;
      io_enqLsq_req_7_bits_lqIdx_r_value <= _io_enq_resp_7_lqIdx_new_ptr_value_T_1;
      io_enqLsq_req_7_bits_sqIdx_r_flag <= io_enq_resp_7_sqIdx_flag_0;
      io_enqLsq_req_7_bits_sqIdx_r_value <= _io_enq_resp_7_sqIdx_new_ptr_value_T_1;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:332];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [8:0] i = 9'h0; i < 9'h14D; i += 9'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        lqPtr_flag = _RANDOM[9'h0][0];
        lqPtr_value = _RANDOM[9'h0][7:1];
        sqPtr_flag = _RANDOM[9'h0][8];
        sqPtr_value = _RANDOM[9'h0][14:9];
        lqCounter = _RANDOM[9'h0][21:15];
        sqCounter = _RANDOM[9'h0][27:22];
        t1_redirect = _RANDOM[9'h0][29];
        t2_redirect = _RANDOM[9'h0][30];
        t3_update = _RANDOM[9'h0][31];
        t3_lqCancelCnt_next_r = _RANDOM[9'h1][6:0];
        t3_sqCancelCnt_next_r = _RANDOM[9'h1][12:7];
        io_enq_canAccept_REG = _RANDOM[9'h1][13];
        REG_0 = _RANDOM[9'h1][15:14];
        REG_1 = _RANDOM[9'h1][17:16];
        REG_2 = _RANDOM[9'h1][19:18];
        REG_3 = _RANDOM[9'h1][21:20];
        REG_4 = _RANDOM[9'h1][23:22];
        REG_5 = _RANDOM[9'h1][25:24];
        REG_6 = _RANDOM[9'h1][27:26];
        REG_7 = _RANDOM[9'h1][29:28];
        io_enqLsq_req_0_valid_REG = _RANDOM[9'h2][6];
        io_enqLsq_req_0_bits_r_fuType = {_RANDOM[9'h7][31:13], _RANDOM[9'h8][16:0]};
        io_enqLsq_req_0_bits_r_uopIdx = _RANDOM[9'h11][17:11];
        io_enqLsq_req_0_bits_r_robIdx_flag = _RANDOM[9'h14][30];
        io_enqLsq_req_0_bits_r_robIdx_value = {_RANDOM[9'h14][31], _RANDOM[9'h15][7:0]};
        io_enqLsq_req_0_bits_r_numLsElem = {_RANDOM[9'h2A][31:28], _RANDOM[9'h2B][0]};
        io_enqLsq_req_0_bits_lqIdx_r_flag = _RANDOM[9'h2B][1];
        io_enqLsq_req_0_bits_lqIdx_r_value = _RANDOM[9'h2B][8:2];
        io_enqLsq_req_0_bits_sqIdx_r_flag = _RANDOM[9'h2B][9];
        io_enqLsq_req_0_bits_sqIdx_r_value = _RANDOM[9'h2B][15:10];
        io_enqLsq_req_1_valid_REG = _RANDOM[9'h2B][16];
        io_enqLsq_req_1_bits_r_fuType = {_RANDOM[9'h30][31:23], _RANDOM[9'h31][26:0]};
        io_enqLsq_req_1_bits_r_uopIdx = _RANDOM[9'h3A][27:21];
        io_enqLsq_req_1_bits_r_robIdx_flag = _RANDOM[9'h3E][8];
        io_enqLsq_req_1_bits_r_robIdx_value = _RANDOM[9'h3E][17:9];
        io_enqLsq_req_1_bits_r_numLsElem = _RANDOM[9'h54][10:6];
        io_enqLsq_req_1_bits_lqIdx_r_flag = _RANDOM[9'h54][11];
        io_enqLsq_req_1_bits_lqIdx_r_value = _RANDOM[9'h54][18:12];
        io_enqLsq_req_1_bits_sqIdx_r_flag = _RANDOM[9'h54][19];
        io_enqLsq_req_1_bits_sqIdx_r_value = _RANDOM[9'h54][25:20];
        io_enqLsq_req_2_valid_REG = _RANDOM[9'h54][26];
        io_enqLsq_req_2_bits_r_fuType = {_RANDOM[9'h5A][31:1], _RANDOM[9'h5B][4:0]};
        io_enqLsq_req_2_bits_r_uopIdx = {_RANDOM[9'h63][31], _RANDOM[9'h64][5:0]};
        io_enqLsq_req_2_bits_r_robIdx_flag = _RANDOM[9'h67][18];
        io_enqLsq_req_2_bits_r_robIdx_value = _RANDOM[9'h67][27:19];
        io_enqLsq_req_2_bits_r_numLsElem = _RANDOM[9'h7D][20:16];
        io_enqLsq_req_2_bits_lqIdx_r_flag = _RANDOM[9'h7D][21];
        io_enqLsq_req_2_bits_lqIdx_r_value = _RANDOM[9'h7D][28:22];
        io_enqLsq_req_2_bits_sqIdx_r_flag = _RANDOM[9'h7D][29];
        io_enqLsq_req_2_bits_sqIdx_r_value = {_RANDOM[9'h7D][31:30], _RANDOM[9'h7E][3:0]};
        io_enqLsq_req_3_valid_REG = _RANDOM[9'h7E][4];
        io_enqLsq_req_3_bits_r_fuType = {_RANDOM[9'h83][31:11], _RANDOM[9'h84][14:0]};
        io_enqLsq_req_3_bits_r_uopIdx = _RANDOM[9'h8D][15:9];
        io_enqLsq_req_3_bits_r_robIdx_flag = _RANDOM[9'h90][28];
        io_enqLsq_req_3_bits_r_robIdx_value =
          {_RANDOM[9'h90][31:29], _RANDOM[9'h91][5:0]};
        io_enqLsq_req_3_bits_r_numLsElem = _RANDOM[9'hA6][30:26];
        io_enqLsq_req_3_bits_lqIdx_r_flag = _RANDOM[9'hA6][31];
        io_enqLsq_req_3_bits_lqIdx_r_value = _RANDOM[9'hA7][6:0];
        io_enqLsq_req_3_bits_sqIdx_r_flag = _RANDOM[9'hA7][7];
        io_enqLsq_req_3_bits_sqIdx_r_value = _RANDOM[9'hA7][13:8];
        io_enqLsq_req_4_valid_REG = _RANDOM[9'hA7][14];
        io_enqLsq_req_4_bits_r_fuType = {_RANDOM[9'hAC][31:21], _RANDOM[9'hAD][24:0]};
        io_enqLsq_req_4_bits_r_uopIdx = _RANDOM[9'hB6][25:19];
        io_enqLsq_req_4_bits_r_robIdx_flag = _RANDOM[9'hBA][6];
        io_enqLsq_req_4_bits_r_robIdx_value = _RANDOM[9'hBA][15:7];
        io_enqLsq_req_4_bits_r_numLsElem = _RANDOM[9'hD0][8:4];
        io_enqLsq_req_4_bits_lqIdx_r_flag = _RANDOM[9'hD0][9];
        io_enqLsq_req_4_bits_lqIdx_r_value = _RANDOM[9'hD0][16:10];
        io_enqLsq_req_4_bits_sqIdx_r_flag = _RANDOM[9'hD0][17];
        io_enqLsq_req_4_bits_sqIdx_r_value = _RANDOM[9'hD0][23:18];
        io_enqLsq_req_5_valid_REG = _RANDOM[9'hD0][24];
        io_enqLsq_req_5_bits_r_fuType =
          {_RANDOM[9'hD5][31], _RANDOM[9'hD6], _RANDOM[9'hD7][2:0]};
        io_enqLsq_req_5_bits_r_uopIdx = {_RANDOM[9'hDF][31:29], _RANDOM[9'hE0][3:0]};
        io_enqLsq_req_5_bits_r_robIdx_flag = _RANDOM[9'hE3][16];
        io_enqLsq_req_5_bits_r_robIdx_value = _RANDOM[9'hE3][25:17];
        io_enqLsq_req_5_bits_r_numLsElem = _RANDOM[9'hF9][18:14];
        io_enqLsq_req_5_bits_lqIdx_r_flag = _RANDOM[9'hF9][19];
        io_enqLsq_req_5_bits_lqIdx_r_value = _RANDOM[9'hF9][26:20];
        io_enqLsq_req_5_bits_sqIdx_r_flag = _RANDOM[9'hF9][27];
        io_enqLsq_req_5_bits_sqIdx_r_value = {_RANDOM[9'hF9][31:28], _RANDOM[9'hFA][1:0]};
        io_enqLsq_req_6_valid_REG = _RANDOM[9'hFA][2];
        io_enqLsq_req_6_bits_r_fuType = {_RANDOM[9'hFF][31:9], _RANDOM[9'h100][12:0]};
        io_enqLsq_req_6_bits_r_uopIdx = _RANDOM[9'h109][13:7];
        io_enqLsq_req_6_bits_r_robIdx_flag = _RANDOM[9'h10C][26];
        io_enqLsq_req_6_bits_r_robIdx_value =
          {_RANDOM[9'h10C][31:27], _RANDOM[9'h10D][3:0]};
        io_enqLsq_req_6_bits_r_numLsElem = _RANDOM[9'h122][28:24];
        io_enqLsq_req_6_bits_lqIdx_r_flag = _RANDOM[9'h122][29];
        io_enqLsq_req_6_bits_lqIdx_r_value =
          {_RANDOM[9'h122][31:30], _RANDOM[9'h123][4:0]};
        io_enqLsq_req_6_bits_sqIdx_r_flag = _RANDOM[9'h123][5];
        io_enqLsq_req_6_bits_sqIdx_r_value = _RANDOM[9'h123][11:6];
        io_enqLsq_req_7_valid_REG = _RANDOM[9'h123][12];
        io_enqLsq_req_7_bits_r_fuType = {_RANDOM[9'h128][31:19], _RANDOM[9'h129][22:0]};
        io_enqLsq_req_7_bits_r_uopIdx = _RANDOM[9'h132][23:17];
        io_enqLsq_req_7_bits_r_robIdx_flag = _RANDOM[9'h136][4];
        io_enqLsq_req_7_bits_r_robIdx_value = _RANDOM[9'h136][13:5];
        io_enqLsq_req_7_bits_r_numLsElem = _RANDOM[9'h14C][6:2];
        io_enqLsq_req_7_bits_lqIdx_r_flag = _RANDOM[9'h14C][7];
        io_enqLsq_req_7_bits_lqIdx_r_value = _RANDOM[9'h14C][14:8];
        io_enqLsq_req_7_bits_sqIdx_r_flag = _RANDOM[9'h14C][15];
        io_enqLsq_req_7_bits_sqIdx_r_value = _RANDOM[9'h14C][21:16];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        lqPtr_flag = 1'h0;
        lqPtr_value = 7'h0;
        sqPtr_flag = 1'h0;
        sqPtr_value = 6'h0;
        lqCounter = 7'h48;
        sqCounter = 6'h38;
        t3_lqCancelCnt_next_r = 7'h0;
        t3_sqCancelCnt_next_r = 6'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_canAccept = io_enq_canAccept_REG;
  assign io_enq_resp_0_lqIdx_flag = io_enq_resp_0_lqIdx_flag_0;
  assign io_enq_resp_0_lqIdx_value = _io_enq_resp_0_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_0_sqIdx_flag = io_enq_resp_0_sqIdx_flag_0;
  assign io_enq_resp_0_sqIdx_value = _io_enq_resp_0_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_1_lqIdx_flag = io_enq_resp_1_lqIdx_flag_0;
  assign io_enq_resp_1_lqIdx_value = _io_enq_resp_1_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_1_sqIdx_flag = io_enq_resp_1_sqIdx_flag_0;
  assign io_enq_resp_1_sqIdx_value = _io_enq_resp_1_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_2_lqIdx_flag = io_enq_resp_2_lqIdx_flag_0;
  assign io_enq_resp_2_lqIdx_value = _io_enq_resp_2_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_2_sqIdx_flag = io_enq_resp_2_sqIdx_flag_0;
  assign io_enq_resp_2_sqIdx_value = _io_enq_resp_2_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_3_lqIdx_flag = io_enq_resp_3_lqIdx_flag_0;
  assign io_enq_resp_3_lqIdx_value = _io_enq_resp_3_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_3_sqIdx_flag = io_enq_resp_3_sqIdx_flag_0;
  assign io_enq_resp_3_sqIdx_value = _io_enq_resp_3_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_4_lqIdx_flag = io_enq_resp_4_lqIdx_flag_0;
  assign io_enq_resp_4_lqIdx_value = _io_enq_resp_4_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_4_sqIdx_flag = io_enq_resp_4_sqIdx_flag_0;
  assign io_enq_resp_4_sqIdx_value = _io_enq_resp_4_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_5_lqIdx_flag = io_enq_resp_5_lqIdx_flag_0;
  assign io_enq_resp_5_lqIdx_value = _io_enq_resp_5_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_5_sqIdx_flag = io_enq_resp_5_sqIdx_flag_0;
  assign io_enq_resp_5_sqIdx_value = _io_enq_resp_5_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_6_lqIdx_flag = io_enq_resp_6_lqIdx_flag_0;
  assign io_enq_resp_6_lqIdx_value = _io_enq_resp_6_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_6_sqIdx_flag = io_enq_resp_6_sqIdx_flag_0;
  assign io_enq_resp_6_sqIdx_value = _io_enq_resp_6_sqIdx_new_ptr_value_T_1;
  assign io_enq_resp_7_lqIdx_flag = io_enq_resp_7_lqIdx_flag_0;
  assign io_enq_resp_7_lqIdx_value = _io_enq_resp_7_lqIdx_new_ptr_value_T_1;
  assign io_enq_resp_7_sqIdx_flag = io_enq_resp_7_sqIdx_flag_0;
  assign io_enq_resp_7_sqIdx_value = _io_enq_resp_7_sqIdx_new_ptr_value_T_1;
  assign io_lqFreeCount = lqCounter;
  assign io_sqFreeCount = sqCounter;
  assign io_enqLsq_needAlloc_0 = REG_0;
  assign io_enqLsq_needAlloc_1 = REG_1;
  assign io_enqLsq_needAlloc_2 = REG_2;
  assign io_enqLsq_needAlloc_3 = REG_3;
  assign io_enqLsq_needAlloc_4 = REG_4;
  assign io_enqLsq_needAlloc_5 = REG_5;
  assign io_enqLsq_needAlloc_6 = REG_6;
  assign io_enqLsq_needAlloc_7 = REG_7;
  assign io_enqLsq_req_0_valid = io_enqLsq_req_0_valid_REG;
  assign io_enqLsq_req_0_bits_fuType = io_enqLsq_req_0_bits_r_fuType;
  assign io_enqLsq_req_0_bits_uopIdx = io_enqLsq_req_0_bits_r_uopIdx;
  assign io_enqLsq_req_0_bits_robIdx_flag = io_enqLsq_req_0_bits_r_robIdx_flag;
  assign io_enqLsq_req_0_bits_robIdx_value = io_enqLsq_req_0_bits_r_robIdx_value;
  assign io_enqLsq_req_0_bits_lqIdx_flag = io_enqLsq_req_0_bits_lqIdx_r_flag;
  assign io_enqLsq_req_0_bits_lqIdx_value = io_enqLsq_req_0_bits_lqIdx_r_value;
  assign io_enqLsq_req_0_bits_sqIdx_flag = io_enqLsq_req_0_bits_sqIdx_r_flag;
  assign io_enqLsq_req_0_bits_sqIdx_value = io_enqLsq_req_0_bits_sqIdx_r_value;
  assign io_enqLsq_req_0_bits_numLsElem = io_enqLsq_req_0_bits_r_numLsElem;
  assign io_enqLsq_req_1_valid = io_enqLsq_req_1_valid_REG;
  assign io_enqLsq_req_1_bits_fuType = io_enqLsq_req_1_bits_r_fuType;
  assign io_enqLsq_req_1_bits_uopIdx = io_enqLsq_req_1_bits_r_uopIdx;
  assign io_enqLsq_req_1_bits_robIdx_flag = io_enqLsq_req_1_bits_r_robIdx_flag;
  assign io_enqLsq_req_1_bits_robIdx_value = io_enqLsq_req_1_bits_r_robIdx_value;
  assign io_enqLsq_req_1_bits_lqIdx_flag = io_enqLsq_req_1_bits_lqIdx_r_flag;
  assign io_enqLsq_req_1_bits_lqIdx_value = io_enqLsq_req_1_bits_lqIdx_r_value;
  assign io_enqLsq_req_1_bits_sqIdx_flag = io_enqLsq_req_1_bits_sqIdx_r_flag;
  assign io_enqLsq_req_1_bits_sqIdx_value = io_enqLsq_req_1_bits_sqIdx_r_value;
  assign io_enqLsq_req_1_bits_numLsElem = io_enqLsq_req_1_bits_r_numLsElem;
  assign io_enqLsq_req_2_valid = io_enqLsq_req_2_valid_REG;
  assign io_enqLsq_req_2_bits_fuType = io_enqLsq_req_2_bits_r_fuType;
  assign io_enqLsq_req_2_bits_uopIdx = io_enqLsq_req_2_bits_r_uopIdx;
  assign io_enqLsq_req_2_bits_robIdx_flag = io_enqLsq_req_2_bits_r_robIdx_flag;
  assign io_enqLsq_req_2_bits_robIdx_value = io_enqLsq_req_2_bits_r_robIdx_value;
  assign io_enqLsq_req_2_bits_lqIdx_flag = io_enqLsq_req_2_bits_lqIdx_r_flag;
  assign io_enqLsq_req_2_bits_lqIdx_value = io_enqLsq_req_2_bits_lqIdx_r_value;
  assign io_enqLsq_req_2_bits_sqIdx_flag = io_enqLsq_req_2_bits_sqIdx_r_flag;
  assign io_enqLsq_req_2_bits_sqIdx_value = io_enqLsq_req_2_bits_sqIdx_r_value;
  assign io_enqLsq_req_2_bits_numLsElem = io_enqLsq_req_2_bits_r_numLsElem;
  assign io_enqLsq_req_3_valid = io_enqLsq_req_3_valid_REG;
  assign io_enqLsq_req_3_bits_fuType = io_enqLsq_req_3_bits_r_fuType;
  assign io_enqLsq_req_3_bits_uopIdx = io_enqLsq_req_3_bits_r_uopIdx;
  assign io_enqLsq_req_3_bits_robIdx_flag = io_enqLsq_req_3_bits_r_robIdx_flag;
  assign io_enqLsq_req_3_bits_robIdx_value = io_enqLsq_req_3_bits_r_robIdx_value;
  assign io_enqLsq_req_3_bits_lqIdx_flag = io_enqLsq_req_3_bits_lqIdx_r_flag;
  assign io_enqLsq_req_3_bits_lqIdx_value = io_enqLsq_req_3_bits_lqIdx_r_value;
  assign io_enqLsq_req_3_bits_sqIdx_flag = io_enqLsq_req_3_bits_sqIdx_r_flag;
  assign io_enqLsq_req_3_bits_sqIdx_value = io_enqLsq_req_3_bits_sqIdx_r_value;
  assign io_enqLsq_req_3_bits_numLsElem = io_enqLsq_req_3_bits_r_numLsElem;
  assign io_enqLsq_req_4_valid = io_enqLsq_req_4_valid_REG;
  assign io_enqLsq_req_4_bits_fuType = io_enqLsq_req_4_bits_r_fuType;
  assign io_enqLsq_req_4_bits_uopIdx = io_enqLsq_req_4_bits_r_uopIdx;
  assign io_enqLsq_req_4_bits_robIdx_flag = io_enqLsq_req_4_bits_r_robIdx_flag;
  assign io_enqLsq_req_4_bits_robIdx_value = io_enqLsq_req_4_bits_r_robIdx_value;
  assign io_enqLsq_req_4_bits_lqIdx_flag = io_enqLsq_req_4_bits_lqIdx_r_flag;
  assign io_enqLsq_req_4_bits_lqIdx_value = io_enqLsq_req_4_bits_lqIdx_r_value;
  assign io_enqLsq_req_4_bits_sqIdx_flag = io_enqLsq_req_4_bits_sqIdx_r_flag;
  assign io_enqLsq_req_4_bits_sqIdx_value = io_enqLsq_req_4_bits_sqIdx_r_value;
  assign io_enqLsq_req_4_bits_numLsElem = io_enqLsq_req_4_bits_r_numLsElem;
  assign io_enqLsq_req_5_valid = io_enqLsq_req_5_valid_REG;
  assign io_enqLsq_req_5_bits_fuType = io_enqLsq_req_5_bits_r_fuType;
  assign io_enqLsq_req_5_bits_uopIdx = io_enqLsq_req_5_bits_r_uopIdx;
  assign io_enqLsq_req_5_bits_robIdx_flag = io_enqLsq_req_5_bits_r_robIdx_flag;
  assign io_enqLsq_req_5_bits_robIdx_value = io_enqLsq_req_5_bits_r_robIdx_value;
  assign io_enqLsq_req_5_bits_lqIdx_flag = io_enqLsq_req_5_bits_lqIdx_r_flag;
  assign io_enqLsq_req_5_bits_lqIdx_value = io_enqLsq_req_5_bits_lqIdx_r_value;
  assign io_enqLsq_req_5_bits_sqIdx_flag = io_enqLsq_req_5_bits_sqIdx_r_flag;
  assign io_enqLsq_req_5_bits_sqIdx_value = io_enqLsq_req_5_bits_sqIdx_r_value;
  assign io_enqLsq_req_5_bits_numLsElem = io_enqLsq_req_5_bits_r_numLsElem;
  assign io_enqLsq_req_6_valid = io_enqLsq_req_6_valid_REG;
  assign io_enqLsq_req_6_bits_fuType = io_enqLsq_req_6_bits_r_fuType;
  assign io_enqLsq_req_6_bits_uopIdx = io_enqLsq_req_6_bits_r_uopIdx;
  assign io_enqLsq_req_6_bits_robIdx_flag = io_enqLsq_req_6_bits_r_robIdx_flag;
  assign io_enqLsq_req_6_bits_robIdx_value = io_enqLsq_req_6_bits_r_robIdx_value;
  assign io_enqLsq_req_6_bits_lqIdx_flag = io_enqLsq_req_6_bits_lqIdx_r_flag;
  assign io_enqLsq_req_6_bits_lqIdx_value = io_enqLsq_req_6_bits_lqIdx_r_value;
  assign io_enqLsq_req_6_bits_sqIdx_flag = io_enqLsq_req_6_bits_sqIdx_r_flag;
  assign io_enqLsq_req_6_bits_sqIdx_value = io_enqLsq_req_6_bits_sqIdx_r_value;
  assign io_enqLsq_req_6_bits_numLsElem = io_enqLsq_req_6_bits_r_numLsElem;
  assign io_enqLsq_req_7_valid = io_enqLsq_req_7_valid_REG;
  assign io_enqLsq_req_7_bits_fuType = io_enqLsq_req_7_bits_r_fuType;
  assign io_enqLsq_req_7_bits_uopIdx = io_enqLsq_req_7_bits_r_uopIdx;
  assign io_enqLsq_req_7_bits_robIdx_flag = io_enqLsq_req_7_bits_r_robIdx_flag;
  assign io_enqLsq_req_7_bits_robIdx_value = io_enqLsq_req_7_bits_r_robIdx_value;
  assign io_enqLsq_req_7_bits_lqIdx_flag = io_enqLsq_req_7_bits_lqIdx_r_flag;
  assign io_enqLsq_req_7_bits_lqIdx_value = io_enqLsq_req_7_bits_lqIdx_r_value;
  assign io_enqLsq_req_7_bits_sqIdx_flag = io_enqLsq_req_7_bits_sqIdx_r_flag;
  assign io_enqLsq_req_7_bits_sqIdx_value = io_enqLsq_req_7_bits_sqIdx_r_value;
  assign io_enqLsq_req_7_bits_numLsElem = io_enqLsq_req_7_bits_r_numLsElem;
endmodule

