// Generated by CIRCT firtool-1.135.0
module PrefetchReceiver_1(
  output        io_req_valid,
  output [29:0] io_req_bits_tag,
  output [11:0] io_req_bits_set,
  input         io_recv_addr_valid,
  input  [63:0] io_recv_addr_bits
);

  assign io_req_valid = io_recv_addr_valid;
  assign io_req_bits_tag = io_recv_addr_bits[47:18];
  assign io_req_bits_set = io_recv_addr_bits[17:6];
endmodule

