// Generated by CIRCT firtool-1.135.0
module AheadBtbBank(
  input          clock,
  input          reset,
  input          io_readReq_valid,
  input  [4:0]   io_readReq_bits_setIdx,
  output         io_readResp_entries_0_valid,
  output [23:0]  io_readResp_entries_0_tag,
  output [4:0]   io_readResp_entries_0_position,
  output [1:0]   io_readResp_entries_0_attribute_branchType,
  output [1:0]   io_readResp_entries_0_attribute_rasAction,
  output [21:0]  io_readResp_entries_0_targetLowerBits,
  output         io_readResp_entries_1_valid,
  output [23:0]  io_readResp_entries_1_tag,
  output [4:0]   io_readResp_entries_1_position,
  output [1:0]   io_readResp_entries_1_attribute_branchType,
  output [1:0]   io_readResp_entries_1_attribute_rasAction,
  output [21:0]  io_readResp_entries_1_targetLowerBits,
  output         io_readResp_entries_2_valid,
  output [23:0]  io_readResp_entries_2_tag,
  output [4:0]   io_readResp_entries_2_position,
  output [1:0]   io_readResp_entries_2_attribute_branchType,
  output [1:0]   io_readResp_entries_2_attribute_rasAction,
  output [21:0]  io_readResp_entries_2_targetLowerBits,
  output         io_readResp_entries_3_valid,
  output [23:0]  io_readResp_entries_3_tag,
  output [4:0]   io_readResp_entries_3_position,
  output [1:0]   io_readResp_entries_3_attribute_branchType,
  output [1:0]   io_readResp_entries_3_attribute_rasAction,
  output [21:0]  io_readResp_entries_3_targetLowerBits,
  output         io_readResp_entries_4_valid,
  output [23:0]  io_readResp_entries_4_tag,
  output [4:0]   io_readResp_entries_4_position,
  output [1:0]   io_readResp_entries_4_attribute_branchType,
  output [1:0]   io_readResp_entries_4_attribute_rasAction,
  output [21:0]  io_readResp_entries_4_targetLowerBits,
  output         io_readResp_entries_5_valid,
  output [23:0]  io_readResp_entries_5_tag,
  output [4:0]   io_readResp_entries_5_position,
  output [1:0]   io_readResp_entries_5_attribute_branchType,
  output [1:0]   io_readResp_entries_5_attribute_rasAction,
  output [21:0]  io_readResp_entries_5_targetLowerBits,
  output         io_readResp_entries_6_valid,
  output [23:0]  io_readResp_entries_6_tag,
  output [4:0]   io_readResp_entries_6_position,
  output [1:0]   io_readResp_entries_6_attribute_branchType,
  output [1:0]   io_readResp_entries_6_attribute_rasAction,
  output [21:0]  io_readResp_entries_6_targetLowerBits,
  output         io_readResp_entries_7_valid,
  output [23:0]  io_readResp_entries_7_tag,
  output [4:0]   io_readResp_entries_7_position,
  output [1:0]   io_readResp_entries_7_attribute_branchType,
  output [1:0]   io_readResp_entries_7_attribute_rasAction,
  output [21:0]  io_readResp_entries_7_targetLowerBits,
  input          io_writeReq_valid,
  input          io_writeReq_bits_needResetCtr,
  input  [4:0]   io_writeReq_bits_setIdx,
  input  [2:0]   io_writeReq_bits_wayIdx,
  input          io_writeReq_bits_entry_valid,
  input  [23:0]  io_writeReq_bits_entry_tag,
  input  [4:0]   io_writeReq_bits_entry_position,
  input  [1:0]   io_writeReq_bits_entry_attribute_branchType,
  input  [1:0]   io_writeReq_bits_entry_attribute_rasAction,
  input  [21:0]  io_writeReq_bits_entry_targetLowerBits,
  output         io_writeResp_valid,
  output         io_writeResp_bits_needResetCtr,
  output [4:0]   io_writeResp_bits_setIdx,
  output [2:0]   io_writeResp_bits_wayIdx,
  output         io_sramResetDone,
  input  [5:0]   boreChildrenBd_bore_addr,
  input  [5:0]   boreChildrenBd_bore_addr_rd,
  input  [111:0] boreChildrenBd_bore_wdata,
  input  [1:0]   boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [111:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input  [5:0]   boreChildrenBd_bore_array,
  input  [5:0]   boreChildrenBd_bore_1_addr,
  input  [5:0]   boreChildrenBd_bore_1_addr_rd,
  input  [111:0] boreChildrenBd_bore_1_wdata,
  input  [1:0]   boreChildrenBd_bore_1_wmask,
  input          boreChildrenBd_bore_1_re,
  input          boreChildrenBd_bore_1_we,
  output [111:0] boreChildrenBd_bore_1_rdata,
  input          boreChildrenBd_bore_1_ack,
  input          boreChildrenBd_bore_1_selectedOH,
  input  [5:0]   boreChildrenBd_bore_1_array,
  input  [5:0]   boreChildrenBd_bore_2_addr,
  input  [5:0]   boreChildrenBd_bore_2_addr_rd,
  input  [111:0] boreChildrenBd_bore_2_wdata,
  input  [1:0]   boreChildrenBd_bore_2_wmask,
  input          boreChildrenBd_bore_2_re,
  input          boreChildrenBd_bore_2_we,
  output [111:0] boreChildrenBd_bore_2_rdata,
  input          boreChildrenBd_bore_2_ack,
  input          boreChildrenBd_bore_2_selectedOH,
  input  [5:0]   boreChildrenBd_bore_2_array,
  input  [5:0]   boreChildrenBd_bore_3_addr,
  input  [5:0]   boreChildrenBd_bore_3_addr_rd,
  input  [111:0] boreChildrenBd_bore_3_wdata,
  input  [1:0]   boreChildrenBd_bore_3_wmask,
  input          boreChildrenBd_bore_3_re,
  input          boreChildrenBd_bore_3_we,
  output [111:0] boreChildrenBd_bore_3_rdata,
  input          boreChildrenBd_bore_3_ack,
  input          boreChildrenBd_bore_3_selectedOH,
  input  [5:0]   boreChildrenBd_bore_3_array,
  input          sigFromSrams_bore_ram_hold,
  input          sigFromSrams_bore_ram_bypass,
  input          sigFromSrams_bore_ram_bp_clken,
  input          sigFromSrams_bore_ram_aux_clk,
  input          sigFromSrams_bore_ram_aux_ckbp,
  input          sigFromSrams_bore_ram_mcp_hold,
  input          sigFromSrams_bore_cgen,
  input          sigFromSrams_bore_1_ram_hold,
  input          sigFromSrams_bore_1_ram_bypass,
  input          sigFromSrams_bore_1_ram_bp_clken,
  input          sigFromSrams_bore_1_ram_aux_clk,
  input          sigFromSrams_bore_1_ram_aux_ckbp,
  input          sigFromSrams_bore_1_ram_mcp_hold,
  input          sigFromSrams_bore_1_cgen,
  input          sigFromSrams_bore_2_ram_hold,
  input          sigFromSrams_bore_2_ram_bypass,
  input          sigFromSrams_bore_2_ram_bp_clken,
  input          sigFromSrams_bore_2_ram_aux_clk,
  input          sigFromSrams_bore_2_ram_aux_ckbp,
  input          sigFromSrams_bore_2_ram_mcp_hold,
  input          sigFromSrams_bore_2_cgen,
  input          sigFromSrams_bore_3_ram_hold,
  input          sigFromSrams_bore_3_ram_bypass,
  input          sigFromSrams_bore_3_ram_bp_clken,
  input          sigFromSrams_bore_3_ram_aux_clk,
  input          sigFromSrams_bore_3_ram_aux_ckbp,
  input          sigFromSrams_bore_3_ram_mcp_hold,
  input          sigFromSrams_bore_3_cgen
);

  wire        _writeBuffer_io_read_0_valid;
  wire [4:0]  _writeBuffer_io_read_0_bits_setIdx;
  wire [2:0]  _writeBuffer_io_read_0_bits_wayIdx;
  wire        _writeBuffer_io_read_0_bits_entry_valid;
  wire [23:0] _writeBuffer_io_read_0_bits_entry_tag;
  wire [4:0]  _writeBuffer_io_read_0_bits_entry_position;
  wire [1:0]  _writeBuffer_io_read_0_bits_entry_attribute_branchType;
  wire [1:0]  _writeBuffer_io_read_0_bits_entry_attribute_rasAction;
  wire [21:0] _writeBuffer_io_read_0_bits_entry_targetLowerBits;
  wire        _sram_io_w_req_ready;
  wire        writeBuffer_io_read_0_ready = _sram_io_w_req_ready & ~io_readReq_valid;
  SplittedSRAMTemplate_2 sram (
    .clock                                     (clock),
    .reset                                     (reset),
    .io_r_req_valid                            (io_readReq_valid),
    .io_r_req_bits_setIdx                      (io_readReq_bits_setIdx),
    .io_r_resp_data_0_valid                    (io_readResp_entries_0_valid),
    .io_r_resp_data_0_tag                      (io_readResp_entries_0_tag),
    .io_r_resp_data_0_position                 (io_readResp_entries_0_position),
    .io_r_resp_data_0_attribute_branchType
      (io_readResp_entries_0_attribute_branchType),
    .io_r_resp_data_0_attribute_rasAction
      (io_readResp_entries_0_attribute_rasAction),
    .io_r_resp_data_0_targetLowerBits          (io_readResp_entries_0_targetLowerBits),
    .io_r_resp_data_1_valid                    (io_readResp_entries_1_valid),
    .io_r_resp_data_1_tag                      (io_readResp_entries_1_tag),
    .io_r_resp_data_1_position                 (io_readResp_entries_1_position),
    .io_r_resp_data_1_attribute_branchType
      (io_readResp_entries_1_attribute_branchType),
    .io_r_resp_data_1_attribute_rasAction
      (io_readResp_entries_1_attribute_rasAction),
    .io_r_resp_data_1_targetLowerBits          (io_readResp_entries_1_targetLowerBits),
    .io_r_resp_data_2_valid                    (io_readResp_entries_2_valid),
    .io_r_resp_data_2_tag                      (io_readResp_entries_2_tag),
    .io_r_resp_data_2_position                 (io_readResp_entries_2_position),
    .io_r_resp_data_2_attribute_branchType
      (io_readResp_entries_2_attribute_branchType),
    .io_r_resp_data_2_attribute_rasAction
      (io_readResp_entries_2_attribute_rasAction),
    .io_r_resp_data_2_targetLowerBits          (io_readResp_entries_2_targetLowerBits),
    .io_r_resp_data_3_valid                    (io_readResp_entries_3_valid),
    .io_r_resp_data_3_tag                      (io_readResp_entries_3_tag),
    .io_r_resp_data_3_position                 (io_readResp_entries_3_position),
    .io_r_resp_data_3_attribute_branchType
      (io_readResp_entries_3_attribute_branchType),
    .io_r_resp_data_3_attribute_rasAction
      (io_readResp_entries_3_attribute_rasAction),
    .io_r_resp_data_3_targetLowerBits          (io_readResp_entries_3_targetLowerBits),
    .io_r_resp_data_4_valid                    (io_readResp_entries_4_valid),
    .io_r_resp_data_4_tag                      (io_readResp_entries_4_tag),
    .io_r_resp_data_4_position                 (io_readResp_entries_4_position),
    .io_r_resp_data_4_attribute_branchType
      (io_readResp_entries_4_attribute_branchType),
    .io_r_resp_data_4_attribute_rasAction
      (io_readResp_entries_4_attribute_rasAction),
    .io_r_resp_data_4_targetLowerBits          (io_readResp_entries_4_targetLowerBits),
    .io_r_resp_data_5_valid                    (io_readResp_entries_5_valid),
    .io_r_resp_data_5_tag                      (io_readResp_entries_5_tag),
    .io_r_resp_data_5_position                 (io_readResp_entries_5_position),
    .io_r_resp_data_5_attribute_branchType
      (io_readResp_entries_5_attribute_branchType),
    .io_r_resp_data_5_attribute_rasAction
      (io_readResp_entries_5_attribute_rasAction),
    .io_r_resp_data_5_targetLowerBits          (io_readResp_entries_5_targetLowerBits),
    .io_r_resp_data_6_valid                    (io_readResp_entries_6_valid),
    .io_r_resp_data_6_tag                      (io_readResp_entries_6_tag),
    .io_r_resp_data_6_position                 (io_readResp_entries_6_position),
    .io_r_resp_data_6_attribute_branchType
      (io_readResp_entries_6_attribute_branchType),
    .io_r_resp_data_6_attribute_rasAction
      (io_readResp_entries_6_attribute_rasAction),
    .io_r_resp_data_6_targetLowerBits          (io_readResp_entries_6_targetLowerBits),
    .io_r_resp_data_7_valid                    (io_readResp_entries_7_valid),
    .io_r_resp_data_7_tag                      (io_readResp_entries_7_tag),
    .io_r_resp_data_7_position                 (io_readResp_entries_7_position),
    .io_r_resp_data_7_attribute_branchType
      (io_readResp_entries_7_attribute_branchType),
    .io_r_resp_data_7_attribute_rasAction
      (io_readResp_entries_7_attribute_rasAction),
    .io_r_resp_data_7_targetLowerBits          (io_readResp_entries_7_targetLowerBits),
    .io_w_req_ready                            (_sram_io_w_req_ready),
    .io_w_req_valid
      (_writeBuffer_io_read_0_valid & ~io_readReq_valid),
    .io_w_req_bits_setIdx                      (_writeBuffer_io_read_0_bits_setIdx),
    .io_w_req_bits_data_0_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_0_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_0_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_0_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_0_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_0_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_1_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_1_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_1_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_1_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_1_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_1_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_2_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_2_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_2_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_2_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_2_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_2_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_3_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_3_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_3_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_3_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_3_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_3_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_4_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_4_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_4_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_4_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_4_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_4_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_5_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_5_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_5_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_5_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_5_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_5_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_6_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_6_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_6_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_6_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_6_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_6_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_data_7_valid                (_writeBuffer_io_read_0_bits_entry_valid),
    .io_w_req_bits_data_7_tag                  (_writeBuffer_io_read_0_bits_entry_tag),
    .io_w_req_bits_data_7_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_w_req_bits_data_7_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_w_req_bits_data_7_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_w_req_bits_data_7_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits),
    .io_w_req_bits_waymask
      (8'h1 << _writeBuffer_io_read_0_bits_wayIdx),
    .io_resetDone                              (io_sramResetDone),
    .boreChildrenBd_bore_addr                  (boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_addr_rd               (boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_wdata                 (boreChildrenBd_bore_wdata),
    .boreChildrenBd_bore_wmask                 (boreChildrenBd_bore_wmask),
    .boreChildrenBd_bore_re                    (boreChildrenBd_bore_re),
    .boreChildrenBd_bore_we                    (boreChildrenBd_bore_we),
    .boreChildrenBd_bore_rdata                 (boreChildrenBd_bore_rdata),
    .boreChildrenBd_bore_ack                   (boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_selectedOH            (boreChildrenBd_bore_selectedOH),
    .boreChildrenBd_bore_array                 (boreChildrenBd_bore_array),
    .boreChildrenBd_bore_1_addr                (boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_1_addr_rd             (boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_1_wdata               (boreChildrenBd_bore_1_wdata),
    .boreChildrenBd_bore_1_wmask               (boreChildrenBd_bore_1_wmask),
    .boreChildrenBd_bore_1_re                  (boreChildrenBd_bore_1_re),
    .boreChildrenBd_bore_1_we                  (boreChildrenBd_bore_1_we),
    .boreChildrenBd_bore_1_rdata               (boreChildrenBd_bore_1_rdata),
    .boreChildrenBd_bore_1_ack                 (boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_1_selectedOH          (boreChildrenBd_bore_1_selectedOH),
    .boreChildrenBd_bore_1_array               (boreChildrenBd_bore_1_array),
    .boreChildrenBd_bore_2_addr                (boreChildrenBd_bore_2_addr),
    .boreChildrenBd_bore_2_addr_rd             (boreChildrenBd_bore_2_addr_rd),
    .boreChildrenBd_bore_2_wdata               (boreChildrenBd_bore_2_wdata),
    .boreChildrenBd_bore_2_wmask               (boreChildrenBd_bore_2_wmask),
    .boreChildrenBd_bore_2_re                  (boreChildrenBd_bore_2_re),
    .boreChildrenBd_bore_2_we                  (boreChildrenBd_bore_2_we),
    .boreChildrenBd_bore_2_rdata               (boreChildrenBd_bore_2_rdata),
    .boreChildrenBd_bore_2_ack                 (boreChildrenBd_bore_2_ack),
    .boreChildrenBd_bore_2_selectedOH          (boreChildrenBd_bore_2_selectedOH),
    .boreChildrenBd_bore_2_array               (boreChildrenBd_bore_2_array),
    .boreChildrenBd_bore_3_addr                (boreChildrenBd_bore_3_addr),
    .boreChildrenBd_bore_3_addr_rd             (boreChildrenBd_bore_3_addr_rd),
    .boreChildrenBd_bore_3_wdata               (boreChildrenBd_bore_3_wdata),
    .boreChildrenBd_bore_3_wmask               (boreChildrenBd_bore_3_wmask),
    .boreChildrenBd_bore_3_re                  (boreChildrenBd_bore_3_re),
    .boreChildrenBd_bore_3_we                  (boreChildrenBd_bore_3_we),
    .boreChildrenBd_bore_3_rdata               (boreChildrenBd_bore_3_rdata),
    .boreChildrenBd_bore_3_ack                 (boreChildrenBd_bore_3_ack),
    .boreChildrenBd_bore_3_selectedOH          (boreChildrenBd_bore_3_selectedOH),
    .boreChildrenBd_bore_3_array               (boreChildrenBd_bore_3_array),
    .sigFromSrams_bore_ram_hold                (sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass              (sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken            (sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk             (sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp            (sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold            (sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen                    (sigFromSrams_bore_cgen),
    .sigFromSrams_bore_1_ram_hold              (sigFromSrams_bore_1_ram_hold),
    .sigFromSrams_bore_1_ram_bypass            (sigFromSrams_bore_1_ram_bypass),
    .sigFromSrams_bore_1_ram_bp_clken          (sigFromSrams_bore_1_ram_bp_clken),
    .sigFromSrams_bore_1_ram_aux_clk           (sigFromSrams_bore_1_ram_aux_clk),
    .sigFromSrams_bore_1_ram_aux_ckbp          (sigFromSrams_bore_1_ram_aux_ckbp),
    .sigFromSrams_bore_1_ram_mcp_hold          (sigFromSrams_bore_1_ram_mcp_hold),
    .sigFromSrams_bore_1_cgen                  (sigFromSrams_bore_1_cgen),
    .sigFromSrams_bore_2_ram_hold              (sigFromSrams_bore_2_ram_hold),
    .sigFromSrams_bore_2_ram_bypass            (sigFromSrams_bore_2_ram_bypass),
    .sigFromSrams_bore_2_ram_bp_clken          (sigFromSrams_bore_2_ram_bp_clken),
    .sigFromSrams_bore_2_ram_aux_clk           (sigFromSrams_bore_2_ram_aux_clk),
    .sigFromSrams_bore_2_ram_aux_ckbp          (sigFromSrams_bore_2_ram_aux_ckbp),
    .sigFromSrams_bore_2_ram_mcp_hold          (sigFromSrams_bore_2_ram_mcp_hold),
    .sigFromSrams_bore_2_cgen                  (sigFromSrams_bore_2_cgen),
    .sigFromSrams_bore_3_ram_hold              (sigFromSrams_bore_3_ram_hold),
    .sigFromSrams_bore_3_ram_bypass            (sigFromSrams_bore_3_ram_bypass),
    .sigFromSrams_bore_3_ram_bp_clken          (sigFromSrams_bore_3_ram_bp_clken),
    .sigFromSrams_bore_3_ram_aux_clk           (sigFromSrams_bore_3_ram_aux_clk),
    .sigFromSrams_bore_3_ram_aux_ckbp          (sigFromSrams_bore_3_ram_aux_ckbp),
    .sigFromSrams_bore_3_ram_mcp_hold          (sigFromSrams_bore_3_ram_mcp_hold),
    .sigFromSrams_bore_3_cgen                  (sigFromSrams_bore_3_cgen)
  );
  WriteBuffer writeBuffer (
    .clock                                      (clock),
    .reset                                      (reset),
    .io_write_0_valid                           (io_writeReq_valid),
    .io_write_0_bits_needResetCtr               (io_writeReq_bits_needResetCtr),
    .io_write_0_bits_setIdx                     (io_writeReq_bits_setIdx),
    .io_write_0_bits_wayIdx                     (io_writeReq_bits_wayIdx),
    .io_write_0_bits_entry_valid                (io_writeReq_bits_entry_valid),
    .io_write_0_bits_entry_tag                  (io_writeReq_bits_entry_tag),
    .io_write_0_bits_entry_position             (io_writeReq_bits_entry_position),
    .io_write_0_bits_entry_attribute_branchType
      (io_writeReq_bits_entry_attribute_branchType),
    .io_write_0_bits_entry_attribute_rasAction
      (io_writeReq_bits_entry_attribute_rasAction),
    .io_write_0_bits_entry_targetLowerBits      (io_writeReq_bits_entry_targetLowerBits),
    .io_read_0_ready                            (writeBuffer_io_read_0_ready),
    .io_read_0_valid                            (_writeBuffer_io_read_0_valid),
    .io_read_0_bits_needResetCtr                (io_writeResp_bits_needResetCtr),
    .io_read_0_bits_setIdx                      (_writeBuffer_io_read_0_bits_setIdx),
    .io_read_0_bits_wayIdx                      (_writeBuffer_io_read_0_bits_wayIdx),
    .io_read_0_bits_entry_valid                 (_writeBuffer_io_read_0_bits_entry_valid),
    .io_read_0_bits_entry_tag                   (_writeBuffer_io_read_0_bits_entry_tag),
    .io_read_0_bits_entry_position
      (_writeBuffer_io_read_0_bits_entry_position),
    .io_read_0_bits_entry_attribute_branchType
      (_writeBuffer_io_read_0_bits_entry_attribute_branchType),
    .io_read_0_bits_entry_attribute_rasAction
      (_writeBuffer_io_read_0_bits_entry_attribute_rasAction),
    .io_read_0_bits_entry_targetLowerBits
      (_writeBuffer_io_read_0_bits_entry_targetLowerBits)
  );
  assign io_writeResp_valid = writeBuffer_io_read_0_ready & _writeBuffer_io_read_0_valid;
  assign io_writeResp_bits_setIdx = _writeBuffer_io_read_0_bits_setIdx;
  assign io_writeResp_bits_wayIdx = _writeBuffer_io_read_0_bits_wayIdx;
endmodule

