// Generated by CIRCT firtool-1.135.0
module compare_3to1(
  input  [63:0] io_a,
  input  [63:0] io_b,
  input  [63:0] io_c,
  input         io_max,
  input         io_signed,
  output [63:0] io_d
);

  wire         _adder_xb_2_io_cout;
  wire         _adder_xb_1_io_cout;
  wire         _adder_xb_io_cout;
  wire [191:0] vs_lo_inv = ~{io_b, {2{io_c}}};
  wire         less_0 =
    io_signed ? io_b[63] ^ vs_lo_inv[63] ^ _adder_xb_io_cout : ~_adder_xb_io_cout;
  wire         less_1 =
    io_signed ? io_a[63] ^ vs_lo_inv[127] ^ _adder_xb_1_io_cout : ~_adder_xb_1_io_cout;
  wire         less_2 =
    io_signed ? io_a[63] ^ vs_lo_inv[191] ^ _adder_xb_2_io_cout : ~_adder_xb_2_io_cout;
  Adder_xb adder_xb (
    .io_in1  (vs_lo_inv[63:0]),
    .io_in2  (io_b),
    .io_cout (_adder_xb_io_cout)
  );
  Adder_xb adder_xb_1 (
    .io_in1  (vs_lo_inv[127:64]),
    .io_in2  (io_a),
    .io_cout (_adder_xb_1_io_cout)
  );
  Adder_xb adder_xb_2 (
    .io_in1  (vs_lo_inv[191:128]),
    .io_in2  (io_a),
    .io_cout (_adder_xb_2_io_cout)
  );
  assign io_d =
    less_2 & less_1 & ~io_max | ~less_2 & ~less_1 & io_max
      ? io_a
      : ~less_2 & less_0 & ~io_max | less_2 & ~less_0 & io_max
          ? io_b
          : ~less_1 & ~less_0 & ~io_max | less_1 & less_0 & io_max ? io_c : 64'h0;
endmodule

