// Generated by CIRCT firtool-1.135.0
module FarShiftRightWithMuxInvFirst_2(
  input  [51:0] io_src,
  input  [4:0]  io_shiftValue,
  output [51:0] io_result,
  input         io_EOP
);

  wire [51:0] io_result_res_vec_1 = io_shiftValue[0] ? {io_EOP, io_src[51:1]} : io_src;
  wire [51:0] io_result_res_vec_2 =
    io_shiftValue[1] ? {{2{io_EOP}}, io_result_res_vec_1[51:2]} : io_result_res_vec_1;
  wire [51:0] io_result_res_vec_3 =
    io_shiftValue[2] ? {{4{io_EOP}}, io_result_res_vec_2[51:4]} : io_result_res_vec_2;
  wire [51:0] io_result_res_vec_4 =
    io_shiftValue[3] ? {{8{io_EOP}}, io_result_res_vec_3[51:8]} : io_result_res_vec_3;
  assign io_result =
    io_shiftValue[4] ? {{16{io_EOP}}, io_result_res_vec_4[51:16]} : io_result_res_vec_4;
endmodule

