// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module McyclecfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [63:0] rdata,
  output        regOut_MINH,
  output        regOut_SINH,
  output        regOut_UINH,
  output        regOut_VSINH,
  output        regOut_VUINH,
  input         fromSireg2_valid,
  input  [63:0] fromSireg2_bits,
  output [63:0] toSireg2
);

  reg reg_MINH;
  reg reg_SINH;
  reg reg_UINH;
  reg reg_VSINH;
  reg reg_VUINH;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      reg_MINH <= 1'h0;
      reg_SINH <= 1'h0;
      reg_UINH <= 1'h0;
      reg_VSINH <= 1'h0;
      reg_VUINH <= 1'h0;
    end
    else if (w_wen) begin
      reg_MINH <= w_wdata[62];
      reg_SINH <= w_wdata[61];
      reg_UINH <= w_wdata[60];
      reg_VSINH <= w_wdata[59];
      reg_VUINH <= w_wdata[58];
    end
    else if (fromSireg2_valid) begin
      reg_MINH <= fromSireg2_bits[62];
      reg_SINH <= fromSireg2_bits[61];
      reg_UINH <= fromSireg2_bits[60];
      reg_VSINH <= fromSireg2_bits[59];
      reg_VUINH <= fromSireg2_bits[58];
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        reg_MINH = _RANDOM[/*Zero width*/ 1'b0][0];
        reg_SINH = _RANDOM[/*Zero width*/ 1'b0][1];
        reg_UINH = _RANDOM[/*Zero width*/ 1'b0][2];
        reg_VSINH = _RANDOM[/*Zero width*/ 1'b0][3];
        reg_VUINH = _RANDOM[/*Zero width*/ 1'b0][4];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        reg_MINH = 1'h0;
        reg_SINH = 1'h0;
        reg_UINH = 1'h0;
        reg_VSINH = 1'h0;
        reg_VUINH = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign rdata = {1'h0, reg_MINH, reg_SINH, reg_UINH, reg_VSINH, reg_VUINH, 58'h0};
  assign regOut_MINH = reg_MINH;
  assign regOut_SINH = reg_SINH;
  assign regOut_UINH = reg_UINH;
  assign regOut_VSINH = reg_VSINH;
  assign regOut_VUINH = reg_VUINH;
  assign toSireg2 = {1'h0, reg_MINH, reg_SINH, reg_UINH, reg_VSINH, reg_VUINH, 58'h0};
endmodule

