// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module OldestArbiter(
  input        clock,
  input        reset,
  output       io_in_0_ready,
  input        io_in_0_valid,
  input  [5:0] io_in_0_bits_addr,
  input        io_in_0_bits_robIdx_flag,
  input  [8:0] io_in_0_bits_robIdx_value,
  input        io_in_0_bits_issueValid,
  output       io_in_1_ready,
  input        io_in_1_valid,
  input  [5:0] io_in_1_bits_addr,
  input        io_in_1_bits_robIdx_flag,
  input  [8:0] io_in_1_bits_robIdx_value,
  input        io_in_1_bits_issueValid,
  output       io_out_valid,
  output [5:0] io_out_bits_addr,
  output       io_out_bits_robIdx_flag,
  output [8:0] io_out_bits_robIdx_value,
  output       io_out_bits_issueValid
);

  reg        validVecReg_0;
  reg        validVecReg_1;
  reg        robIdxVecReg_0_flag;
  reg  [8:0] robIdxVecReg_0_value;
  reg        robIdxVecReg_1_flag;
  reg  [8:0] robIdxVecReg_1_value;
  reg  [1:0] priorityVecReg_0;
  reg  [1:0] priorityVecReg_1;
  wire [1:0] mergePriority =
    (io_in_0_valid ? priorityVecReg_0 : 2'h0) | (io_in_1_valid ? priorityVecReg_1 : 2'h0);
  wire [1:0] lzdMergePriority = mergePriority[0] ? 2'h0 : mergePriority[1] ? 2'h1 : 2'h2;
  wire       olderThanOtherNum_differentFlag = robIdxVecReg_0_flag ^ robIdxVecReg_1_flag;
  wire       olderThanOtherNum =
    olderThanOtherNum_differentFlag ^ robIdxVecReg_0_value < robIdxVecReg_1_value
    | ~validVecReg_1;
  wire       lzdHit_0 =
    (priorityVecReg_0[0] ? 2'h0 : priorityVecReg_0[1] ? 2'h1 : 2'h2) == lzdMergePriority;
  wire       olderThanOtherNum_1 =
    olderThanOtherNum_differentFlag ^ robIdxVecReg_1_value < robIdxVecReg_0_value
    | ~validVecReg_0;
  wire       lzdHit_1 =
    (priorityVecReg_1[0] ? 2'h0 : priorityVecReg_1[1] ? 2'h1 : 2'h2) == lzdMergePriority;
  wire       _GEN = validVecReg_0 & validVecReg_1;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      validVecReg_0 <= 1'h0;
      validVecReg_1 <= 1'h0;
      priorityVecReg_0 <= 2'h1;
      priorityVecReg_1 <= 2'h2;
    end
    else begin
      validVecReg_0 <= io_in_0_valid;
      validVecReg_1 <= io_in_1_valid;
      priorityVecReg_0 <= _GEN ? 2'h2 >> olderThanOtherNum : 2'h1;
      priorityVecReg_1 <= _GEN ? 2'h2 >> olderThanOtherNum_1 : 2'h2;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    robIdxVecReg_0_flag <= io_in_0_bits_robIdx_flag;
    robIdxVecReg_0_value <= io_in_0_bits_robIdx_value;
    robIdxVecReg_1_flag <= io_in_1_bits_robIdx_flag;
    robIdxVecReg_1_value <= io_in_1_bits_robIdx_value;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        validVecReg_0 = _RANDOM[/*Zero width*/ 1'b0][0];
        validVecReg_1 = _RANDOM[/*Zero width*/ 1'b0][1];
        robIdxVecReg_0_flag = _RANDOM[/*Zero width*/ 1'b0][2];
        robIdxVecReg_0_value = _RANDOM[/*Zero width*/ 1'b0][11:3];
        robIdxVecReg_1_flag = _RANDOM[/*Zero width*/ 1'b0][12];
        robIdxVecReg_1_value = _RANDOM[/*Zero width*/ 1'b0][21:13];
        priorityVecReg_0 = _RANDOM[/*Zero width*/ 1'b0][23:22];
        priorityVecReg_1 = _RANDOM[/*Zero width*/ 1'b0][25:24];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        validVecReg_0 = 1'h0;
        validVecReg_1 = 1'h0;
        priorityVecReg_0 = 2'h1;
        priorityVecReg_1 = 2'h2;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = ~io_in_0_valid | lzdHit_0;
  assign io_in_1_ready = ~io_in_1_valid | lzdHit_1;
  assign io_out_valid = io_in_0_valid | io_in_1_valid;
  assign io_out_bits_addr =
    (lzdHit_0 ? io_in_0_bits_addr : 6'h0) | (lzdHit_1 ? io_in_1_bits_addr : 6'h0);
  assign io_out_bits_robIdx_flag =
    lzdHit_0 & io_in_0_bits_robIdx_flag | lzdHit_1 & io_in_1_bits_robIdx_flag;
  assign io_out_bits_robIdx_value =
    (lzdHit_0 ? io_in_0_bits_robIdx_value : 9'h0)
    | (lzdHit_1 ? io_in_1_bits_robIdx_value : 9'h0);
  assign io_out_bits_issueValid =
    lzdHit_0 & io_in_0_bits_issueValid | lzdHit_1 & io_in_1_bits_issueValid;
endmodule

