// Generated by CIRCT firtool-1.135.0
module Pmaaddr29Module(
  output [63:0] rdata,
  output [63:0] regOut_ALL,
  input  [63:0] addrRData_29,
  input  [63:0] addrRegOut_29
);

  assign rdata = addrRData_29;
  assign regOut_ALL = addrRegOut_29;
endmodule

