// Generated by CIRCT firtool-1.135.0
module PPGen(
  input  [63:0] io_in_b,
  input  [3:0]  io_in_booth,
  input         io_in_sign,
  output [65:0] io_out_ppOut,
  output        io_out_ppCOut
);

  wire [65:0] _ppNeg_T = {66{io_in_booth[2]}};
  wire [65:0] _ppNeg_T_5 = {66{io_in_booth[3]}};
  assign io_out_ppOut =
    {66{io_in_booth[0]}}
    & (_ppNeg_T & {io_in_sign, io_in_b, 1'h0} | _ppNeg_T_5 & {{2{io_in_sign}}, io_in_b})
    | {66{io_in_booth[1]}}
    & (_ppNeg_T & {~io_in_sign, ~io_in_b, 1'h1} | _ppNeg_T_5
       & {{2{~io_in_sign}}, ~io_in_b});
  assign io_out_ppCOut = io_in_booth[1];
endmodule

