// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RedirectGenerator(
  input         clock,
  input         reset,
  input         io_oldestExuRedirect_valid,
  input         io_oldestExuRedirect_bits_ftqIdx_flag,
  input  [5:0]  io_oldestExuRedirect_bits_ftqIdx_value,
  input  [49:0] io_oldestExuRedirect_bits_pc,
  input         io_oldestExuRedirect_bits_taken,
  input  [4:0]  io_oldestExuRedirect_bits_ftqOffset,
  input         io_oldestExuRedirect_bits_isRVC,
  input  [1:0]  io_oldestExuRedirect_bits_attribute_branchType,
  input  [1:0]  io_oldestExuRedirect_bits_attribute_rasAction,
  input  [49:0] io_oldestExuRedirect_bits_target,
  input         io_oldestExuRedirect_bits_level,
  input         io_oldestExuRedirect_bits_backendIGPF,
  input         io_oldestExuRedirect_bits_backendIPF,
  input         io_oldestExuRedirect_bits_backendIAF,
  input         io_oldestExuRedirect_bits_robIdx_flag,
  input  [8:0]  io_oldestExuRedirect_bits_robIdx_value,
  input         io_oldestExuRedirect_bits_isMisPred,
  input  [63:0] io_oldestExuRedirect_bits_fullTarget,
  input         io_oldestExuRedirect_bits_debugIsCtrl,
  input         io_loadReplay_valid,
  input         io_loadReplay_bits_ftqIdx_flag,
  input  [5:0]  io_loadReplay_bits_ftqIdx_value,
  input  [49:0] io_loadReplay_bits_pc,
  input  [4:0]  io_loadReplay_bits_ftqOffset,
  input         io_loadReplay_bits_isRVC,
  input  [49:0] io_loadReplay_bits_target,
  input         io_loadReplay_bits_level,
  input         io_loadReplay_bits_robIdx_flag,
  input  [8:0]  io_loadReplay_bits_robIdx_value,
  input         io_robFlush_valid,
  input         io_robFlush_bits_level,
  input         io_robFlush_bits_robIdx_flag,
  input  [8:0]  io_robFlush_bits_robIdx_value,
  output        io_stage2Redirect_valid,
  output        io_stage2Redirect_bits_ftqIdx_flag,
  output [5:0]  io_stage2Redirect_bits_ftqIdx_value,
  output [49:0] io_stage2Redirect_bits_pc,
  output        io_stage2Redirect_bits_taken,
  output [4:0]  io_stage2Redirect_bits_ftqOffset,
  output        io_stage2Redirect_bits_isRVC,
  output [1:0]  io_stage2Redirect_bits_attribute_branchType,
  output [1:0]  io_stage2Redirect_bits_attribute_rasAction,
  output [49:0] io_stage2Redirect_bits_target,
  output        io_stage2Redirect_bits_level,
  output        io_stage2Redirect_bits_backendIGPF,
  output        io_stage2Redirect_bits_backendIPF,
  output        io_stage2Redirect_bits_backendIAF,
  output        io_stage2Redirect_bits_robIdx_flag,
  output [8:0]  io_stage2Redirect_bits_robIdx_value,
  output        io_stage2Redirect_bits_isMisPred,
  output [63:0] io_stage2Redirect_bits_fullTarget,
  output        io_stage2Redirect_bits_debugIsCtrl,
  output        io_stage2Redirect_bits_debugIsMemVio
);

  wire        oldestOneHot_compareVec_1_0 =
    io_oldestExuRedirect_bits_robIdx_flag ^ io_loadReplay_bits_robIdx_flag
    ^ io_oldestExuRedirect_bits_robIdx_value > io_loadReplay_bits_robIdx_value;
  wire [1:0]  _oldestOneHot_resultOnehot_T_3 =
    {io_oldestExuRedirect_valid, ~io_loadReplay_valid | ~oldestOneHot_compareVec_1_0};
  wire [1:0]  _oldestOneHot_resultOnehot_T_7 =
    {~io_oldestExuRedirect_valid | oldestOneHot_compareVec_1_0, io_loadReplay_valid};
  reg         flushAfter_valid;
  reg         flushAfter_bits_level;
  reg         flushAfter_bits_robIdx_flag;
  reg  [8:0]  flushAfter_bits_robIdx_value;
  wire [9:0]  _needFlushVec_flushItself_T_6 =
    {flushAfter_bits_robIdx_flag, flushAfter_bits_robIdx_value};
  wire [1:0]  _oldestValid_T_4 =
    {(&_oldestOneHot_resultOnehot_T_7)
       & ~(flushAfter_valid
           & (flushAfter_bits_level
              & {io_loadReplay_bits_robIdx_flag,
                 io_loadReplay_bits_robIdx_value} == _needFlushVec_flushItself_T_6
              | io_loadReplay_bits_robIdx_flag ^ flushAfter_bits_robIdx_flag
              ^ io_loadReplay_bits_robIdx_value > flushAfter_bits_robIdx_value)
           | io_robFlush_valid),
     (&_oldestOneHot_resultOnehot_T_3)
       & ~(flushAfter_valid
           & (flushAfter_bits_level
              & {io_oldestExuRedirect_bits_robIdx_flag,
                 io_oldestExuRedirect_bits_robIdx_value} == _needFlushVec_flushItself_T_6
              | io_oldestExuRedirect_bits_robIdx_flag ^ flushAfter_bits_robIdx_flag
              ^ io_oldestExuRedirect_bits_robIdx_value > flushAfter_bits_robIdx_value)
           | io_robFlush_valid)};
  wire [8:0]  oldestRedirect_bits_robIdx_value =
    ((&_oldestOneHot_resultOnehot_T_3) ? io_oldestExuRedirect_bits_robIdx_value : 9'h0)
    | ((&_oldestOneHot_resultOnehot_T_7) ? io_loadReplay_bits_robIdx_value : 9'h0);
  wire        oldestRedirect_bits_robIdx_flag =
    (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_robIdx_flag
    | (&_oldestOneHot_resultOnehot_T_7) & io_loadReplay_bits_robIdx_flag;
  wire        oldestRedirect_bits_level =
    (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_level
    | (&_oldestOneHot_resultOnehot_T_7) & io_loadReplay_bits_level;
  reg         s1_redirect_bits_reg_ftqIdx_flag;
  reg  [5:0]  s1_redirect_bits_reg_ftqIdx_value;
  reg  [49:0] s1_redirect_bits_reg_pc;
  reg         s1_redirect_bits_reg_taken;
  reg  [4:0]  s1_redirect_bits_reg_ftqOffset;
  reg         s1_redirect_bits_reg_isRVC;
  reg  [1:0]  s1_redirect_bits_reg_attribute_branchType;
  reg  [1:0]  s1_redirect_bits_reg_attribute_rasAction;
  reg  [49:0] s1_redirect_bits_reg_target;
  reg         s1_redirect_bits_reg_level;
  reg         s1_redirect_bits_reg_backendIGPF;
  reg         s1_redirect_bits_reg_backendIPF;
  reg         s1_redirect_bits_reg_backendIAF;
  reg         s1_redirect_bits_reg_robIdx_flag;
  reg  [8:0]  s1_redirect_bits_reg_robIdx_value;
  reg         s1_redirect_bits_reg_isMisPred;
  reg  [63:0] s1_redirect_bits_reg_fullTarget;
  reg         s1_redirect_bits_reg_debugIsCtrl;
  reg         s1_redirect_bits_reg_debugIsMemVio;
  reg         s1_redirect_valid_reg_last_REG;
  reg  [2:0]  flushAfterCounter;
  wire        robFlushOrExuFlushValid = (|_oldestValid_T_4) | io_robFlush_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      flushAfter_valid <= 1'h0;
      flushAfter_bits_level <= 1'h0;
      flushAfter_bits_robIdx_flag <= 1'h0;
      flushAfter_bits_robIdx_value <= 9'h0;
      s1_redirect_valid_reg_last_REG <= 1'h0;
    end
    else begin
      flushAfter_valid <=
        robFlushOrExuFlushValid | flushAfterCounter[0] & flushAfter_valid;
      if (robFlushOrExuFlushValid) begin
        flushAfter_bits_level <=
          io_robFlush_valid ? io_robFlush_bits_level : oldestRedirect_bits_level;
        flushAfter_bits_robIdx_flag <=
          io_robFlush_valid
            ? io_robFlush_bits_robIdx_flag
            : oldestRedirect_bits_robIdx_flag;
        flushAfter_bits_robIdx_value <=
          io_robFlush_valid
            ? io_robFlush_bits_robIdx_value
            : oldestRedirect_bits_robIdx_value;
      end
      s1_redirect_valid_reg_last_REG <= |_oldestValid_T_4;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (|_oldestValid_T_4) begin
      s1_redirect_bits_reg_ftqIdx_flag <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_ftqIdx_flag
        | (&_oldestOneHot_resultOnehot_T_7) & io_loadReplay_bits_ftqIdx_flag;
      s1_redirect_bits_reg_ftqIdx_value <=
        ((&_oldestOneHot_resultOnehot_T_3)
           ? io_oldestExuRedirect_bits_ftqIdx_value
           : 6'h0)
        | ((&_oldestOneHot_resultOnehot_T_7) ? io_loadReplay_bits_ftqIdx_value : 6'h0);
      s1_redirect_bits_reg_pc <=
        ((&_oldestOneHot_resultOnehot_T_3) ? io_oldestExuRedirect_bits_pc : 50'h0)
        | ((&_oldestOneHot_resultOnehot_T_7) ? io_loadReplay_bits_pc : 50'h0);
      s1_redirect_bits_reg_taken <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_taken;
      s1_redirect_bits_reg_ftqOffset <=
        ((&_oldestOneHot_resultOnehot_T_3) ? io_oldestExuRedirect_bits_ftqOffset : 5'h0)
        | ((&_oldestOneHot_resultOnehot_T_7) ? io_loadReplay_bits_ftqOffset : 5'h0);
      s1_redirect_bits_reg_isRVC <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_isRVC
        | (&_oldestOneHot_resultOnehot_T_7) & io_loadReplay_bits_isRVC;
      s1_redirect_bits_reg_attribute_branchType <=
        (&_oldestOneHot_resultOnehot_T_3)
          ? io_oldestExuRedirect_bits_attribute_branchType
          : 2'h0;
      s1_redirect_bits_reg_attribute_rasAction <=
        (&_oldestOneHot_resultOnehot_T_3)
          ? io_oldestExuRedirect_bits_attribute_rasAction
          : 2'h0;
      s1_redirect_bits_reg_target <=
        ((&_oldestOneHot_resultOnehot_T_3) ? io_oldestExuRedirect_bits_target : 50'h0)
        | ((&_oldestOneHot_resultOnehot_T_7) ? io_loadReplay_bits_target : 50'h0);
      s1_redirect_bits_reg_level <= oldestRedirect_bits_level;
      s1_redirect_bits_reg_backendIGPF <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_backendIGPF;
      s1_redirect_bits_reg_backendIPF <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_backendIPF;
      s1_redirect_bits_reg_backendIAF <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_backendIAF;
      s1_redirect_bits_reg_robIdx_flag <= oldestRedirect_bits_robIdx_flag;
      s1_redirect_bits_reg_robIdx_value <= oldestRedirect_bits_robIdx_value;
      s1_redirect_bits_reg_isMisPred <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_isMisPred;
      s1_redirect_bits_reg_fullTarget <=
        (&_oldestOneHot_resultOnehot_T_3) ? io_oldestExuRedirect_bits_fullTarget : 64'h0;
      s1_redirect_bits_reg_debugIsCtrl <=
        (&_oldestOneHot_resultOnehot_T_3) & io_oldestExuRedirect_bits_debugIsCtrl;
      s1_redirect_bits_reg_debugIsMemVio <= &_oldestOneHot_resultOnehot_T_7;
    end
    if (robFlushOrExuFlushValid)
      flushAfterCounter <= 3'h7;
    else if (flushAfterCounter[0])
      flushAfterCounter <= {1'h0, flushAfterCounter[2:1]};
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        flushAfter_valid = _RANDOM[5'h0][0];
        flushAfter_bits_level = _RANDOM[5'h3][23];
        flushAfter_bits_robIdx_flag = _RANDOM[5'h3][27];
        flushAfter_bits_robIdx_value = {_RANDOM[5'h3][31:28], _RANDOM[5'h4][4:0]};
        s1_redirect_bits_reg_ftqIdx_flag = _RANDOM[5'h8][22];
        s1_redirect_bits_reg_ftqIdx_value = _RANDOM[5'h8][28:23];
        s1_redirect_bits_reg_pc =
          {_RANDOM[5'h8][31:29], _RANDOM[5'h9], _RANDOM[5'hA][14:0]};
        s1_redirect_bits_reg_taken = _RANDOM[5'hA][15];
        s1_redirect_bits_reg_ftqOffset = _RANDOM[5'hA][20:16];
        s1_redirect_bits_reg_isRVC = _RANDOM[5'hA][21];
        s1_redirect_bits_reg_attribute_branchType = _RANDOM[5'hA][23:22];
        s1_redirect_bits_reg_attribute_rasAction = _RANDOM[5'hA][25:24];
        s1_redirect_bits_reg_target =
          {_RANDOM[5'hA][31:26], _RANDOM[5'hB], _RANDOM[5'hC][11:0]};
        s1_redirect_bits_reg_level = _RANDOM[5'hC][12];
        s1_redirect_bits_reg_backendIGPF = _RANDOM[5'hC][13];
        s1_redirect_bits_reg_backendIPF = _RANDOM[5'hC][14];
        s1_redirect_bits_reg_backendIAF = _RANDOM[5'hC][15];
        s1_redirect_bits_reg_robIdx_flag = _RANDOM[5'hC][16];
        s1_redirect_bits_reg_robIdx_value = _RANDOM[5'hC][25:17];
        s1_redirect_bits_reg_isMisPred = _RANDOM[5'hC][27];
        s1_redirect_bits_reg_fullTarget =
          {_RANDOM[5'hC][31:28], _RANDOM[5'hD], _RANDOM[5'hE][27:0]};
        s1_redirect_bits_reg_debugIsCtrl = _RANDOM[5'h11][9];
        s1_redirect_bits_reg_debugIsMemVio = _RANDOM[5'h11][10];
        s1_redirect_valid_reg_last_REG = _RANDOM[5'h11][11];
        flushAfterCounter = _RANDOM[5'h11][16:14];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        flushAfter_valid = 1'h0;
        flushAfter_bits_level = 1'h0;
        flushAfter_bits_robIdx_flag = 1'h0;
        flushAfter_bits_robIdx_value = 9'h0;
        s1_redirect_valid_reg_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_stage2Redirect_valid = s1_redirect_valid_reg_last_REG & ~io_robFlush_valid;
  assign io_stage2Redirect_bits_ftqIdx_flag = s1_redirect_bits_reg_ftqIdx_flag;
  assign io_stage2Redirect_bits_ftqIdx_value = s1_redirect_bits_reg_ftqIdx_value;
  assign io_stage2Redirect_bits_pc = s1_redirect_bits_reg_pc;
  assign io_stage2Redirect_bits_taken = s1_redirect_bits_reg_taken;
  assign io_stage2Redirect_bits_ftqOffset = s1_redirect_bits_reg_ftqOffset;
  assign io_stage2Redirect_bits_isRVC = s1_redirect_bits_reg_isRVC;
  assign io_stage2Redirect_bits_attribute_branchType =
    s1_redirect_bits_reg_attribute_branchType;
  assign io_stage2Redirect_bits_attribute_rasAction =
    s1_redirect_bits_reg_attribute_rasAction;
  assign io_stage2Redirect_bits_target = s1_redirect_bits_reg_target;
  assign io_stage2Redirect_bits_level = s1_redirect_bits_reg_level;
  assign io_stage2Redirect_bits_backendIGPF = s1_redirect_bits_reg_backendIGPF;
  assign io_stage2Redirect_bits_backendIPF = s1_redirect_bits_reg_backendIPF;
  assign io_stage2Redirect_bits_backendIAF = s1_redirect_bits_reg_backendIAF;
  assign io_stage2Redirect_bits_robIdx_flag = s1_redirect_bits_reg_robIdx_flag;
  assign io_stage2Redirect_bits_robIdx_value = s1_redirect_bits_reg_robIdx_value;
  assign io_stage2Redirect_bits_isMisPred = s1_redirect_bits_reg_isMisPred;
  assign io_stage2Redirect_bits_fullTarget = s1_redirect_bits_reg_fullTarget;
  assign io_stage2Redirect_bits_debugIsCtrl = s1_redirect_bits_reg_debugIsCtrl;
  assign io_stage2Redirect_bits_debugIsMemVio = s1_redirect_bits_reg_debugIsMemVio;
endmodule

