// Generated by CIRCT firtool-1.135.0
module VIMac64bStage2(
  input  [151:0] io_in_compStage1ResultsS1_0,
  input  [151:0] io_in_compStage1ResultsS1_1,
  input  [151:0] io_in_compStage1ResultsS1_2,
  input  [151:0] io_in_compStage1ResultsS1_3,
  input  [151:0] io_in_compStage1ResultsS1_4,
  input  [151:0] io_in_compStage1ResultsS1_5,
  input  [151:0] io_in_compStage1ResultsS1_6,
  input  [151:0] io_in_wallaceLine34NonFixPS1,
  input  [151:0] io_in_wallaceLine34FixPS1,
  input          io_in_highHalfS1,
  input  [5:0]   io_in_uopIdxS1,
  input          io_in_widenS1,
  input  [1:0]   io_in_vxrmS1,
  input          io_in_isFixPS1,
  input          io_in_sewIs8S1,
  input          io_in_sewIs16S1,
  input          io_in_sewIs32S1,
  input          io_in_sewIs64S1,
  output [151:0] io_out_sumFinalNonFixPS2,
  output [151:0] io_out_sumFinalFixPS2,
  output         io_out_highHalfS2,
  output [5:0]   io_out_uopIdxS2,
  output         io_out_widenS2,
  output [1:0]   io_out_vxrmS2,
  output         io_out_isFixPS2,
  output         io_out_sewIs8S2,
  output         io_out_sewIs16S2,
  output         io_out_sewIs32S2,
  output         io_out_sewIs64S2
);

  wire [151:0] _wallace3to2CompStage2_io_sum34to2NonFixP;
  wire [151:0] _wallace3to2CompStage2_io_cout34to2NonFixP;
  wire [151:0] _wallace3to2CompStage2_io_sum34to2FixP;
  wire [151:0] _wallace3to2CompStage2_io_cout34to2FixP;
  wallace3to2CompressorStage2 wallace3to2CompStage2 (
    .io_compStage1Results_0  (io_in_compStage1ResultsS1_0),
    .io_compStage1Results_1  (io_in_compStage1ResultsS1_1),
    .io_compStage1Results_2  (io_in_compStage1ResultsS1_2),
    .io_compStage1Results_3  (io_in_compStage1ResultsS1_3),
    .io_compStage1Results_4  (io_in_compStage1ResultsS1_4),
    .io_compStage1Results_5  (io_in_compStage1ResultsS1_5),
    .io_compStage1Results_6  (io_in_compStage1ResultsS1_6),
    .io_wallaceLine34NonFixP (io_in_wallaceLine34NonFixPS1),
    .io_wallaceLine34FixP    (io_in_wallaceLine34FixPS1),
    .io_sum34to2NonFixP      (_wallace3to2CompStage2_io_sum34to2NonFixP),
    .io_cout34to2NonFixP     (_wallace3to2CompStage2_io_cout34to2NonFixP),
    .io_sum34to2FixP         (_wallace3to2CompStage2_io_sum34to2FixP),
    .io_cout34to2FixP        (_wallace3to2CompStage2_io_cout34to2FixP)
  );
  fullAdder152b finalSumAdderNonFixP (
    .io_sum34to2  (_wallace3to2CompStage2_io_sum34to2NonFixP),
    .io_cout34to2 (_wallace3to2CompStage2_io_cout34to2NonFixP),
    .io_sumFinal  (io_out_sumFinalNonFixPS2)
  );
  fullAdder152b finalSumAdderFixP (
    .io_sum34to2  (_wallace3to2CompStage2_io_sum34to2FixP),
    .io_cout34to2 (_wallace3to2CompStage2_io_cout34to2FixP),
    .io_sumFinal  (io_out_sumFinalFixPS2)
  );
  assign io_out_highHalfS2 = io_in_highHalfS1;
  assign io_out_uopIdxS2 = io_in_uopIdxS1;
  assign io_out_widenS2 = io_in_widenS1;
  assign io_out_vxrmS2 = io_in_vxrmS1;
  assign io_out_isFixPS2 = io_in_isFixPS1;
  assign io_out_sewIs8S2 = io_in_sewIs8S1;
  assign io_out_sewIs16S2 = io_in_sewIs16S1;
  assign io_out_sewIs32S2 = io_in_sewIs32S1;
  assign io_out_sewIs64S2 = io_in_sewIs64S1;
endmodule

