// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DataStorage_4(
  input          clock,
  input          reset,
  input          io_read_valid,
  input  [3:0]   io_read_bits_way,
  input  [11:0]  io_read_bits_set,
  input          io_write_valid,
  input  [3:0]   io_write_bits_way,
  input  [11:0]  io_write_bits_set,
  output [255:0] io_rdata_data_0_data,
  output [255:0] io_rdata_data_1_data,
  input  [255:0] io_wdata_data_0_data,
  input  [255:0] io_wdata_data_1_data
);

  wire [255:0] _array_io_r_resp_data_0_data_0_data;
  wire [255:0] _array_io_r_resp_data_0_data_1_data;
  wire [15:0]  readIdx = {io_read_bits_way, io_read_bits_set};
  wire [15:0]  writeIdx = {io_write_bits_way, io_write_bits_set};
  reg  [15:0]  writeBuffer_blockIdx;
  reg  [255:0] writeBuffer_data_data_0_data;
  reg  [255:0] writeBuffer_data_data_1_data;
  wire         readBuffer = readIdx == writeBuffer_blockIdx & io_read_valid;
  reg          rdata_s1_REG;
  reg  [255:0] rdata_s1_r_data_0_data;
  reg  [255:0] rdata_s1_r_data_1_data;
  reg          rdata_s2_REG;
  reg  [255:0] rdata_s2_data_0_data;
  reg  [255:0] rdata_s2_data_1_data;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      writeBuffer_blockIdx <= 16'h0;
      writeBuffer_data_data_0_data <= 256'h0;
      writeBuffer_data_data_1_data <= 256'h0;
      rdata_s1_REG <= 1'h0;
      rdata_s1_r_data_0_data <= 256'h0;
      rdata_s1_r_data_1_data <= 256'h0;
      rdata_s2_REG <= 1'h0;
      rdata_s2_data_0_data <= 256'h0;
      rdata_s2_data_1_data <= 256'h0;
    end
    else begin
      if (io_write_valid) begin
        writeBuffer_blockIdx <= writeIdx;
        writeBuffer_data_data_0_data <= io_wdata_data_0_data;
        writeBuffer_data_data_1_data <= io_wdata_data_1_data;
      end
      rdata_s1_REG <= readBuffer;
      if (readBuffer) begin
        rdata_s1_r_data_0_data <= writeBuffer_data_data_0_data;
        rdata_s1_r_data_1_data <= writeBuffer_data_data_1_data;
      end
      rdata_s2_REG <= io_read_valid;
      if (rdata_s2_REG) begin
        rdata_s2_data_0_data <=
          rdata_s1_REG ? rdata_s1_r_data_0_data : _array_io_r_resp_data_0_data_0_data;
        rdata_s2_data_1_data <=
          rdata_s1_REG ? rdata_s1_r_data_1_data : _array_io_r_resp_data_0_data_1_data;
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:48];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h31; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        writeBuffer_blockIdx = _RANDOM[6'h0][15:0];
        writeBuffer_data_data_0_data =
          {_RANDOM[6'h0][31:16],
           _RANDOM[6'h1],
           _RANDOM[6'h2],
           _RANDOM[6'h3],
           _RANDOM[6'h4],
           _RANDOM[6'h5],
           _RANDOM[6'h6],
           _RANDOM[6'h7],
           _RANDOM[6'h8][15:0]};
        writeBuffer_data_data_1_data =
          {_RANDOM[6'h8][31:16],
           _RANDOM[6'h9],
           _RANDOM[6'hA],
           _RANDOM[6'hB],
           _RANDOM[6'hC],
           _RANDOM[6'hD],
           _RANDOM[6'hE],
           _RANDOM[6'hF],
           _RANDOM[6'h10][15:0]};
        rdata_s1_REG = _RANDOM[6'h10][16];
        rdata_s1_r_data_0_data =
          {_RANDOM[6'h10][31:17],
           _RANDOM[6'h11],
           _RANDOM[6'h12],
           _RANDOM[6'h13],
           _RANDOM[6'h14],
           _RANDOM[6'h15],
           _RANDOM[6'h16],
           _RANDOM[6'h17],
           _RANDOM[6'h18][16:0]};
        rdata_s1_r_data_1_data =
          {_RANDOM[6'h18][31:17],
           _RANDOM[6'h19],
           _RANDOM[6'h1A],
           _RANDOM[6'h1B],
           _RANDOM[6'h1C],
           _RANDOM[6'h1D],
           _RANDOM[6'h1E],
           _RANDOM[6'h1F],
           _RANDOM[6'h20][16:0]};
        rdata_s2_REG = _RANDOM[6'h20][17];
        rdata_s2_data_0_data =
          {_RANDOM[6'h20][31:18],
           _RANDOM[6'h21],
           _RANDOM[6'h22],
           _RANDOM[6'h23],
           _RANDOM[6'h24],
           _RANDOM[6'h25],
           _RANDOM[6'h26],
           _RANDOM[6'h27],
           _RANDOM[6'h28][17:0]};
        rdata_s2_data_1_data =
          {_RANDOM[6'h28][31:18],
           _RANDOM[6'h29],
           _RANDOM[6'h2A],
           _RANDOM[6'h2B],
           _RANDOM[6'h2C],
           _RANDOM[6'h2D],
           _RANDOM[6'h2E],
           _RANDOM[6'h2F],
           _RANDOM[6'h30][17:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        writeBuffer_blockIdx = 16'h0;
        writeBuffer_data_data_0_data = 256'h0;
        writeBuffer_data_data_1_data = 256'h0;
        rdata_s1_REG = 1'h0;
        rdata_s1_r_data_0_data = 256'h0;
        rdata_s1_r_data_1_data = 256'h0;
        rdata_s2_REG = 1'h0;
        rdata_s2_data_0_data = 256'h0;
        rdata_s2_data_1_data = 256'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SRAMTemplate_375 array (
    .clock                            (clock),
    .io_r_req_valid                   (~readBuffer),
    .io_r_req_bits_setIdx             (readIdx),
    .io_r_resp_data_0_data_0_data     (_array_io_r_resp_data_0_data_0_data),
    .io_r_resp_data_0_data_1_data     (_array_io_r_resp_data_0_data_1_data),
    .io_w_req_valid                   (writeIdx != writeBuffer_blockIdx & io_write_valid),
    .io_w_req_bits_setIdx             (writeBuffer_blockIdx),
    .io_w_req_bits_data_0_data_0_data (writeBuffer_data_data_0_data),
    .io_w_req_bits_data_0_data_1_data (writeBuffer_data_data_1_data)
  );
  assign io_rdata_data_0_data = rdata_s2_data_0_data;
  assign io_rdata_data_1_data = rdata_s2_data_1_data;
endmodule

