// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module InstrUncacheEntry(
  input         clock,
  input         reset,
  output        io_req_ready,
  input         io_req_valid,
  input  [46:0] io_req_bits_addr_addr,
  input         io_req_bits_memBackTypeMM,
  input         io_req_bits_memPageTypeNC,
  output        io_resp_valid,
  output [31:0] io_resp_bits_data,
  output        io_resp_bits_corrupt,
  output        io_resp_bits_denied,
  output        io_resp_bits_needResend,
  input         io_mmioAcquire_ready,
  output        io_mmioAcquire_valid,
  output [47:0] io_mmioAcquire_bits_address,
  output        io_mmioAcquire_bits_user_memPageType_NC,
  output        io_mmioAcquire_bits_user_memBackType_MM,
  input         io_mmioGrant_valid,
  input         io_mmioGrant_bits_denied,
  input  [63:0] io_mmioGrant_bits_data,
  input         io_mmioGrant_bits_corrupt,
  input         io_wfi_wfiReq,
  output        io_wfi_wfiSafe
);

  reg  [1:0]      state;
  wire            io_req_ready_0 = state == 2'h0;
  reg  [46:0]     reqReg_addr_addr;
  reg             reqReg_memBackTypeMM;
  reg             reqReg_memPageTypeNC;
  reg             resending;
  wire            _io_mmioAcquire_valid_T = state == 2'h1;
  wire            io_mmioAcquire_valid_0 = _io_mmioAcquire_valid_T & ~io_wfi_wfiReq;
  reg  [15:0]     respDataReg_0;
  reg  [15:0]     respDataReg_1;
  reg             respCorruptReg;
  reg             respDeniedReg;
  wire            _reqReg_T = io_req_ready_0 & io_req_valid;
  wire            refillDone = state == 2'h2 & io_mmioGrant_valid;
  wire [3:0]      _shiftedBusData_T_2 = 4'h1 << reqReg_addr_addr[1:0];
  wire [31:0]     shiftedBusData =
    (_shiftedBusData_T_2[0] ? io_mmioGrant_bits_data[31:0] : 32'h0)
    | (_shiftedBusData_T_2[1] ? io_mmioGrant_bits_data[47:16] : 32'h0)
    | (_shiftedBusData_T_2[2] ? io_mmioGrant_bits_data[63:32] : 32'h0)
    | (_shiftedBusData_T_2[3] ? {16'h0, io_mmioGrant_bits_data[63:48]} : 32'h0);
  wire            needResend =
    (&(reqReg_addr_addr[1:0])) & ~(&(reqReg_addr_addr[10:0])) & ~io_mmioGrant_bits_corrupt
    & (&(shiftedBusData[1:0])) & ~resending;
  wire            _GEN = io_req_ready_0 | _io_mmioAcquire_valid_T;
  wire            _GEN_0 = _GEN | ~refillDone;
  wire [3:0][1:0] _GEN_1 =
    {{2'h0},
     {refillDone ? {~needResend, 1'h1} : state},
     {io_mmioAcquire_ready & io_mmioAcquire_valid_0 ? 2'h2 : state},
     {_reqReg_T ? 2'h1 : state}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      state <= 2'h0;
      reqReg_addr_addr <= 47'h0;
      reqReg_memBackTypeMM <= 1'h0;
      reqReg_memPageTypeNC <= 1'h0;
      resending <= 1'h0;
      respDataReg_0 <= 16'h0;
      respDataReg_1 <= 16'h0;
      respCorruptReg <= 1'h0;
      respDeniedReg <= 1'h0;
    end
    else begin
      state <= _GEN_1[state];
      if (_reqReg_T) begin
        reqReg_addr_addr <= io_req_bits_addr_addr;
        reqReg_memBackTypeMM <= io_req_bits_memBackTypeMM;
        reqReg_memPageTypeNC <= io_req_bits_memPageTypeNC;
      end
      if (_GEN_0) begin
      end
      else
        resending <= needResend;
      if (_GEN | ~refillDone | resending) begin
      end
      else
        respDataReg_0 <= shiftedBusData[15:0];
      if (_GEN_0) begin
      end
      else begin
        respDataReg_1 <= resending ? io_mmioGrant_bits_data[15:0] : shiftedBusData[31:16];
        respCorruptReg <= io_mmioGrant_bits_corrupt;
        respDeniedReg <= io_mmioGrant_bits_denied;
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        state = _RANDOM[2'h0][1:0];
        reqReg_addr_addr = {_RANDOM[2'h0][31:3], _RANDOM[2'h1][17:0]};
        reqReg_memBackTypeMM = _RANDOM[2'h1][18];
        reqReg_memPageTypeNC = _RANDOM[2'h1][19];
        resending = _RANDOM[2'h1][20];
        respDataReg_0 = {_RANDOM[2'h1][31:21], _RANDOM[2'h2][4:0]};
        respDataReg_1 = _RANDOM[2'h2][20:5];
        respCorruptReg = _RANDOM[2'h2][21];
        respDeniedReg = _RANDOM[2'h2][22];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        state = 2'h0;
        reqReg_addr_addr = 47'h0;
        reqReg_memBackTypeMM = 1'h0;
        reqReg_memPageTypeNC = 1'h0;
        resending = 1'h0;
        respDataReg_0 = 16'h0;
        respDataReg_1 = 16'h0;
        respCorruptReg = 1'h0;
        respDeniedReg = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;
  assign io_resp_valid = &state;
  assign io_resp_bits_data = {respDataReg_1, respDataReg_0};
  assign io_resp_bits_corrupt = respCorruptReg;
  assign io_resp_bits_denied = respDeniedReg;
  assign io_resp_bits_needResend =
    (&(reqReg_addr_addr[10:0])) & ~respCorruptReg & (&(respDataReg_0[1:0]));
  assign io_mmioAcquire_valid = io_mmioAcquire_valid_0;
  assign io_mmioAcquire_bits_address =
    {1'h0,
     resending ? 44'(reqReg_addr_addr[45:2] + 44'h1) : reqReg_addr_addr[45:2],
     3'h0};
  assign io_mmioAcquire_bits_user_memPageType_NC = reqReg_memPageTypeNC;
  assign io_mmioAcquire_bits_user_memBackType_MM = reqReg_memBackTypeMM;
  assign io_wfi_wfiSafe = state != 2'h2;
endmodule

