// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module L1PrefetchMonitor_1(
  input        clock,
  input        reset,
  input        io_prefetch_info_loadinfo_0_total_prefetch,
  input        io_prefetch_info_loadinfo_0_pf_late_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_0_pf_source,
  input        io_prefetch_info_loadinfo_0_hit_pf_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_0_hit_source,
  input        io_prefetch_info_loadinfo_1_total_prefetch,
  input        io_prefetch_info_loadinfo_1_pf_late_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_1_pf_source,
  input        io_prefetch_info_loadinfo_1_hit_pf_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_1_hit_source,
  input        io_prefetch_info_loadinfo_2_total_prefetch,
  input        io_prefetch_info_loadinfo_2_pf_late_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_2_pf_source,
  input        io_prefetch_info_loadinfo_2_hit_pf_in_cache,
  input  [2:0] io_prefetch_info_loadinfo_2_hit_source,
  input        io_prefetch_info_missinfo_pf_late_in_mshr,
  input  [2:0] io_prefetch_info_missinfo_pf_source,
  input        io_prefetch_info_maininfo_pf_useless,
  input  [2:0] io_prefetch_info_maininfo_pf_source_useless,
  input        io_prefetch_info_maininfo_hit_pf_in_cache,
  input  [2:0] io_prefetch_info_maininfo_hit_pf_source_in_cache,
  output       io_pf_ctrl_enable,
  output       io_pf_ctrl_confidence
);

  reg         enable;
  reg         confidence;
  reg  [10:0] total_prefetch_cnt;
  reg  [10:0] pf_late_in_cache_cnt;
  reg  [10:0] pf_late_in_mshr_cnt;
  reg  [10:0] hit_pf_in_cache_cnt;
  reg  [10:0] pf_useless_cnt;
  reg  [17:0] back_off_cnt;
  reg  [18:0] low_conf_cnt;
  wire        timely_reset =
    total_prefetch_cnt == 11'h3E8 | pf_late_in_cache_cnt > 11'h3E7;
  wire        validity_reset = 11'(hit_pf_in_cache_cnt + pf_useless_cnt) == 11'h320;
  wire        back_off_reset = back_off_cnt == 18'h186A0;
  wire        conf_reset = low_conf_cnt == 19'h30D40;
  wire        _nack_prefetch_raw_T = io_prefetch_info_loadinfo_0_pf_source == 3'h2;
  wire        _nack_prefetch_raw_T_2 = io_prefetch_info_loadinfo_1_pf_source == 3'h2;
  wire        _nack_prefetch_raw_T_4 = io_prefetch_info_loadinfo_2_pf_source == 3'h2;
  wire        trigger_late_miss = timely_reset & pf_late_in_mshr_cnt > 11'hC7;
  wire        trigger_disable = validity_reset & pf_useless_cnt > 11'h2BB;
  wire        _enable_T = back_off_reset | enable;
  wire        _confidence_T = conf_reset | confidence;
  wire        _GEN = timely_reset & pf_late_in_cache_cnt > 11'h383 | trigger_disable;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      enable <= 1'h1;
      confidence <= 1'h1;
      total_prefetch_cnt <= 11'h0;
      pf_late_in_cache_cnt <= 11'h0;
      pf_late_in_mshr_cnt <= 11'h0;
      hit_pf_in_cache_cnt <= 11'h0;
      pf_useless_cnt <= 11'h0;
      back_off_cnt <= 18'h0;
      low_conf_cnt <= 19'h0;
    end
    else begin
      enable <= trigger_late_miss ? ~trigger_disable & _enable_T : ~_GEN & _enable_T;
      confidence <=
        trigger_late_miss ? ~trigger_disable & _confidence_T : ~_GEN & _confidence_T;
      total_prefetch_cnt <=
        timely_reset
          ? 11'h0
          : 11'(total_prefetch_cnt
                + {10'h0,
                   io_prefetch_info_loadinfo_0_total_prefetch & _nack_prefetch_raw_T
                     | io_prefetch_info_loadinfo_1_total_prefetch & _nack_prefetch_raw_T_2
                     | io_prefetch_info_loadinfo_2_total_prefetch
                     & _nack_prefetch_raw_T_4});
      pf_late_in_cache_cnt <=
        timely_reset
          ? 11'h0
          : 11'(pf_late_in_cache_cnt
                + {10'h0,
                   io_prefetch_info_loadinfo_0_pf_late_in_cache & _nack_prefetch_raw_T
                     | io_prefetch_info_loadinfo_1_pf_late_in_cache
                     & _nack_prefetch_raw_T_2
                     | io_prefetch_info_loadinfo_2_pf_late_in_cache
                     & _nack_prefetch_raw_T_4});
      pf_late_in_mshr_cnt <=
        timely_reset
          ? 11'h0
          : 11'(pf_late_in_mshr_cnt
                + {10'h0,
                   io_prefetch_info_missinfo_pf_late_in_mshr
                     & io_prefetch_info_missinfo_pf_source == 3'h2});
      hit_pf_in_cache_cnt <=
        validity_reset
          ? 11'h0
          : 11'(hit_pf_in_cache_cnt
                + {8'h0,
                   3'({1'h0,
                       2'({1'h0,
                           io_prefetch_info_loadinfo_0_hit_pf_in_cache
                             & io_prefetch_info_loadinfo_0_hit_source == 3'h2}
                          + {1'h0,
                             io_prefetch_info_loadinfo_1_hit_pf_in_cache
                               & io_prefetch_info_loadinfo_1_hit_source == 3'h2})}
                      + {1'h0,
                         2'({1'h0,
                             io_prefetch_info_loadinfo_2_hit_pf_in_cache
                               & io_prefetch_info_loadinfo_2_hit_source == 3'h2}
                            + {1'h0,
                               io_prefetch_info_maininfo_hit_pf_in_cache
                                 & io_prefetch_info_maininfo_hit_pf_source_in_cache == 3'h2})})});
      pf_useless_cnt <=
        validity_reset
          ? 11'h0
          : 11'(pf_useless_cnt
                + {10'h0,
                   io_prefetch_info_maininfo_pf_useless
                     & io_prefetch_info_maininfo_pf_source_useless == 3'h2});
      back_off_cnt <= back_off_reset ? 18'h0 : 18'(back_off_cnt + {17'h0, ~enable});
      low_conf_cnt <= conf_reset ? 19'h0 : 19'(low_conf_cnt + {18'h0, ~confidence});
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        enable = _RANDOM[2'h0][13];
        confidence = _RANDOM[2'h0][14];
        total_prefetch_cnt = _RANDOM[2'h0][25:15];
        pf_late_in_cache_cnt = {_RANDOM[2'h0][31:26], _RANDOM[2'h1][4:0]};
        pf_late_in_mshr_cnt = _RANDOM[2'h1][15:5];
        hit_pf_in_cache_cnt = _RANDOM[2'h1][26:16];
        pf_useless_cnt = {_RANDOM[2'h1][31:27], _RANDOM[2'h2][5:0]};
        back_off_cnt = _RANDOM[2'h2][23:6];
        low_conf_cnt = {_RANDOM[2'h2][31:24], _RANDOM[2'h3][10:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        enable = 1'h1;
        confidence = 1'h1;
        total_prefetch_cnt = 11'h0;
        pf_late_in_cache_cnt = 11'h0;
        pf_late_in_mshr_cnt = 11'h0;
        hit_pf_in_cache_cnt = 11'h0;
        pf_useless_cnt = 11'h0;
        back_off_cnt = 18'h0;
        low_conf_cnt = 19'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_pf_ctrl_enable = enable;
  assign io_pf_ctrl_confidence = confidence;
endmodule

