// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NCBUpstreamTXDAT_1(
  input          clock,
  input          reset,
  output         io_txdat_flitpend,
  output         io_txdat_flitv,
  output [3:0]   io_txdat_flit_QoS,
  output [10:0]  io_txdat_flit_TgtID,
  output [10:0]  io_txdat_flit_SrcID,
  output [11:0]  io_txdat_flit_TxnID,
  output [10:0]  io_txdat_flit_HomeNID,
  output [3:0]   io_txdat_flit_Opcode,
  output [1:0]   io_txdat_flit_RespErr,
  output [2:0]   io_txdat_flit_CBusy,
  output [1:0]   io_txdat_flit_CCID,
  output [1:0]   io_txdat_flit_DataID,
  output [1:0]   io_txdat_flit_TagOp,
  output [7:0]   io_txdat_flit_Tag,
  output [1:0]   io_txdat_flit_TU,
  output         io_txdat_flit_TraceTag,
  output [3:0]   io_txdat_flit_RSVDC,
  output [255:0] io_txdat_flit_Data,
  output [31:0]  io_txdat_flit_DataCheck,
  input          io_txdat_lcrdv,
  input          io_linkState_stop,
  input          io_linkState_activate,
  input          io_linkState_run,
  input          io_linkState_deactivate,
  output         io_ageSelect_in_0,
  output         io_ageSelect_in_1,
  output         io_ageSelect_in_2,
  output         io_ageSelect_in_3,
  output         io_ageSelect_in_4,
  output         io_ageSelect_in_5,
  output         io_ageSelect_in_6,
  output         io_ageSelect_in_7,
  output         io_ageSelect_in_8,
  output         io_ageSelect_in_9,
  output         io_ageSelect_in_10,
  output         io_ageSelect_in_11,
  output         io_ageSelect_in_12,
  output         io_ageSelect_in_13,
  output         io_ageSelect_in_14,
  output         io_ageSelect_in_15,
  output         io_ageSelect_in_16,
  output         io_ageSelect_in_17,
  output         io_ageSelect_in_18,
  output         io_ageSelect_in_19,
  output         io_ageSelect_in_20,
  output         io_ageSelect_in_21,
  output         io_ageSelect_in_22,
  output         io_ageSelect_in_23,
  output         io_ageSelect_in_24,
  output         io_ageSelect_in_25,
  output         io_ageSelect_in_26,
  output         io_ageSelect_in_27,
  output         io_ageSelect_in_28,
  output         io_ageSelect_in_29,
  output         io_ageSelect_in_30,
  output         io_ageSelect_in_31,
  input          io_ageSelect_out_0,
  input          io_ageSelect_out_1,
  input          io_ageSelect_out_2,
  input          io_ageSelect_out_3,
  input          io_ageSelect_out_4,
  input          io_ageSelect_out_5,
  input          io_ageSelect_out_6,
  input          io_ageSelect_out_7,
  input          io_ageSelect_out_8,
  input          io_ageSelect_out_9,
  input          io_ageSelect_out_10,
  input          io_ageSelect_out_11,
  input          io_ageSelect_out_12,
  input          io_ageSelect_out_13,
  input          io_ageSelect_out_14,
  input          io_ageSelect_out_15,
  input          io_ageSelect_out_16,
  input          io_ageSelect_out_17,
  input          io_ageSelect_out_18,
  input          io_ageSelect_out_19,
  input          io_ageSelect_out_20,
  input          io_ageSelect_out_21,
  input          io_ageSelect_out_22,
  input          io_ageSelect_out_23,
  input          io_ageSelect_out_24,
  input          io_ageSelect_out_25,
  input          io_ageSelect_out_26,
  input          io_ageSelect_out_27,
  input          io_ageSelect_out_28,
  input          io_ageSelect_out_29,
  input          io_ageSelect_out_30,
  input          io_ageSelect_out_31,
  input          io_queue_opValid_valid_0,
  input          io_queue_opValid_valid_1,
  input          io_queue_opValid_valid_2,
  input          io_queue_opValid_valid_3,
  input          io_queue_opValid_valid_4,
  input          io_queue_opValid_valid_5,
  input          io_queue_opValid_valid_6,
  input          io_queue_opValid_valid_7,
  input          io_queue_opValid_valid_8,
  input          io_queue_opValid_valid_9,
  input          io_queue_opValid_valid_10,
  input          io_queue_opValid_valid_11,
  input          io_queue_opValid_valid_12,
  input          io_queue_opValid_valid_13,
  input          io_queue_opValid_valid_14,
  input          io_queue_opValid_valid_15,
  input          io_queue_opValid_valid_16,
  input          io_queue_opValid_valid_17,
  input          io_queue_opValid_valid_18,
  input          io_queue_opValid_valid_19,
  input          io_queue_opValid_valid_20,
  input          io_queue_opValid_valid_21,
  input          io_queue_opValid_valid_22,
  input          io_queue_opValid_valid_23,
  input          io_queue_opValid_valid_24,
  input          io_queue_opValid_valid_25,
  input          io_queue_opValid_valid_26,
  input          io_queue_opValid_valid_27,
  input          io_queue_opValid_valid_28,
  input          io_queue_opValid_valid_29,
  input          io_queue_opValid_valid_30,
  input          io_queue_opValid_valid_31,
  input          io_queue_opValid_bits_Critical_0_0,
  input          io_queue_opValid_bits_Critical_0_1,
  input          io_queue_opValid_bits_Critical_1_0,
  input          io_queue_opValid_bits_Critical_1_1,
  input          io_queue_opValid_bits_Critical_2_0,
  input          io_queue_opValid_bits_Critical_2_1,
  input          io_queue_opValid_bits_Critical_3_0,
  input          io_queue_opValid_bits_Critical_3_1,
  input          io_queue_opValid_bits_Critical_4_0,
  input          io_queue_opValid_bits_Critical_4_1,
  input          io_queue_opValid_bits_Critical_5_0,
  input          io_queue_opValid_bits_Critical_5_1,
  input          io_queue_opValid_bits_Critical_6_0,
  input          io_queue_opValid_bits_Critical_6_1,
  input          io_queue_opValid_bits_Critical_7_0,
  input          io_queue_opValid_bits_Critical_7_1,
  input          io_queue_opValid_bits_Critical_8_0,
  input          io_queue_opValid_bits_Critical_8_1,
  input          io_queue_opValid_bits_Critical_9_0,
  input          io_queue_opValid_bits_Critical_9_1,
  input          io_queue_opValid_bits_Critical_10_0,
  input          io_queue_opValid_bits_Critical_10_1,
  input          io_queue_opValid_bits_Critical_11_0,
  input          io_queue_opValid_bits_Critical_11_1,
  input          io_queue_opValid_bits_Critical_12_0,
  input          io_queue_opValid_bits_Critical_12_1,
  input          io_queue_opValid_bits_Critical_13_0,
  input          io_queue_opValid_bits_Critical_13_1,
  input          io_queue_opValid_bits_Critical_14_0,
  input          io_queue_opValid_bits_Critical_14_1,
  input          io_queue_opValid_bits_Critical_15_0,
  input          io_queue_opValid_bits_Critical_15_1,
  input          io_queue_opValid_bits_Critical_16_0,
  input          io_queue_opValid_bits_Critical_16_1,
  input          io_queue_opValid_bits_Critical_17_0,
  input          io_queue_opValid_bits_Critical_17_1,
  input          io_queue_opValid_bits_Critical_18_0,
  input          io_queue_opValid_bits_Critical_18_1,
  input          io_queue_opValid_bits_Critical_19_0,
  input          io_queue_opValid_bits_Critical_19_1,
  input          io_queue_opValid_bits_Critical_20_0,
  input          io_queue_opValid_bits_Critical_20_1,
  input          io_queue_opValid_bits_Critical_21_0,
  input          io_queue_opValid_bits_Critical_21_1,
  input          io_queue_opValid_bits_Critical_22_0,
  input          io_queue_opValid_bits_Critical_22_1,
  input          io_queue_opValid_bits_Critical_23_0,
  input          io_queue_opValid_bits_Critical_23_1,
  input          io_queue_opValid_bits_Critical_24_0,
  input          io_queue_opValid_bits_Critical_24_1,
  input          io_queue_opValid_bits_Critical_25_0,
  input          io_queue_opValid_bits_Critical_25_1,
  input          io_queue_opValid_bits_Critical_26_0,
  input          io_queue_opValid_bits_Critical_26_1,
  input          io_queue_opValid_bits_Critical_27_0,
  input          io_queue_opValid_bits_Critical_27_1,
  input          io_queue_opValid_bits_Critical_28_0,
  input          io_queue_opValid_bits_Critical_28_1,
  input          io_queue_opValid_bits_Critical_29_0,
  input          io_queue_opValid_bits_Critical_29_1,
  input          io_queue_opValid_bits_Critical_30_0,
  input          io_queue_opValid_bits_Critical_30_1,
  input          io_queue_opValid_bits_Critical_31_0,
  input          io_queue_opValid_bits_Critical_31_1,
  output         io_queue_opRead_strb_0,
  output         io_queue_opRead_strb_1,
  output         io_queue_opRead_strb_2,
  output         io_queue_opRead_strb_3,
  output         io_queue_opRead_strb_4,
  output         io_queue_opRead_strb_5,
  output         io_queue_opRead_strb_6,
  output         io_queue_opRead_strb_7,
  output         io_queue_opRead_strb_8,
  output         io_queue_opRead_strb_9,
  output         io_queue_opRead_strb_10,
  output         io_queue_opRead_strb_11,
  output         io_queue_opRead_strb_12,
  output         io_queue_opRead_strb_13,
  output         io_queue_opRead_strb_14,
  output         io_queue_opRead_strb_15,
  output         io_queue_opRead_strb_16,
  output         io_queue_opRead_strb_17,
  output         io_queue_opRead_strb_18,
  output         io_queue_opRead_strb_19,
  output         io_queue_opRead_strb_20,
  output         io_queue_opRead_strb_21,
  output         io_queue_opRead_strb_22,
  output         io_queue_opRead_strb_23,
  output         io_queue_opRead_strb_24,
  output         io_queue_opRead_strb_25,
  output         io_queue_opRead_strb_26,
  output         io_queue_opRead_strb_27,
  output         io_queue_opRead_strb_28,
  output         io_queue_opRead_strb_29,
  output         io_queue_opRead_strb_30,
  output         io_queue_opRead_strb_31,
  input          io_queue_opRead_bits_CompData_valid,
  input          io_queue_opRead_bits_CompData_sep,
  output         io_queue_opDone_strb_0,
  output         io_queue_opDone_strb_1,
  output         io_queue_opDone_strb_2,
  output         io_queue_opDone_strb_3,
  output         io_queue_opDone_strb_4,
  output         io_queue_opDone_strb_5,
  output         io_queue_opDone_strb_6,
  output         io_queue_opDone_strb_7,
  output         io_queue_opDone_strb_8,
  output         io_queue_opDone_strb_9,
  output         io_queue_opDone_strb_10,
  output         io_queue_opDone_strb_11,
  output         io_queue_opDone_strb_12,
  output         io_queue_opDone_strb_13,
  output         io_queue_opDone_strb_14,
  output         io_queue_opDone_strb_15,
  output         io_queue_opDone_strb_16,
  output         io_queue_opDone_strb_17,
  output         io_queue_opDone_strb_18,
  output         io_queue_opDone_strb_19,
  output         io_queue_opDone_strb_20,
  output         io_queue_opDone_strb_21,
  output         io_queue_opDone_strb_22,
  output         io_queue_opDone_strb_23,
  output         io_queue_opDone_strb_24,
  output         io_queue_opDone_strb_25,
  output         io_queue_opDone_strb_26,
  output         io_queue_opDone_strb_27,
  output         io_queue_opDone_strb_28,
  output         io_queue_opDone_strb_29,
  output         io_queue_opDone_strb_30,
  output         io_queue_opDone_strb_31,
  output         io_queue_opDone_bits_CompData,
  output         io_queue_infoRead_strb_0,
  output         io_queue_infoRead_strb_1,
  output         io_queue_infoRead_strb_2,
  output         io_queue_infoRead_strb_3,
  output         io_queue_infoRead_strb_4,
  output         io_queue_infoRead_strb_5,
  output         io_queue_infoRead_strb_6,
  output         io_queue_infoRead_strb_7,
  output         io_queue_infoRead_strb_8,
  output         io_queue_infoRead_strb_9,
  output         io_queue_infoRead_strb_10,
  output         io_queue_infoRead_strb_11,
  output         io_queue_infoRead_strb_12,
  output         io_queue_infoRead_strb_13,
  output         io_queue_infoRead_strb_14,
  output         io_queue_infoRead_strb_15,
  output         io_queue_infoRead_strb_16,
  output         io_queue_infoRead_strb_17,
  output         io_queue_infoRead_strb_18,
  output         io_queue_infoRead_strb_19,
  output         io_queue_infoRead_strb_20,
  output         io_queue_infoRead_strb_21,
  output         io_queue_infoRead_strb_22,
  output         io_queue_infoRead_strb_23,
  output         io_queue_infoRead_strb_24,
  output         io_queue_infoRead_strb_25,
  output         io_queue_infoRead_strb_26,
  output         io_queue_infoRead_strb_27,
  output         io_queue_infoRead_strb_28,
  output         io_queue_infoRead_strb_29,
  output         io_queue_infoRead_strb_30,
  output         io_queue_infoRead_strb_31,
  input  [3:0]   io_queue_infoRead_bits_QoS,
  input  [10:0]  io_queue_infoRead_bits_TgtID,
  input  [10:0]  io_queue_infoRead_bits_SrcID,
  input  [11:0]  io_queue_infoRead_bits_TxnID,
  input          io_queue_infoRead_bits_TraceTag,
  output         io_queue_operandRead_strb_0,
  output         io_queue_operandRead_strb_1,
  output         io_queue_operandRead_strb_2,
  output         io_queue_operandRead_strb_3,
  output         io_queue_operandRead_strb_4,
  output         io_queue_operandRead_strb_5,
  output         io_queue_operandRead_strb_6,
  output         io_queue_operandRead_strb_7,
  output         io_queue_operandRead_strb_8,
  output         io_queue_operandRead_strb_9,
  output         io_queue_operandRead_strb_10,
  output         io_queue_operandRead_strb_11,
  output         io_queue_operandRead_strb_12,
  output         io_queue_operandRead_strb_13,
  output         io_queue_operandRead_strb_14,
  output         io_queue_operandRead_strb_15,
  output         io_queue_operandRead_strb_16,
  output         io_queue_operandRead_strb_17,
  output         io_queue_operandRead_strb_18,
  output         io_queue_operandRead_strb_19,
  output         io_queue_operandRead_strb_20,
  output         io_queue_operandRead_strb_21,
  output         io_queue_operandRead_strb_22,
  output         io_queue_operandRead_strb_23,
  output         io_queue_operandRead_strb_24,
  output         io_queue_operandRead_strb_25,
  output         io_queue_operandRead_strb_26,
  output         io_queue_operandRead_strb_27,
  output         io_queue_operandRead_strb_28,
  output         io_queue_operandRead_strb_29,
  output         io_queue_operandRead_strb_30,
  output         io_queue_operandRead_strb_31,
  input  [47:0]  io_queue_operandRead_bits_Addr,
  input  [1:0]   io_queue_operandRead_bits_ReadRespErr,
  input          io_queue_operandRead_bits_Critical_0,
  input          io_queue_operandRead_bits_Critical_1,
  input          io_queue_operandRead_bits_Count,
  output         io_queue_operandWrite_strb_0,
  output         io_queue_operandWrite_strb_1,
  output         io_queue_operandWrite_strb_2,
  output         io_queue_operandWrite_strb_3,
  output         io_queue_operandWrite_strb_4,
  output         io_queue_operandWrite_strb_5,
  output         io_queue_operandWrite_strb_6,
  output         io_queue_operandWrite_strb_7,
  output         io_queue_operandWrite_strb_8,
  output         io_queue_operandWrite_strb_9,
  output         io_queue_operandWrite_strb_10,
  output         io_queue_operandWrite_strb_11,
  output         io_queue_operandWrite_strb_12,
  output         io_queue_operandWrite_strb_13,
  output         io_queue_operandWrite_strb_14,
  output         io_queue_operandWrite_strb_15,
  output         io_queue_operandWrite_strb_16,
  output         io_queue_operandWrite_strb_17,
  output         io_queue_operandWrite_strb_18,
  output         io_queue_operandWrite_strb_19,
  output         io_queue_operandWrite_strb_20,
  output         io_queue_operandWrite_strb_21,
  output         io_queue_operandWrite_strb_22,
  output         io_queue_operandWrite_strb_23,
  output         io_queue_operandWrite_strb_24,
  output         io_queue_operandWrite_strb_25,
  output         io_queue_operandWrite_strb_26,
  output         io_queue_operandWrite_strb_27,
  output         io_queue_operandWrite_strb_28,
  output         io_queue_operandWrite_strb_29,
  output         io_queue_operandWrite_strb_30,
  output         io_queue_operandWrite_strb_31,
  output         io_queue_operandWrite_bits_Critical_0,
  output         io_queue_operandWrite_bits_Critical_1,
  output         io_queue_operandWrite_bits_Count,
  output         io_payloadRead_en,
  output         io_payloadRead_strb_0,
  output         io_payloadRead_strb_1,
  output         io_payloadRead_strb_2,
  output         io_payloadRead_strb_3,
  output         io_payloadRead_strb_4,
  output         io_payloadRead_strb_5,
  output         io_payloadRead_strb_6,
  output         io_payloadRead_strb_7,
  output         io_payloadRead_strb_8,
  output         io_payloadRead_strb_9,
  output         io_payloadRead_strb_10,
  output         io_payloadRead_strb_11,
  output         io_payloadRead_strb_12,
  output         io_payloadRead_strb_13,
  output         io_payloadRead_strb_14,
  output         io_payloadRead_strb_15,
  output         io_payloadRead_strb_16,
  output         io_payloadRead_strb_17,
  output         io_payloadRead_strb_18,
  output         io_payloadRead_strb_19,
  output         io_payloadRead_strb_20,
  output         io_payloadRead_strb_21,
  output         io_payloadRead_strb_22,
  output         io_payloadRead_strb_23,
  output         io_payloadRead_strb_24,
  output         io_payloadRead_strb_25,
  output         io_payloadRead_strb_26,
  output         io_payloadRead_strb_27,
  output         io_payloadRead_strb_28,
  output         io_payloadRead_strb_29,
  output         io_payloadRead_strb_30,
  output         io_payloadRead_strb_31,
  output         io_payloadRead_index_0,
  output         io_payloadRead_index_1,
  input  [255:0] io_payloadRead_data,
  input          io_payloadValid_0_0,
  input          io_payloadValid_0_1,
  input          io_payloadValid_1_0,
  input          io_payloadValid_1_1,
  input          io_payloadValid_2_0,
  input          io_payloadValid_2_1,
  input          io_payloadValid_3_0,
  input          io_payloadValid_3_1,
  input          io_payloadValid_4_0,
  input          io_payloadValid_4_1,
  input          io_payloadValid_5_0,
  input          io_payloadValid_5_1,
  input          io_payloadValid_6_0,
  input          io_payloadValid_6_1,
  input          io_payloadValid_7_0,
  input          io_payloadValid_7_1,
  input          io_payloadValid_8_0,
  input          io_payloadValid_8_1,
  input          io_payloadValid_9_0,
  input          io_payloadValid_9_1,
  input          io_payloadValid_10_0,
  input          io_payloadValid_10_1,
  input          io_payloadValid_11_0,
  input          io_payloadValid_11_1,
  input          io_payloadValid_12_0,
  input          io_payloadValid_12_1,
  input          io_payloadValid_13_0,
  input          io_payloadValid_13_1,
  input          io_payloadValid_14_0,
  input          io_payloadValid_14_1,
  input          io_payloadValid_15_0,
  input          io_payloadValid_15_1,
  input          io_payloadValid_16_0,
  input          io_payloadValid_16_1,
  input          io_payloadValid_17_0,
  input          io_payloadValid_17_1,
  input          io_payloadValid_18_0,
  input          io_payloadValid_18_1,
  input          io_payloadValid_19_0,
  input          io_payloadValid_19_1,
  input          io_payloadValid_20_0,
  input          io_payloadValid_20_1,
  input          io_payloadValid_21_0,
  input          io_payloadValid_21_1,
  input          io_payloadValid_22_0,
  input          io_payloadValid_22_1,
  input          io_payloadValid_23_0,
  input          io_payloadValid_23_1,
  input          io_payloadValid_24_0,
  input          io_payloadValid_24_1,
  input          io_payloadValid_25_0,
  input          io_payloadValid_25_1,
  input          io_payloadValid_26_0,
  input          io_payloadValid_26_1,
  input          io_payloadValid_27_0,
  input          io_payloadValid_27_1,
  input          io_payloadValid_28_0,
  input          io_payloadValid_28_1,
  input          io_payloadValid_29_0,
  input          io_payloadValid_29_1,
  input          io_payloadValid_30_0,
  input          io_payloadValid_30_1,
  input          io_payloadValid_31_0,
  input          io_payloadValid_31_1,
  output         debug_linkCredit_LinkActiveStateNotOneHot,
  output         debug_linkCredit_LinkCreditConsumeOutOfRun,
  output         debug_linkCredit_LinkCreditReturnOutOfDeactivate,
  output         debug_linkCredit_LinkCreditValidWhenLinkStop,
  output         debug_linkCredit_LinkCreditOverflow,
  output         debug_linkCredit_LinkCreditUnderflow
);

  wire         _uLinkCredit_io_linkCreditAvailable;
  reg          regTXDATFlitPend_flitv;
  reg  [3:0]   regTXDATFlitPend_flit_QoS;
  reg  [10:0]  regTXDATFlitPend_flit_TgtID;
  reg  [10:0]  regTXDATFlitPend_flit_SrcID;
  reg  [11:0]  regTXDATFlitPend_flit_TxnID;
  reg  [10:0]  regTXDATFlitPend_flit_HomeNID;
  reg  [3:0]   regTXDATFlitPend_flit_Opcode;
  reg  [1:0]   regTXDATFlitPend_flit_RespErr;
  reg  [1:0]   regTXDATFlitPend_flit_CCID;
  reg  [1:0]   regTXDATFlitPend_flit_DataID;
  reg          regTXDATFlitPend_flit_TraceTag;
  reg  [255:0] regTXDATFlitPend_flit_Data;
  reg  [31:0]  regTXDATFlitPend_flit_DataCheck;
  reg          regTXDAT_flitv;
  reg  [3:0]   regTXDAT_flit_QoS;
  reg  [10:0]  regTXDAT_flit_TgtID;
  reg  [10:0]  regTXDAT_flit_SrcID;
  reg  [11:0]  regTXDAT_flit_TxnID;
  reg  [10:0]  regTXDAT_flit_HomeNID;
  reg  [3:0]   regTXDAT_flit_Opcode;
  reg  [1:0]   regTXDAT_flit_RespErr;
  reg  [1:0]   regTXDAT_flit_CCID;
  reg  [1:0]   regTXDAT_flit_DataID;
  reg          regTXDAT_flit_TraceTag;
  reg  [255:0] regTXDAT_flit_Data;
  reg  [31:0]  regTXDAT_flit_DataCheck;
  reg          regTXDAT_lcrdv;
  wire         logicLCrdReturn =
    io_linkState_deactivate & _uLinkCredit_io_linkCreditAvailable;
  wire         logicOpDoneValid =
    _uLinkCredit_io_linkCreditAvailable
    & (|{io_ageSelect_out_31,
         io_ageSelect_out_30,
         io_ageSelect_out_29,
         io_ageSelect_out_28,
         io_ageSelect_out_27,
         io_ageSelect_out_26,
         io_ageSelect_out_25,
         io_ageSelect_out_24,
         io_ageSelect_out_23,
         io_ageSelect_out_22,
         io_ageSelect_out_21,
         io_ageSelect_out_20,
         io_ageSelect_out_19,
         io_ageSelect_out_18,
         io_ageSelect_out_17,
         io_ageSelect_out_16,
         io_ageSelect_out_15,
         io_ageSelect_out_14,
         io_ageSelect_out_13,
         io_ageSelect_out_12,
         io_ageSelect_out_11,
         io_ageSelect_out_10,
         io_ageSelect_out_9,
         io_ageSelect_out_8,
         io_ageSelect_out_7,
         io_ageSelect_out_6,
         io_ageSelect_out_5,
         io_ageSelect_out_4,
         io_ageSelect_out_3,
         io_ageSelect_out_2,
         io_ageSelect_out_1,
         io_ageSelect_out_0});
  wire         logicSelectedGo_0 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_0;
  wire         logicSelectedGo_1 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_1;
  wire         logicSelectedGo_2 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_2;
  wire         logicSelectedGo_3 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_3;
  wire         logicSelectedGo_4 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_4;
  wire         logicSelectedGo_5 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_5;
  wire         logicSelectedGo_6 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_6;
  wire         logicSelectedGo_7 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_7;
  wire         logicSelectedGo_8 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_8;
  wire         logicSelectedGo_9 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_9;
  wire         logicSelectedGo_10 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_10;
  wire         logicSelectedGo_11 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_11;
  wire         logicSelectedGo_12 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_12;
  wire         logicSelectedGo_13 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_13;
  wire         logicSelectedGo_14 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_14;
  wire         logicSelectedGo_15 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_15;
  wire         logicSelectedGo_16 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_16;
  wire         logicSelectedGo_17 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_17;
  wire         logicSelectedGo_18 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_18;
  wire         logicSelectedGo_19 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_19;
  wire         logicSelectedGo_20 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_20;
  wire         logicSelectedGo_21 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_21;
  wire         logicSelectedGo_22 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_22;
  wire         logicSelectedGo_23 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_23;
  wire         logicSelectedGo_24 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_24;
  wire         logicSelectedGo_25 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_25;
  wire         logicSelectedGo_26 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_26;
  wire         logicSelectedGo_27 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_27;
  wire         logicSelectedGo_28 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_28;
  wire         logicSelectedGo_29 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_29;
  wire         logicSelectedGo_30 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_30;
  wire         logicSelectedGo_31 =
    _uLinkCredit_io_linkCreditAvailable & io_ageSelect_out_31;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      regTXDATFlitPend_flitv <= 1'h0;
      regTXDAT_flitv <= 1'h0;
      regTXDAT_lcrdv <= 1'h0;
    end
    else begin
      regTXDATFlitPend_flitv <= logicOpDoneValid | logicLCrdReturn;
      regTXDAT_flitv <= regTXDATFlitPend_flitv;
      regTXDAT_lcrdv <= io_txdat_lcrdv;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (logicOpDoneValid) begin
      regTXDATFlitPend_flit_QoS <= io_queue_infoRead_bits_QoS;
      regTXDATFlitPend_flit_TgtID <= io_queue_infoRead_bits_SrcID;
      regTXDATFlitPend_flit_SrcID <= io_queue_infoRead_bits_TgtID;
      regTXDATFlitPend_flit_TxnID <= io_queue_infoRead_bits_TxnID;
      regTXDATFlitPend_flit_HomeNID <= io_queue_infoRead_bits_SrcID;
      regTXDATFlitPend_flit_Opcode <=
        io_linkState_deactivate ? 4'h0 : io_queue_opRead_bits_CompData_sep ? 4'hB : 4'h4;
      regTXDATFlitPend_flit_RespErr <= io_queue_operandRead_bits_ReadRespErr;
      regTXDATFlitPend_flit_CCID <= io_queue_operandRead_bits_Addr[5:4];
      regTXDATFlitPend_flit_DataID <= {io_queue_operandRead_bits_Critical_1, 1'h0};
      regTXDATFlitPend_flit_TraceTag <= io_queue_infoRead_bits_TraceTag;
      regTXDATFlitPend_flit_Data <= io_payloadRead_data;
      regTXDATFlitPend_flit_DataCheck <=
        {~(^(io_payloadRead_data[255:248])),
         ~(^(io_payloadRead_data[247:240])),
         ~(^(io_payloadRead_data[239:232])),
         ~(^(io_payloadRead_data[231:224])),
         ~(^(io_payloadRead_data[223:216])),
         ~(^(io_payloadRead_data[215:208])),
         ~(^(io_payloadRead_data[207:200])),
         ~(^(io_payloadRead_data[199:192])),
         ~(^(io_payloadRead_data[191:184])),
         ~(^(io_payloadRead_data[183:176])),
         ~(^(io_payloadRead_data[175:168])),
         ~(^(io_payloadRead_data[167:160])),
         ~(^(io_payloadRead_data[159:152])),
         ~(^(io_payloadRead_data[151:144])),
         ~(^(io_payloadRead_data[143:136])),
         ~(^(io_payloadRead_data[135:128])),
         ~(^(io_payloadRead_data[127:120])),
         ~(^(io_payloadRead_data[119:112])),
         ~(^(io_payloadRead_data[111:104])),
         ~(^(io_payloadRead_data[103:96])),
         ~(^(io_payloadRead_data[95:88])),
         ~(^(io_payloadRead_data[87:80])),
         ~(^(io_payloadRead_data[79:72])),
         ~(^(io_payloadRead_data[71:64])),
         ~(^(io_payloadRead_data[63:56])),
         ~(^(io_payloadRead_data[55:48])),
         ~(^(io_payloadRead_data[47:40])),
         ~(^(io_payloadRead_data[39:32])),
         ~(^(io_payloadRead_data[31:24])),
         ~(^(io_payloadRead_data[23:16])),
         ~(^(io_payloadRead_data[15:8])),
         ~(^(io_payloadRead_data[7:0]))};
    end
    if (regTXDATFlitPend_flitv) begin
      regTXDAT_flit_QoS <= regTXDATFlitPend_flit_QoS;
      regTXDAT_flit_TgtID <= regTXDATFlitPend_flit_TgtID;
      regTXDAT_flit_SrcID <= regTXDATFlitPend_flit_SrcID;
      regTXDAT_flit_TxnID <= regTXDATFlitPend_flit_TxnID;
      regTXDAT_flit_HomeNID <= regTXDATFlitPend_flit_HomeNID;
      regTXDAT_flit_Opcode <= regTXDATFlitPend_flit_Opcode;
      regTXDAT_flit_RespErr <= regTXDATFlitPend_flit_RespErr;
      regTXDAT_flit_CCID <= regTXDATFlitPend_flit_CCID;
      regTXDAT_flit_DataID <= regTXDATFlitPend_flit_DataID;
      regTXDAT_flit_TraceTag <= regTXDATFlitPend_flit_TraceTag;
      regTXDAT_flit_Data <= regTXDATFlitPend_flit_Data;
      regTXDAT_flit_DataCheck <= regTXDATFlitPend_flit_DataCheck;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:26];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h1B; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        regTXDATFlitPend_flitv = _RANDOM[5'h0][1];
        regTXDATFlitPend_flit_QoS = _RANDOM[5'h0][5:2];
        regTXDATFlitPend_flit_TgtID = _RANDOM[5'h0][16:6];
        regTXDATFlitPend_flit_SrcID = _RANDOM[5'h0][27:17];
        regTXDATFlitPend_flit_TxnID = {_RANDOM[5'h0][31:28], _RANDOM[5'h1][7:0]};
        regTXDATFlitPend_flit_HomeNID = _RANDOM[5'h1][18:8];
        regTXDATFlitPend_flit_Opcode = _RANDOM[5'h1][22:19];
        regTXDATFlitPend_flit_RespErr = _RANDOM[5'h1][24:23];
        regTXDATFlitPend_flit_CCID = _RANDOM[5'h2][16:15];
        regTXDATFlitPend_flit_DataID = _RANDOM[5'h2][18:17];
        regTXDATFlitPend_flit_TraceTag = _RANDOM[5'h2][31];
        regTXDATFlitPend_flit_Data =
          {_RANDOM[5'h4][31:4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7],
           _RANDOM[5'h8],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC][3:0]};
        regTXDATFlitPend_flit_DataCheck = {_RANDOM[5'hC][31:4], _RANDOM[5'hD][3:0]};
        regTXDAT_flitv = _RANDOM[5'hD][10];
        regTXDAT_flit_QoS = _RANDOM[5'hD][14:11];
        regTXDAT_flit_TgtID = _RANDOM[5'hD][25:15];
        regTXDAT_flit_SrcID = {_RANDOM[5'hD][31:26], _RANDOM[5'hE][4:0]};
        regTXDAT_flit_TxnID = _RANDOM[5'hE][16:5];
        regTXDAT_flit_HomeNID = _RANDOM[5'hE][27:17];
        regTXDAT_flit_Opcode = _RANDOM[5'hE][31:28];
        regTXDAT_flit_RespErr = _RANDOM[5'hF][1:0];
        regTXDAT_flit_CCID = _RANDOM[5'hF][25:24];
        regTXDAT_flit_DataID = _RANDOM[5'hF][27:26];
        regTXDAT_flit_TraceTag = _RANDOM[5'h10][8];
        regTXDAT_flit_Data =
          {_RANDOM[5'h11][31:13],
           _RANDOM[5'h12],
           _RANDOM[5'h13],
           _RANDOM[5'h14],
           _RANDOM[5'h15],
           _RANDOM[5'h16],
           _RANDOM[5'h17],
           _RANDOM[5'h18],
           _RANDOM[5'h19][12:0]};
        regTXDAT_flit_DataCheck = {_RANDOM[5'h19][31:13], _RANDOM[5'h1A][12:0]};
        regTXDAT_lcrdv = _RANDOM[5'h1A][17];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        regTXDATFlitPend_flitv = 1'h0;
        regTXDAT_flitv = 1'h0;
        regTXDAT_lcrdv = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CHILinkCreditManagerTX uLinkCredit (
    .clock                                 (clock),
    .reset                                 (reset),
    .io_linkState_stop                     (io_linkState_stop),
    .io_linkState_activate                 (io_linkState_activate),
    .io_linkState_run                      (io_linkState_run),
    .io_linkState_deactivate               (io_linkState_deactivate),
    .io_linkCreditAvailable                (_uLinkCredit_io_linkCreditAvailable),
    .io_linkCreditConsume                  (logicOpDoneValid),
    .io_linkCreditReturn                   (logicLCrdReturn),
    .io_lcrdv                              (regTXDAT_lcrdv),
    .debug_LinkActiveStateNotOneHot        (debug_linkCredit_LinkActiveStateNotOneHot),
    .debug_LinkCreditConsumeOutOfRun       (debug_linkCredit_LinkCreditConsumeOutOfRun),
    .debug_LinkCreditReturnOutOfDeactivate
      (debug_linkCredit_LinkCreditReturnOutOfDeactivate),
    .debug_LinkCreditValidWhenLinkStop     (debug_linkCredit_LinkCreditValidWhenLinkStop),
    .debug_LinkCreditOverflow              (debug_linkCredit_LinkCreditOverflow),
    .debug_LinkCreditUnderflow             (debug_linkCredit_LinkCreditUnderflow)
  );
  assign io_txdat_flitpend = regTXDATFlitPend_flitv;
  assign io_txdat_flitv = regTXDAT_flitv;
  assign io_txdat_flit_QoS = regTXDAT_flit_QoS;
  assign io_txdat_flit_TgtID = regTXDAT_flit_TgtID;
  assign io_txdat_flit_SrcID = regTXDAT_flit_SrcID;
  assign io_txdat_flit_TxnID = regTXDAT_flit_TxnID;
  assign io_txdat_flit_HomeNID = regTXDAT_flit_HomeNID;
  assign io_txdat_flit_Opcode = regTXDAT_flit_Opcode;
  assign io_txdat_flit_RespErr = regTXDAT_flit_RespErr;
  assign io_txdat_flit_CBusy = 3'h0;
  assign io_txdat_flit_CCID = regTXDAT_flit_CCID;
  assign io_txdat_flit_DataID = regTXDAT_flit_DataID;
  assign io_txdat_flit_TagOp = 2'h0;
  assign io_txdat_flit_Tag = 8'h0;
  assign io_txdat_flit_TU = 2'h0;
  assign io_txdat_flit_TraceTag = regTXDAT_flit_TraceTag;
  assign io_txdat_flit_RSVDC = 4'h0;
  assign io_txdat_flit_Data = regTXDAT_flit_Data;
  assign io_txdat_flit_DataCheck = regTXDAT_flit_DataCheck;
  assign io_ageSelect_in_0 =
    io_queue_opValid_valid_0
    & (|{io_queue_opValid_valid_0 & io_queue_opValid_bits_Critical_0_1
           & io_payloadValid_0_1,
         io_queue_opValid_valid_0 & io_queue_opValid_bits_Critical_0_0
           & io_payloadValid_0_0});
  assign io_ageSelect_in_1 =
    io_queue_opValid_valid_1
    & (|{io_queue_opValid_valid_1 & io_queue_opValid_bits_Critical_1_1
           & io_payloadValid_1_1,
         io_queue_opValid_valid_1 & io_queue_opValid_bits_Critical_1_0
           & io_payloadValid_1_0});
  assign io_ageSelect_in_2 =
    io_queue_opValid_valid_2
    & (|{io_queue_opValid_valid_2 & io_queue_opValid_bits_Critical_2_1
           & io_payloadValid_2_1,
         io_queue_opValid_valid_2 & io_queue_opValid_bits_Critical_2_0
           & io_payloadValid_2_0});
  assign io_ageSelect_in_3 =
    io_queue_opValid_valid_3
    & (|{io_queue_opValid_valid_3 & io_queue_opValid_bits_Critical_3_1
           & io_payloadValid_3_1,
         io_queue_opValid_valid_3 & io_queue_opValid_bits_Critical_3_0
           & io_payloadValid_3_0});
  assign io_ageSelect_in_4 =
    io_queue_opValid_valid_4
    & (|{io_queue_opValid_valid_4 & io_queue_opValid_bits_Critical_4_1
           & io_payloadValid_4_1,
         io_queue_opValid_valid_4 & io_queue_opValid_bits_Critical_4_0
           & io_payloadValid_4_0});
  assign io_ageSelect_in_5 =
    io_queue_opValid_valid_5
    & (|{io_queue_opValid_valid_5 & io_queue_opValid_bits_Critical_5_1
           & io_payloadValid_5_1,
         io_queue_opValid_valid_5 & io_queue_opValid_bits_Critical_5_0
           & io_payloadValid_5_0});
  assign io_ageSelect_in_6 =
    io_queue_opValid_valid_6
    & (|{io_queue_opValid_valid_6 & io_queue_opValid_bits_Critical_6_1
           & io_payloadValid_6_1,
         io_queue_opValid_valid_6 & io_queue_opValid_bits_Critical_6_0
           & io_payloadValid_6_0});
  assign io_ageSelect_in_7 =
    io_queue_opValid_valid_7
    & (|{io_queue_opValid_valid_7 & io_queue_opValid_bits_Critical_7_1
           & io_payloadValid_7_1,
         io_queue_opValid_valid_7 & io_queue_opValid_bits_Critical_7_0
           & io_payloadValid_7_0});
  assign io_ageSelect_in_8 =
    io_queue_opValid_valid_8
    & (|{io_queue_opValid_valid_8 & io_queue_opValid_bits_Critical_8_1
           & io_payloadValid_8_1,
         io_queue_opValid_valid_8 & io_queue_opValid_bits_Critical_8_0
           & io_payloadValid_8_0});
  assign io_ageSelect_in_9 =
    io_queue_opValid_valid_9
    & (|{io_queue_opValid_valid_9 & io_queue_opValid_bits_Critical_9_1
           & io_payloadValid_9_1,
         io_queue_opValid_valid_9 & io_queue_opValid_bits_Critical_9_0
           & io_payloadValid_9_0});
  assign io_ageSelect_in_10 =
    io_queue_opValid_valid_10
    & (|{io_queue_opValid_valid_10 & io_queue_opValid_bits_Critical_10_1
           & io_payloadValid_10_1,
         io_queue_opValid_valid_10 & io_queue_opValid_bits_Critical_10_0
           & io_payloadValid_10_0});
  assign io_ageSelect_in_11 =
    io_queue_opValid_valid_11
    & (|{io_queue_opValid_valid_11 & io_queue_opValid_bits_Critical_11_1
           & io_payloadValid_11_1,
         io_queue_opValid_valid_11 & io_queue_opValid_bits_Critical_11_0
           & io_payloadValid_11_0});
  assign io_ageSelect_in_12 =
    io_queue_opValid_valid_12
    & (|{io_queue_opValid_valid_12 & io_queue_opValid_bits_Critical_12_1
           & io_payloadValid_12_1,
         io_queue_opValid_valid_12 & io_queue_opValid_bits_Critical_12_0
           & io_payloadValid_12_0});
  assign io_ageSelect_in_13 =
    io_queue_opValid_valid_13
    & (|{io_queue_opValid_valid_13 & io_queue_opValid_bits_Critical_13_1
           & io_payloadValid_13_1,
         io_queue_opValid_valid_13 & io_queue_opValid_bits_Critical_13_0
           & io_payloadValid_13_0});
  assign io_ageSelect_in_14 =
    io_queue_opValid_valid_14
    & (|{io_queue_opValid_valid_14 & io_queue_opValid_bits_Critical_14_1
           & io_payloadValid_14_1,
         io_queue_opValid_valid_14 & io_queue_opValid_bits_Critical_14_0
           & io_payloadValid_14_0});
  assign io_ageSelect_in_15 =
    io_queue_opValid_valid_15
    & (|{io_queue_opValid_valid_15 & io_queue_opValid_bits_Critical_15_1
           & io_payloadValid_15_1,
         io_queue_opValid_valid_15 & io_queue_opValid_bits_Critical_15_0
           & io_payloadValid_15_0});
  assign io_ageSelect_in_16 =
    io_queue_opValid_valid_16
    & (|{io_queue_opValid_valid_16 & io_queue_opValid_bits_Critical_16_1
           & io_payloadValid_16_1,
         io_queue_opValid_valid_16 & io_queue_opValid_bits_Critical_16_0
           & io_payloadValid_16_0});
  assign io_ageSelect_in_17 =
    io_queue_opValid_valid_17
    & (|{io_queue_opValid_valid_17 & io_queue_opValid_bits_Critical_17_1
           & io_payloadValid_17_1,
         io_queue_opValid_valid_17 & io_queue_opValid_bits_Critical_17_0
           & io_payloadValid_17_0});
  assign io_ageSelect_in_18 =
    io_queue_opValid_valid_18
    & (|{io_queue_opValid_valid_18 & io_queue_opValid_bits_Critical_18_1
           & io_payloadValid_18_1,
         io_queue_opValid_valid_18 & io_queue_opValid_bits_Critical_18_0
           & io_payloadValid_18_0});
  assign io_ageSelect_in_19 =
    io_queue_opValid_valid_19
    & (|{io_queue_opValid_valid_19 & io_queue_opValid_bits_Critical_19_1
           & io_payloadValid_19_1,
         io_queue_opValid_valid_19 & io_queue_opValid_bits_Critical_19_0
           & io_payloadValid_19_0});
  assign io_ageSelect_in_20 =
    io_queue_opValid_valid_20
    & (|{io_queue_opValid_valid_20 & io_queue_opValid_bits_Critical_20_1
           & io_payloadValid_20_1,
         io_queue_opValid_valid_20 & io_queue_opValid_bits_Critical_20_0
           & io_payloadValid_20_0});
  assign io_ageSelect_in_21 =
    io_queue_opValid_valid_21
    & (|{io_queue_opValid_valid_21 & io_queue_opValid_bits_Critical_21_1
           & io_payloadValid_21_1,
         io_queue_opValid_valid_21 & io_queue_opValid_bits_Critical_21_0
           & io_payloadValid_21_0});
  assign io_ageSelect_in_22 =
    io_queue_opValid_valid_22
    & (|{io_queue_opValid_valid_22 & io_queue_opValid_bits_Critical_22_1
           & io_payloadValid_22_1,
         io_queue_opValid_valid_22 & io_queue_opValid_bits_Critical_22_0
           & io_payloadValid_22_0});
  assign io_ageSelect_in_23 =
    io_queue_opValid_valid_23
    & (|{io_queue_opValid_valid_23 & io_queue_opValid_bits_Critical_23_1
           & io_payloadValid_23_1,
         io_queue_opValid_valid_23 & io_queue_opValid_bits_Critical_23_0
           & io_payloadValid_23_0});
  assign io_ageSelect_in_24 =
    io_queue_opValid_valid_24
    & (|{io_queue_opValid_valid_24 & io_queue_opValid_bits_Critical_24_1
           & io_payloadValid_24_1,
         io_queue_opValid_valid_24 & io_queue_opValid_bits_Critical_24_0
           & io_payloadValid_24_0});
  assign io_ageSelect_in_25 =
    io_queue_opValid_valid_25
    & (|{io_queue_opValid_valid_25 & io_queue_opValid_bits_Critical_25_1
           & io_payloadValid_25_1,
         io_queue_opValid_valid_25 & io_queue_opValid_bits_Critical_25_0
           & io_payloadValid_25_0});
  assign io_ageSelect_in_26 =
    io_queue_opValid_valid_26
    & (|{io_queue_opValid_valid_26 & io_queue_opValid_bits_Critical_26_1
           & io_payloadValid_26_1,
         io_queue_opValid_valid_26 & io_queue_opValid_bits_Critical_26_0
           & io_payloadValid_26_0});
  assign io_ageSelect_in_27 =
    io_queue_opValid_valid_27
    & (|{io_queue_opValid_valid_27 & io_queue_opValid_bits_Critical_27_1
           & io_payloadValid_27_1,
         io_queue_opValid_valid_27 & io_queue_opValid_bits_Critical_27_0
           & io_payloadValid_27_0});
  assign io_ageSelect_in_28 =
    io_queue_opValid_valid_28
    & (|{io_queue_opValid_valid_28 & io_queue_opValid_bits_Critical_28_1
           & io_payloadValid_28_1,
         io_queue_opValid_valid_28 & io_queue_opValid_bits_Critical_28_0
           & io_payloadValid_28_0});
  assign io_ageSelect_in_29 =
    io_queue_opValid_valid_29
    & (|{io_queue_opValid_valid_29 & io_queue_opValid_bits_Critical_29_1
           & io_payloadValid_29_1,
         io_queue_opValid_valid_29 & io_queue_opValid_bits_Critical_29_0
           & io_payloadValid_29_0});
  assign io_ageSelect_in_30 =
    io_queue_opValid_valid_30
    & (|{io_queue_opValid_valid_30 & io_queue_opValid_bits_Critical_30_1
           & io_payloadValid_30_1,
         io_queue_opValid_valid_30 & io_queue_opValid_bits_Critical_30_0
           & io_payloadValid_30_0});
  assign io_ageSelect_in_31 =
    io_queue_opValid_valid_31
    & (|{io_queue_opValid_valid_31 & io_queue_opValid_bits_Critical_31_1
           & io_payloadValid_31_1,
         io_queue_opValid_valid_31 & io_queue_opValid_bits_Critical_31_0
           & io_payloadValid_31_0});
  assign io_queue_opRead_strb_0 = io_ageSelect_out_0;
  assign io_queue_opRead_strb_1 = io_ageSelect_out_1;
  assign io_queue_opRead_strb_2 = io_ageSelect_out_2;
  assign io_queue_opRead_strb_3 = io_ageSelect_out_3;
  assign io_queue_opRead_strb_4 = io_ageSelect_out_4;
  assign io_queue_opRead_strb_5 = io_ageSelect_out_5;
  assign io_queue_opRead_strb_6 = io_ageSelect_out_6;
  assign io_queue_opRead_strb_7 = io_ageSelect_out_7;
  assign io_queue_opRead_strb_8 = io_ageSelect_out_8;
  assign io_queue_opRead_strb_9 = io_ageSelect_out_9;
  assign io_queue_opRead_strb_10 = io_ageSelect_out_10;
  assign io_queue_opRead_strb_11 = io_ageSelect_out_11;
  assign io_queue_opRead_strb_12 = io_ageSelect_out_12;
  assign io_queue_opRead_strb_13 = io_ageSelect_out_13;
  assign io_queue_opRead_strb_14 = io_ageSelect_out_14;
  assign io_queue_opRead_strb_15 = io_ageSelect_out_15;
  assign io_queue_opRead_strb_16 = io_ageSelect_out_16;
  assign io_queue_opRead_strb_17 = io_ageSelect_out_17;
  assign io_queue_opRead_strb_18 = io_ageSelect_out_18;
  assign io_queue_opRead_strb_19 = io_ageSelect_out_19;
  assign io_queue_opRead_strb_20 = io_ageSelect_out_20;
  assign io_queue_opRead_strb_21 = io_ageSelect_out_21;
  assign io_queue_opRead_strb_22 = io_ageSelect_out_22;
  assign io_queue_opRead_strb_23 = io_ageSelect_out_23;
  assign io_queue_opRead_strb_24 = io_ageSelect_out_24;
  assign io_queue_opRead_strb_25 = io_ageSelect_out_25;
  assign io_queue_opRead_strb_26 = io_ageSelect_out_26;
  assign io_queue_opRead_strb_27 = io_ageSelect_out_27;
  assign io_queue_opRead_strb_28 = io_ageSelect_out_28;
  assign io_queue_opRead_strb_29 = io_ageSelect_out_29;
  assign io_queue_opRead_strb_30 = io_ageSelect_out_30;
  assign io_queue_opRead_strb_31 = io_ageSelect_out_31;
  assign io_queue_opDone_strb_0 = logicSelectedGo_0;
  assign io_queue_opDone_strb_1 = logicSelectedGo_1;
  assign io_queue_opDone_strb_2 = logicSelectedGo_2;
  assign io_queue_opDone_strb_3 = logicSelectedGo_3;
  assign io_queue_opDone_strb_4 = logicSelectedGo_4;
  assign io_queue_opDone_strb_5 = logicSelectedGo_5;
  assign io_queue_opDone_strb_6 = logicSelectedGo_6;
  assign io_queue_opDone_strb_7 = logicSelectedGo_7;
  assign io_queue_opDone_strb_8 = logicSelectedGo_8;
  assign io_queue_opDone_strb_9 = logicSelectedGo_9;
  assign io_queue_opDone_strb_10 = logicSelectedGo_10;
  assign io_queue_opDone_strb_11 = logicSelectedGo_11;
  assign io_queue_opDone_strb_12 = logicSelectedGo_12;
  assign io_queue_opDone_strb_13 = logicSelectedGo_13;
  assign io_queue_opDone_strb_14 = logicSelectedGo_14;
  assign io_queue_opDone_strb_15 = logicSelectedGo_15;
  assign io_queue_opDone_strb_16 = logicSelectedGo_16;
  assign io_queue_opDone_strb_17 = logicSelectedGo_17;
  assign io_queue_opDone_strb_18 = logicSelectedGo_18;
  assign io_queue_opDone_strb_19 = logicSelectedGo_19;
  assign io_queue_opDone_strb_20 = logicSelectedGo_20;
  assign io_queue_opDone_strb_21 = logicSelectedGo_21;
  assign io_queue_opDone_strb_22 = logicSelectedGo_22;
  assign io_queue_opDone_strb_23 = logicSelectedGo_23;
  assign io_queue_opDone_strb_24 = logicSelectedGo_24;
  assign io_queue_opDone_strb_25 = logicSelectedGo_25;
  assign io_queue_opDone_strb_26 = logicSelectedGo_26;
  assign io_queue_opDone_strb_27 = logicSelectedGo_27;
  assign io_queue_opDone_strb_28 = logicSelectedGo_28;
  assign io_queue_opDone_strb_29 = logicSelectedGo_29;
  assign io_queue_opDone_strb_30 = logicSelectedGo_30;
  assign io_queue_opDone_strb_31 = logicSelectedGo_31;
  assign io_queue_opDone_bits_CompData =
    io_queue_opRead_bits_CompData_valid & ~io_queue_operandRead_bits_Count;
  assign io_queue_infoRead_strb_0 = io_ageSelect_out_0;
  assign io_queue_infoRead_strb_1 = io_ageSelect_out_1;
  assign io_queue_infoRead_strb_2 = io_ageSelect_out_2;
  assign io_queue_infoRead_strb_3 = io_ageSelect_out_3;
  assign io_queue_infoRead_strb_4 = io_ageSelect_out_4;
  assign io_queue_infoRead_strb_5 = io_ageSelect_out_5;
  assign io_queue_infoRead_strb_6 = io_ageSelect_out_6;
  assign io_queue_infoRead_strb_7 = io_ageSelect_out_7;
  assign io_queue_infoRead_strb_8 = io_ageSelect_out_8;
  assign io_queue_infoRead_strb_9 = io_ageSelect_out_9;
  assign io_queue_infoRead_strb_10 = io_ageSelect_out_10;
  assign io_queue_infoRead_strb_11 = io_ageSelect_out_11;
  assign io_queue_infoRead_strb_12 = io_ageSelect_out_12;
  assign io_queue_infoRead_strb_13 = io_ageSelect_out_13;
  assign io_queue_infoRead_strb_14 = io_ageSelect_out_14;
  assign io_queue_infoRead_strb_15 = io_ageSelect_out_15;
  assign io_queue_infoRead_strb_16 = io_ageSelect_out_16;
  assign io_queue_infoRead_strb_17 = io_ageSelect_out_17;
  assign io_queue_infoRead_strb_18 = io_ageSelect_out_18;
  assign io_queue_infoRead_strb_19 = io_ageSelect_out_19;
  assign io_queue_infoRead_strb_20 = io_ageSelect_out_20;
  assign io_queue_infoRead_strb_21 = io_ageSelect_out_21;
  assign io_queue_infoRead_strb_22 = io_ageSelect_out_22;
  assign io_queue_infoRead_strb_23 = io_ageSelect_out_23;
  assign io_queue_infoRead_strb_24 = io_ageSelect_out_24;
  assign io_queue_infoRead_strb_25 = io_ageSelect_out_25;
  assign io_queue_infoRead_strb_26 = io_ageSelect_out_26;
  assign io_queue_infoRead_strb_27 = io_ageSelect_out_27;
  assign io_queue_infoRead_strb_28 = io_ageSelect_out_28;
  assign io_queue_infoRead_strb_29 = io_ageSelect_out_29;
  assign io_queue_infoRead_strb_30 = io_ageSelect_out_30;
  assign io_queue_infoRead_strb_31 = io_ageSelect_out_31;
  assign io_queue_operandRead_strb_0 = io_ageSelect_out_0;
  assign io_queue_operandRead_strb_1 = io_ageSelect_out_1;
  assign io_queue_operandRead_strb_2 = io_ageSelect_out_2;
  assign io_queue_operandRead_strb_3 = io_ageSelect_out_3;
  assign io_queue_operandRead_strb_4 = io_ageSelect_out_4;
  assign io_queue_operandRead_strb_5 = io_ageSelect_out_5;
  assign io_queue_operandRead_strb_6 = io_ageSelect_out_6;
  assign io_queue_operandRead_strb_7 = io_ageSelect_out_7;
  assign io_queue_operandRead_strb_8 = io_ageSelect_out_8;
  assign io_queue_operandRead_strb_9 = io_ageSelect_out_9;
  assign io_queue_operandRead_strb_10 = io_ageSelect_out_10;
  assign io_queue_operandRead_strb_11 = io_ageSelect_out_11;
  assign io_queue_operandRead_strb_12 = io_ageSelect_out_12;
  assign io_queue_operandRead_strb_13 = io_ageSelect_out_13;
  assign io_queue_operandRead_strb_14 = io_ageSelect_out_14;
  assign io_queue_operandRead_strb_15 = io_ageSelect_out_15;
  assign io_queue_operandRead_strb_16 = io_ageSelect_out_16;
  assign io_queue_operandRead_strb_17 = io_ageSelect_out_17;
  assign io_queue_operandRead_strb_18 = io_ageSelect_out_18;
  assign io_queue_operandRead_strb_19 = io_ageSelect_out_19;
  assign io_queue_operandRead_strb_20 = io_ageSelect_out_20;
  assign io_queue_operandRead_strb_21 = io_ageSelect_out_21;
  assign io_queue_operandRead_strb_22 = io_ageSelect_out_22;
  assign io_queue_operandRead_strb_23 = io_ageSelect_out_23;
  assign io_queue_operandRead_strb_24 = io_ageSelect_out_24;
  assign io_queue_operandRead_strb_25 = io_ageSelect_out_25;
  assign io_queue_operandRead_strb_26 = io_ageSelect_out_26;
  assign io_queue_operandRead_strb_27 = io_ageSelect_out_27;
  assign io_queue_operandRead_strb_28 = io_ageSelect_out_28;
  assign io_queue_operandRead_strb_29 = io_ageSelect_out_29;
  assign io_queue_operandRead_strb_30 = io_ageSelect_out_30;
  assign io_queue_operandRead_strb_31 = io_ageSelect_out_31;
  assign io_queue_operandWrite_strb_0 = logicSelectedGo_0;
  assign io_queue_operandWrite_strb_1 = logicSelectedGo_1;
  assign io_queue_operandWrite_strb_2 = logicSelectedGo_2;
  assign io_queue_operandWrite_strb_3 = logicSelectedGo_3;
  assign io_queue_operandWrite_strb_4 = logicSelectedGo_4;
  assign io_queue_operandWrite_strb_5 = logicSelectedGo_5;
  assign io_queue_operandWrite_strb_6 = logicSelectedGo_6;
  assign io_queue_operandWrite_strb_7 = logicSelectedGo_7;
  assign io_queue_operandWrite_strb_8 = logicSelectedGo_8;
  assign io_queue_operandWrite_strb_9 = logicSelectedGo_9;
  assign io_queue_operandWrite_strb_10 = logicSelectedGo_10;
  assign io_queue_operandWrite_strb_11 = logicSelectedGo_11;
  assign io_queue_operandWrite_strb_12 = logicSelectedGo_12;
  assign io_queue_operandWrite_strb_13 = logicSelectedGo_13;
  assign io_queue_operandWrite_strb_14 = logicSelectedGo_14;
  assign io_queue_operandWrite_strb_15 = logicSelectedGo_15;
  assign io_queue_operandWrite_strb_16 = logicSelectedGo_16;
  assign io_queue_operandWrite_strb_17 = logicSelectedGo_17;
  assign io_queue_operandWrite_strb_18 = logicSelectedGo_18;
  assign io_queue_operandWrite_strb_19 = logicSelectedGo_19;
  assign io_queue_operandWrite_strb_20 = logicSelectedGo_20;
  assign io_queue_operandWrite_strb_21 = logicSelectedGo_21;
  assign io_queue_operandWrite_strb_22 = logicSelectedGo_22;
  assign io_queue_operandWrite_strb_23 = logicSelectedGo_23;
  assign io_queue_operandWrite_strb_24 = logicSelectedGo_24;
  assign io_queue_operandWrite_strb_25 = logicSelectedGo_25;
  assign io_queue_operandWrite_strb_26 = logicSelectedGo_26;
  assign io_queue_operandWrite_strb_27 = logicSelectedGo_27;
  assign io_queue_operandWrite_strb_28 = logicSelectedGo_28;
  assign io_queue_operandWrite_strb_29 = logicSelectedGo_29;
  assign io_queue_operandWrite_strb_30 = logicSelectedGo_30;
  assign io_queue_operandWrite_strb_31 = logicSelectedGo_31;
  assign io_queue_operandWrite_bits_Critical_0 = io_queue_operandRead_bits_Critical_1;
  assign io_queue_operandWrite_bits_Critical_1 = io_queue_operandRead_bits_Critical_0;
  assign io_queue_operandWrite_bits_Count = 1'(io_queue_operandRead_bits_Count - 1'h1);
  assign io_payloadRead_en = logicOpDoneValid;
  assign io_payloadRead_strb_0 = io_ageSelect_out_0;
  assign io_payloadRead_strb_1 = io_ageSelect_out_1;
  assign io_payloadRead_strb_2 = io_ageSelect_out_2;
  assign io_payloadRead_strb_3 = io_ageSelect_out_3;
  assign io_payloadRead_strb_4 = io_ageSelect_out_4;
  assign io_payloadRead_strb_5 = io_ageSelect_out_5;
  assign io_payloadRead_strb_6 = io_ageSelect_out_6;
  assign io_payloadRead_strb_7 = io_ageSelect_out_7;
  assign io_payloadRead_strb_8 = io_ageSelect_out_8;
  assign io_payloadRead_strb_9 = io_ageSelect_out_9;
  assign io_payloadRead_strb_10 = io_ageSelect_out_10;
  assign io_payloadRead_strb_11 = io_ageSelect_out_11;
  assign io_payloadRead_strb_12 = io_ageSelect_out_12;
  assign io_payloadRead_strb_13 = io_ageSelect_out_13;
  assign io_payloadRead_strb_14 = io_ageSelect_out_14;
  assign io_payloadRead_strb_15 = io_ageSelect_out_15;
  assign io_payloadRead_strb_16 = io_ageSelect_out_16;
  assign io_payloadRead_strb_17 = io_ageSelect_out_17;
  assign io_payloadRead_strb_18 = io_ageSelect_out_18;
  assign io_payloadRead_strb_19 = io_ageSelect_out_19;
  assign io_payloadRead_strb_20 = io_ageSelect_out_20;
  assign io_payloadRead_strb_21 = io_ageSelect_out_21;
  assign io_payloadRead_strb_22 = io_ageSelect_out_22;
  assign io_payloadRead_strb_23 = io_ageSelect_out_23;
  assign io_payloadRead_strb_24 = io_ageSelect_out_24;
  assign io_payloadRead_strb_25 = io_ageSelect_out_25;
  assign io_payloadRead_strb_26 = io_ageSelect_out_26;
  assign io_payloadRead_strb_27 = io_ageSelect_out_27;
  assign io_payloadRead_strb_28 = io_ageSelect_out_28;
  assign io_payloadRead_strb_29 = io_ageSelect_out_29;
  assign io_payloadRead_strb_30 = io_ageSelect_out_30;
  assign io_payloadRead_strb_31 = io_ageSelect_out_31;
  assign io_payloadRead_index_0 = io_queue_operandRead_bits_Critical_0;
  assign io_payloadRead_index_1 = io_queue_operandRead_bits_Critical_1;
endmodule

