// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module WriteBuffer_44(
  input         clock,
  input         reset,
  input         io_write_0_valid,
  input  [8:0]  io_write_0_bits_entry_tag,
  input  [1:0]  io_write_0_bits_entry_confidenceCnt_value,
  input  [18:0] io_write_0_bits_entry_targetOffset_offset_addr,
  input  [3:0]  io_write_0_bits_entry_targetOffset_pointer,
  input         io_write_0_bits_entry_targetOffset_usePcRegion,
  input         io_write_0_bits_entry_usefulCnt_value,
  input  [6:0]  io_write_0_bits_setIdx,
  input  [37:0] io_write_0_bits_bitmask,
  input         io_read_0_ready,
  output        io_read_0_valid,
  output        io_read_0_bits_entry_valid,
  output [8:0]  io_read_0_bits_entry_tag,
  output [1:0]  io_read_0_bits_entry_confidenceCnt_value,
  output [18:0] io_read_0_bits_entry_targetOffset_offset_addr,
  output [3:0]  io_read_0_bits_entry_targetOffset_pointer,
  output        io_read_0_bits_entry_targetOffset_usePcRegion,
  output        io_read_0_bits_entry_usefulCnt_value,
  output        io_read_0_bits_entry_paddingBit,
  output [6:0]  io_read_0_bits_setIdx,
  output [37:0] io_read_0_bits_bitmask
);

  reg              needWrite_0_0;
  wire             readValidVec_0_0 = needWrite_0_0;
  reg              needWrite_0_1;
  wire             readValidVec_0_1 = needWrite_0_1;
  reg              needWrite_0_2;
  wire             readValidVec_0_2 = needWrite_0_2;
  reg              needWrite_0_3;
  wire             readValidVec_0_3 = needWrite_0_3;
  reg              entries_0_0_entry_valid;
  reg  [8:0]       entries_0_0_entry_tag;
  reg  [1:0]       entries_0_0_entry_confidenceCnt_value;
  reg  [18:0]      entries_0_0_entry_targetOffset_offset_addr;
  reg  [3:0]       entries_0_0_entry_targetOffset_pointer;
  reg              entries_0_0_entry_targetOffset_usePcRegion;
  reg              entries_0_0_entry_usefulCnt_value;
  reg              entries_0_0_entry_paddingBit;
  reg  [6:0]       entries_0_0_setIdx;
  reg  [37:0]      entries_0_0_bitmask;
  reg              entries_0_1_entry_valid;
  reg  [8:0]       entries_0_1_entry_tag;
  reg  [1:0]       entries_0_1_entry_confidenceCnt_value;
  reg  [18:0]      entries_0_1_entry_targetOffset_offset_addr;
  reg  [3:0]       entries_0_1_entry_targetOffset_pointer;
  reg              entries_0_1_entry_targetOffset_usePcRegion;
  reg              entries_0_1_entry_usefulCnt_value;
  reg              entries_0_1_entry_paddingBit;
  reg  [6:0]       entries_0_1_setIdx;
  reg  [37:0]      entries_0_1_bitmask;
  reg              entries_0_2_entry_valid;
  reg  [8:0]       entries_0_2_entry_tag;
  reg  [1:0]       entries_0_2_entry_confidenceCnt_value;
  reg  [18:0]      entries_0_2_entry_targetOffset_offset_addr;
  reg  [3:0]       entries_0_2_entry_targetOffset_pointer;
  reg              entries_0_2_entry_targetOffset_usePcRegion;
  reg              entries_0_2_entry_usefulCnt_value;
  reg              entries_0_2_entry_paddingBit;
  reg  [6:0]       entries_0_2_setIdx;
  reg  [37:0]      entries_0_2_bitmask;
  reg              entries_0_3_entry_valid;
  reg  [8:0]       entries_0_3_entry_tag;
  reg  [1:0]       entries_0_3_entry_confidenceCnt_value;
  reg  [18:0]      entries_0_3_entry_targetOffset_offset_addr;
  reg  [3:0]       entries_0_3_entry_targetOffset_pointer;
  reg              entries_0_3_entry_targetOffset_usePcRegion;
  reg              entries_0_3_entry_usefulCnt_value;
  reg              entries_0_3_entry_paddingBit;
  reg  [6:0]       entries_0_3_setIdx;
  reg  [37:0]      entries_0_3_bitmask;
  reg              valids_0_0;
  reg              valids_0_1;
  reg              valids_0_2;
  reg              valids_0_3;
  wire             _hitMask_0_0_T = io_write_0_valid & valids_0_0;
  wire             _hitMask_0_0_T_1 = io_write_0_bits_setIdx == entries_0_0_setIdx;
  wire             _hitMask_0_1_T = io_write_0_valid & valids_0_1;
  wire             _hitMask_0_1_T_1 = io_write_0_bits_setIdx == entries_0_1_setIdx;
  wire             _hitMask_0_2_T = io_write_0_valid & valids_0_2;
  wire             _hitMask_0_2_T_1 = io_write_0_bits_setIdx == entries_0_2_setIdx;
  wire             _hitMask_0_3_T = io_write_0_valid & valids_0_3;
  wire             _hitMask_0_3_T_1 = io_write_0_bits_setIdx == entries_0_3_setIdx;
  wire             hitMask_0_1 = _hitMask_0_1_T & _hitMask_0_1_T_1;
  wire             hitMask_0_2 = _hitMask_0_2_T & _hitMask_0_2_T_1;
  wire             hitMask_0_3 = _hitMask_0_3_T & _hitMask_0_3_T_1;
  wire             _hitRowsVec_T = _hitMask_0_0_T & _hitMask_0_0_T_1 | hitMask_0_1;
  wire             hitRowsVec_0 = _hitRowsVec_T | hitMask_0_2 | hitMask_0_3;
  wire [1:0]       hitRowIdxVec_0 =
    {|{hitMask_0_3, hitMask_0_2}, hitMask_0_3 | hitMask_0_1};
  wire [3:0]       _GEN =
    {{entries_0_3_entry_valid},
     {entries_0_2_entry_valid},
     {entries_0_1_entry_valid},
     {entries_0_0_entry_valid}};
  wire [3:0][8:0]  _GEN_0 =
    {{entries_0_3_entry_tag},
     {entries_0_2_entry_tag},
     {entries_0_1_entry_tag},
     {entries_0_0_entry_tag}};
  wire [3:0][1:0]  _GEN_1 =
    {{entries_0_3_entry_confidenceCnt_value},
     {entries_0_2_entry_confidenceCnt_value},
     {entries_0_1_entry_confidenceCnt_value},
     {entries_0_0_entry_confidenceCnt_value}};
  wire [3:0][18:0] _GEN_2 =
    {{entries_0_3_entry_targetOffset_offset_addr},
     {entries_0_2_entry_targetOffset_offset_addr},
     {entries_0_1_entry_targetOffset_offset_addr},
     {entries_0_0_entry_targetOffset_offset_addr}};
  wire [3:0][3:0]  _GEN_3 =
    {{entries_0_3_entry_targetOffset_pointer},
     {entries_0_2_entry_targetOffset_pointer},
     {entries_0_1_entry_targetOffset_pointer},
     {entries_0_0_entry_targetOffset_pointer}};
  wire [3:0]       _GEN_4 =
    {{entries_0_3_entry_targetOffset_usePcRegion},
     {entries_0_2_entry_targetOffset_usePcRegion},
     {entries_0_1_entry_targetOffset_usePcRegion},
     {entries_0_0_entry_targetOffset_usePcRegion}};
  wire [3:0]       _GEN_5 =
    {{entries_0_3_entry_usefulCnt_value},
     {entries_0_2_entry_usefulCnt_value},
     {entries_0_1_entry_usefulCnt_value},
     {entries_0_0_entry_usefulCnt_value}};
  wire [3:0]       _GEN_6 =
    {{entries_0_3_entry_paddingBit},
     {entries_0_2_entry_paddingBit},
     {entries_0_1_entry_paddingBit},
     {entries_0_0_entry_paddingBit}};
  wire [3:0][6:0]  _GEN_7 =
    {{entries_0_3_setIdx},
     {entries_0_2_setIdx},
     {entries_0_1_setIdx},
     {entries_0_0_setIdx}};
  wire [3:0][37:0] _GEN_8 =
    {{entries_0_3_bitmask},
     {entries_0_2_bitmask},
     {entries_0_1_bitmask},
     {entries_0_0_bitmask}};
  reg  [2:0]       state_reg;
  wire             emptyVec_0 =
    ~(readValidVec_0_0 | readValidVec_0_1 | readValidVec_0_2 | readValidVec_0_3);
  wire [1:0]       readIdx =
    readValidVec_0_0 ? 2'h0 : readValidVec_0_1 ? 2'h1 : {1'h1, ~readValidVec_0_2};
  wire [1:0]       replacerWay_0 =
    {state_reg[2], state_reg[2] ? state_reg[1] : state_reg[0]};
  wire             setIdxHitVec_1 = _hitMask_0_1_T & _hitMask_0_1_T_1;
  wire             setIdxHitVec_2 = _hitMask_0_2_T & _hitMask_0_2_T_1;
  wire             setIdxHitVec_3 = _hitMask_0_3_T & _hitMask_0_3_T_1;
  wire             hit = _hitRowsVec_T | hitMask_0_2 | hitMask_0_3;
  wire [3:0]       _GEN_9 =
    {{needWrite_0_3}, {needWrite_0_2}, {needWrite_0_1}, {needWrite_0_0}};
  wire             hitNotWritten = hit & _GEN_9[hitRowIdxVec_0];
  wire             hitWritten = hit & ~_GEN_9[hitRowIdxVec_0];
  wire [1:0]       victim =
    _hitMask_0_0_T & _hitMask_0_0_T_1 | setIdxHitVec_1 | setIdxHitVec_2 | setIdxHitVec_3
      ? {|{setIdxHitVec_3, setIdxHitVec_2}, setIdxHitVec_3 | setIdxHitVec_1}
      : needWrite_0_0 & needWrite_0_1 & needWrite_0_2 & needWrite_0_3
          ? replacerWay_0
          : needWrite_0_0 ? (needWrite_0_1 ? {1'h1, needWrite_0_2} : 2'h1) : 2'h0;
  wire             _GEN_10 = ~hit & victim == 2'h0;
  wire             _GEN_11 = ~hit & victim == 2'h1;
  wire             _GEN_12 = ~hit & victim == 2'h2;
  wire             _GEN_13 = ~hit & (&victim);
  wire             _GEN_14 = hitRowIdxVec_0 == 2'h0;
  wire             _GEN_15 = _GEN_14 | _GEN_10;
  wire             _GEN_16 = hitRowIdxVec_0 == 2'h1;
  wire             _GEN_17 = _GEN_16 | _GEN_11;
  wire             _GEN_18 = hitRowIdxVec_0 == 2'h2;
  wire             _GEN_19 = _GEN_18 | _GEN_12;
  wire             _GEN_20 = (&hitRowIdxVec_0) | _GEN_13;
  wire             _GEN_21 =
    {_GEN[hitRowIdxVec_0],
     _GEN_0[hitRowIdxVec_0],
     _GEN_1[hitRowIdxVec_0],
     _GEN_2[hitRowIdxVec_0],
     _GEN_3[hitRowIdxVec_0],
     _GEN_4[hitRowIdxVec_0],
     _GEN_5[hitRowIdxVec_0],
     _GEN_6[hitRowIdxVec_0],
     _GEN_7[hitRowIdxVec_0],
     _GEN_8[hitRowIdxVec_0]} == {1'h1,
                                 io_write_0_bits_entry_tag,
                                 io_write_0_bits_entry_confidenceCnt_value,
                                 io_write_0_bits_entry_targetOffset_offset_addr,
                                 io_write_0_bits_entry_targetOffset_pointer,
                                 io_write_0_bits_entry_targetOffset_usePcRegion,
                                 io_write_0_bits_entry_usefulCnt_value,
                                 1'h0,
                                 io_write_0_bits_setIdx,
                                 io_write_0_bits_bitmask};
  wire             _GEN_22 = ~hit | hitNotWritten | ~hitWritten | _GEN_21;
  wire             _GEN_23 = io_read_0_ready & ~emptyVec_0;
  wire             _GEN_24 = hit & (hitNotWritten | ~(~hitWritten | _GEN_21));
  wire [1:0]       writeTouchVec_0_bits = io_write_0_valid & ~hit ? victim : 2'h0;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      needWrite_0_0 <= 1'h0;
      needWrite_0_1 <= 1'h0;
      needWrite_0_2 <= 1'h0;
      needWrite_0_3 <= 1'h0;
      entries_0_0_entry_valid <= 1'h0;
      entries_0_0_entry_tag <= 9'h0;
      entries_0_0_entry_confidenceCnt_value <= 2'h0;
      entries_0_0_entry_targetOffset_offset_addr <= 19'h0;
      entries_0_0_entry_targetOffset_pointer <= 4'h0;
      entries_0_0_entry_targetOffset_usePcRegion <= 1'h0;
      entries_0_0_entry_usefulCnt_value <= 1'h0;
      entries_0_0_entry_paddingBit <= 1'h0;
      entries_0_0_setIdx <= 7'h0;
      entries_0_0_bitmask <= 38'h0;
      entries_0_1_entry_valid <= 1'h0;
      entries_0_1_entry_tag <= 9'h0;
      entries_0_1_entry_confidenceCnt_value <= 2'h0;
      entries_0_1_entry_targetOffset_offset_addr <= 19'h0;
      entries_0_1_entry_targetOffset_pointer <= 4'h0;
      entries_0_1_entry_targetOffset_usePcRegion <= 1'h0;
      entries_0_1_entry_usefulCnt_value <= 1'h0;
      entries_0_1_entry_paddingBit <= 1'h0;
      entries_0_1_setIdx <= 7'h0;
      entries_0_1_bitmask <= 38'h0;
      entries_0_2_entry_valid <= 1'h0;
      entries_0_2_entry_tag <= 9'h0;
      entries_0_2_entry_confidenceCnt_value <= 2'h0;
      entries_0_2_entry_targetOffset_offset_addr <= 19'h0;
      entries_0_2_entry_targetOffset_pointer <= 4'h0;
      entries_0_2_entry_targetOffset_usePcRegion <= 1'h0;
      entries_0_2_entry_usefulCnt_value <= 1'h0;
      entries_0_2_entry_paddingBit <= 1'h0;
      entries_0_2_setIdx <= 7'h0;
      entries_0_2_bitmask <= 38'h0;
      entries_0_3_entry_valid <= 1'h0;
      entries_0_3_entry_tag <= 9'h0;
      entries_0_3_entry_confidenceCnt_value <= 2'h0;
      entries_0_3_entry_targetOffset_offset_addr <= 19'h0;
      entries_0_3_entry_targetOffset_pointer <= 4'h0;
      entries_0_3_entry_targetOffset_usePcRegion <= 1'h0;
      entries_0_3_entry_usefulCnt_value <= 1'h0;
      entries_0_3_entry_paddingBit <= 1'h0;
      entries_0_3_setIdx <= 7'h0;
      entries_0_3_bitmask <= 38'h0;
      valids_0_0 <= 1'h0;
      valids_0_1 <= 1'h0;
      valids_0_2 <= 1'h0;
      valids_0_3 <= 1'h0;
      state_reg <= 3'h0;
    end
    else begin
      needWrite_0_0 <=
        ~(_GEN_23 & readIdx == 2'h0)
        & (io_write_0_valid
             ? (_GEN_22 ? _GEN_10 | needWrite_0_0 : _GEN_15 | needWrite_0_0)
             : needWrite_0_0);
      needWrite_0_1 <=
        ~(_GEN_23 & readIdx == 2'h1)
        & (io_write_0_valid
             ? (_GEN_22 ? _GEN_11 | needWrite_0_1 : _GEN_17 | needWrite_0_1)
             : needWrite_0_1);
      needWrite_0_2 <=
        ~(_GEN_23 & readIdx == 2'h2)
        & (io_write_0_valid
             ? (_GEN_22 ? _GEN_12 | needWrite_0_2 : _GEN_19 | needWrite_0_2)
             : needWrite_0_2);
      needWrite_0_3 <=
        ~(_GEN_23 & (&readIdx))
        & (io_write_0_valid
             ? (_GEN_22 ? _GEN_13 | needWrite_0_3 : _GEN_20 | needWrite_0_3)
             : needWrite_0_3);
      if (io_write_0_valid) begin
        entries_0_0_entry_valid <=
          _GEN_24 ? _GEN_15 | entries_0_0_entry_valid : _GEN_10 | entries_0_0_entry_valid;
        entries_0_0_entry_paddingBit <=
          _GEN_24
            ? ~_GEN_15 & entries_0_0_entry_paddingBit
            : ~_GEN_10 & entries_0_0_entry_paddingBit;
        entries_0_1_entry_valid <=
          _GEN_24 ? _GEN_17 | entries_0_1_entry_valid : _GEN_11 | entries_0_1_entry_valid;
        entries_0_1_entry_paddingBit <=
          _GEN_24
            ? ~_GEN_17 & entries_0_1_entry_paddingBit
            : ~_GEN_11 & entries_0_1_entry_paddingBit;
        entries_0_2_entry_valid <=
          _GEN_24 ? _GEN_19 | entries_0_2_entry_valid : _GEN_12 | entries_0_2_entry_valid;
        entries_0_2_entry_paddingBit <=
          _GEN_24
            ? ~_GEN_19 & entries_0_2_entry_paddingBit
            : ~_GEN_12 & entries_0_2_entry_paddingBit;
        entries_0_3_entry_valid <=
          _GEN_24 ? _GEN_20 | entries_0_3_entry_valid : _GEN_13 | entries_0_3_entry_valid;
        entries_0_3_entry_paddingBit <=
          _GEN_24
            ? ~_GEN_20 & entries_0_3_entry_paddingBit
            : ~_GEN_13 & entries_0_3_entry_paddingBit;
        valids_0_0 <= _GEN_24 ? _GEN_15 | valids_0_0 : _GEN_10 | valids_0_0;
        valids_0_1 <= _GEN_24 ? _GEN_17 | valids_0_1 : _GEN_11 | valids_0_1;
        valids_0_2 <= _GEN_24 ? _GEN_19 | valids_0_2 : _GEN_12 | valids_0_2;
        valids_0_3 <= _GEN_24 ? _GEN_20 | valids_0_3 : _GEN_13 | valids_0_3;
      end
      if (io_write_0_valid
          & (hit
               ? (hitNotWritten ? _GEN_15 : hitWritten & ~_GEN_21 & _GEN_14 | _GEN_10)
               : _GEN_10)) begin
        entries_0_0_entry_tag <= io_write_0_bits_entry_tag;
        entries_0_0_entry_confidenceCnt_value <=
          io_write_0_bits_entry_confidenceCnt_value;
        entries_0_0_entry_targetOffset_offset_addr <=
          io_write_0_bits_entry_targetOffset_offset_addr;
        entries_0_0_entry_targetOffset_pointer <=
          io_write_0_bits_entry_targetOffset_pointer;
        entries_0_0_entry_targetOffset_usePcRegion <=
          io_write_0_bits_entry_targetOffset_usePcRegion;
        entries_0_0_entry_usefulCnt_value <= io_write_0_bits_entry_usefulCnt_value;
        entries_0_0_setIdx <= io_write_0_bits_setIdx;
        entries_0_0_bitmask <= io_write_0_bits_bitmask;
      end
      if (io_write_0_valid
          & (hit
               ? (hitNotWritten ? _GEN_17 : hitWritten & ~_GEN_21 & _GEN_16 | _GEN_11)
               : _GEN_11)) begin
        entries_0_1_entry_tag <= io_write_0_bits_entry_tag;
        entries_0_1_entry_confidenceCnt_value <=
          io_write_0_bits_entry_confidenceCnt_value;
        entries_0_1_entry_targetOffset_offset_addr <=
          io_write_0_bits_entry_targetOffset_offset_addr;
        entries_0_1_entry_targetOffset_pointer <=
          io_write_0_bits_entry_targetOffset_pointer;
        entries_0_1_entry_targetOffset_usePcRegion <=
          io_write_0_bits_entry_targetOffset_usePcRegion;
        entries_0_1_entry_usefulCnt_value <= io_write_0_bits_entry_usefulCnt_value;
        entries_0_1_setIdx <= io_write_0_bits_setIdx;
        entries_0_1_bitmask <= io_write_0_bits_bitmask;
      end
      if (io_write_0_valid
          & (hit
               ? (hitNotWritten ? _GEN_19 : hitWritten & ~_GEN_21 & _GEN_18 | _GEN_12)
               : _GEN_12)) begin
        entries_0_2_entry_tag <= io_write_0_bits_entry_tag;
        entries_0_2_entry_confidenceCnt_value <=
          io_write_0_bits_entry_confidenceCnt_value;
        entries_0_2_entry_targetOffset_offset_addr <=
          io_write_0_bits_entry_targetOffset_offset_addr;
        entries_0_2_entry_targetOffset_pointer <=
          io_write_0_bits_entry_targetOffset_pointer;
        entries_0_2_entry_targetOffset_usePcRegion <=
          io_write_0_bits_entry_targetOffset_usePcRegion;
        entries_0_2_entry_usefulCnt_value <= io_write_0_bits_entry_usefulCnt_value;
        entries_0_2_setIdx <= io_write_0_bits_setIdx;
        entries_0_2_bitmask <= io_write_0_bits_bitmask;
      end
      if (io_write_0_valid
          & (hit
               ? (hitNotWritten
                    ? _GEN_20
                    : hitWritten & ~_GEN_21 & (&hitRowIdxVec_0) | _GEN_13)
               : _GEN_13)) begin
        entries_0_3_entry_tag <= io_write_0_bits_entry_tag;
        entries_0_3_entry_confidenceCnt_value <=
          io_write_0_bits_entry_confidenceCnt_value;
        entries_0_3_entry_targetOffset_offset_addr <=
          io_write_0_bits_entry_targetOffset_offset_addr;
        entries_0_3_entry_targetOffset_pointer <=
          io_write_0_bits_entry_targetOffset_pointer;
        entries_0_3_entry_targetOffset_usePcRegion <=
          io_write_0_bits_entry_targetOffset_usePcRegion;
        entries_0_3_entry_usefulCnt_value <= io_write_0_bits_entry_usefulCnt_value;
        entries_0_3_setIdx <= io_write_0_bits_setIdx;
        entries_0_3_bitmask <= io_write_0_bits_bitmask;
      end
      if (io_write_0_valid & ~hit)
        state_reg <=
          {~(writeTouchVec_0_bits[1]),
           writeTouchVec_0_bits[1] ? ~(writeTouchVec_0_bits[0]) : state_reg[1],
           writeTouchVec_0_bits[1] ? state_reg[0] : ~(writeTouchVec_0_bits[0])};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:10];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        needWrite_0_0 = _RANDOM[4'h0][0];
        needWrite_0_1 = _RANDOM[4'h0][1];
        needWrite_0_2 = _RANDOM[4'h0][2];
        needWrite_0_3 = _RANDOM[4'h0][3];
        entries_0_0_entry_valid = _RANDOM[4'h0][4];
        entries_0_0_entry_tag = _RANDOM[4'h0][13:5];
        entries_0_0_entry_confidenceCnt_value = _RANDOM[4'h0][15:14];
        entries_0_0_entry_targetOffset_offset_addr =
          {_RANDOM[4'h0][31:16], _RANDOM[4'h1][2:0]};
        entries_0_0_entry_targetOffset_pointer = _RANDOM[4'h1][6:3];
        entries_0_0_entry_targetOffset_usePcRegion = _RANDOM[4'h1][7];
        entries_0_0_entry_usefulCnt_value = _RANDOM[4'h1][8];
        entries_0_0_entry_paddingBit = _RANDOM[4'h1][9];
        entries_0_0_setIdx = _RANDOM[4'h1][16:10];
        entries_0_0_bitmask = {_RANDOM[4'h1][31:17], _RANDOM[4'h2][22:0]};
        entries_0_1_entry_valid = _RANDOM[4'h2][23];
        entries_0_1_entry_tag = {_RANDOM[4'h2][31:24], _RANDOM[4'h3][0]};
        entries_0_1_entry_confidenceCnt_value = _RANDOM[4'h3][2:1];
        entries_0_1_entry_targetOffset_offset_addr = _RANDOM[4'h3][21:3];
        entries_0_1_entry_targetOffset_pointer = _RANDOM[4'h3][25:22];
        entries_0_1_entry_targetOffset_usePcRegion = _RANDOM[4'h3][26];
        entries_0_1_entry_usefulCnt_value = _RANDOM[4'h3][27];
        entries_0_1_entry_paddingBit = _RANDOM[4'h3][28];
        entries_0_1_setIdx = {_RANDOM[4'h3][31:29], _RANDOM[4'h4][3:0]};
        entries_0_1_bitmask = {_RANDOM[4'h4][31:4], _RANDOM[4'h5][9:0]};
        entries_0_2_entry_valid = _RANDOM[4'h5][10];
        entries_0_2_entry_tag = _RANDOM[4'h5][19:11];
        entries_0_2_entry_confidenceCnt_value = _RANDOM[4'h5][21:20];
        entries_0_2_entry_targetOffset_offset_addr =
          {_RANDOM[4'h5][31:22], _RANDOM[4'h6][8:0]};
        entries_0_2_entry_targetOffset_pointer = _RANDOM[4'h6][12:9];
        entries_0_2_entry_targetOffset_usePcRegion = _RANDOM[4'h6][13];
        entries_0_2_entry_usefulCnt_value = _RANDOM[4'h6][14];
        entries_0_2_entry_paddingBit = _RANDOM[4'h6][15];
        entries_0_2_setIdx = _RANDOM[4'h6][22:16];
        entries_0_2_bitmask = {_RANDOM[4'h6][31:23], _RANDOM[4'h7][28:0]};
        entries_0_3_entry_valid = _RANDOM[4'h7][29];
        entries_0_3_entry_tag = {_RANDOM[4'h7][31:30], _RANDOM[4'h8][6:0]};
        entries_0_3_entry_confidenceCnt_value = _RANDOM[4'h8][8:7];
        entries_0_3_entry_targetOffset_offset_addr = _RANDOM[4'h8][27:9];
        entries_0_3_entry_targetOffset_pointer = _RANDOM[4'h8][31:28];
        entries_0_3_entry_targetOffset_usePcRegion = _RANDOM[4'h9][0];
        entries_0_3_entry_usefulCnt_value = _RANDOM[4'h9][1];
        entries_0_3_entry_paddingBit = _RANDOM[4'h9][2];
        entries_0_3_setIdx = _RANDOM[4'h9][9:3];
        entries_0_3_bitmask = {_RANDOM[4'h9][31:10], _RANDOM[4'hA][15:0]};
        valids_0_0 = _RANDOM[4'hA][16];
        valids_0_1 = _RANDOM[4'hA][17];
        valids_0_2 = _RANDOM[4'hA][18];
        valids_0_3 = _RANDOM[4'hA][19];
        state_reg = _RANDOM[4'hA][22:20];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        needWrite_0_0 = 1'h0;
        needWrite_0_1 = 1'h0;
        needWrite_0_2 = 1'h0;
        needWrite_0_3 = 1'h0;
        entries_0_0_entry_valid = 1'h0;
        entries_0_0_entry_tag = 9'h0;
        entries_0_0_entry_confidenceCnt_value = 2'h0;
        entries_0_0_entry_targetOffset_offset_addr = 19'h0;
        entries_0_0_entry_targetOffset_pointer = 4'h0;
        entries_0_0_entry_targetOffset_usePcRegion = 1'h0;
        entries_0_0_entry_usefulCnt_value = 1'h0;
        entries_0_0_entry_paddingBit = 1'h0;
        entries_0_0_setIdx = 7'h0;
        entries_0_0_bitmask = 38'h0;
        entries_0_1_entry_valid = 1'h0;
        entries_0_1_entry_tag = 9'h0;
        entries_0_1_entry_confidenceCnt_value = 2'h0;
        entries_0_1_entry_targetOffset_offset_addr = 19'h0;
        entries_0_1_entry_targetOffset_pointer = 4'h0;
        entries_0_1_entry_targetOffset_usePcRegion = 1'h0;
        entries_0_1_entry_usefulCnt_value = 1'h0;
        entries_0_1_entry_paddingBit = 1'h0;
        entries_0_1_setIdx = 7'h0;
        entries_0_1_bitmask = 38'h0;
        entries_0_2_entry_valid = 1'h0;
        entries_0_2_entry_tag = 9'h0;
        entries_0_2_entry_confidenceCnt_value = 2'h0;
        entries_0_2_entry_targetOffset_offset_addr = 19'h0;
        entries_0_2_entry_targetOffset_pointer = 4'h0;
        entries_0_2_entry_targetOffset_usePcRegion = 1'h0;
        entries_0_2_entry_usefulCnt_value = 1'h0;
        entries_0_2_entry_paddingBit = 1'h0;
        entries_0_2_setIdx = 7'h0;
        entries_0_2_bitmask = 38'h0;
        entries_0_3_entry_valid = 1'h0;
        entries_0_3_entry_tag = 9'h0;
        entries_0_3_entry_confidenceCnt_value = 2'h0;
        entries_0_3_entry_targetOffset_offset_addr = 19'h0;
        entries_0_3_entry_targetOffset_pointer = 4'h0;
        entries_0_3_entry_targetOffset_usePcRegion = 1'h0;
        entries_0_3_entry_usefulCnt_value = 1'h0;
        entries_0_3_entry_paddingBit = 1'h0;
        entries_0_3_setIdx = 7'h0;
        entries_0_3_bitmask = 38'h0;
        valids_0_0 = 1'h0;
        valids_0_1 = 1'h0;
        valids_0_2 = 1'h0;
        valids_0_3 = 1'h0;
        state_reg = 3'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_read_0_valid = ~emptyVec_0;
  assign io_read_0_bits_entry_valid = _GEN[readIdx];
  assign io_read_0_bits_entry_tag = _GEN_0[readIdx];
  assign io_read_0_bits_entry_confidenceCnt_value = _GEN_1[readIdx];
  assign io_read_0_bits_entry_targetOffset_offset_addr = _GEN_2[readIdx];
  assign io_read_0_bits_entry_targetOffset_pointer = _GEN_3[readIdx];
  assign io_read_0_bits_entry_targetOffset_usePcRegion = _GEN_4[readIdx];
  assign io_read_0_bits_entry_usefulCnt_value = _GEN_5[readIdx];
  assign io_read_0_bits_entry_paddingBit = _GEN_6[readIdx];
  assign io_read_0_bits_setIdx = _GEN_7[readIdx];
  assign io_read_0_bits_bitmask = _GEN_8[readIdx];
endmodule

